"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.2, "H": 40, "J": 32, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 193.2, "H": 40, "J": 32, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 4, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 5, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 6, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 7, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.941479, 'e_o_k': [1.498864, 1.387542], 'p_i': 10, 'u_i': 1.1793, 'theta': 0.8507},
        {'id': 1, 'e_m': 4.586898, 'e_o_k': [3.758094, 5.415702], 'p_i': 20, 'u_i': 3.4868, 'theta': 0.8935},
        {'id': 2, 'e_m': 9.102646, 'e_o_k': [1.043849, 0.777282], 'p_i': 40, 'u_i': 1.5119, 'theta': 0.8923},
        {'id': 3, 'e_m': 10.000000, 'e_o_k': [0.959648, 0.868801, 0.581565], 'p_i': 20, 'u_i': 3.9514, 'theta': 0.6049},
        {'id': 4, 'e_m': 2.297342, 'e_o_k': [0.142700], 'p_i': 10, 'u_i': 3.8106, 'theta': 0.8354},
        {'id': 5, 'e_m': 5.000000, 'e_o_k': [0.182486, 0.214280], 'p_i': 10, 'u_i': 3.8065, 'theta': 0.8848},
        {'id': 6, 'e_m': 2.311447, 'e_o_k': [1.272068], 'p_i': 10, 'u_i': 3.2074, 'theta': 0.6363},
        {'id': 7, 'e_m': 2.288621, 'e_o_k': [0.847144, 0.979757, 1.589610], 'p_i': 10, 'u_i': 4.6067, 'theta': 0.8624},
        {'id': 8, 'e_m': 9.307352, 'e_o_k': [7.067949, 4.062114], 'p_i': 40, 'u_i': 4.2153, 'theta': 0.9739},
        {'id': 9, 'e_m': 4.655112, 'e_o_k': [1.217189, 1.187515], 'p_i': 20, 'u_i': 3.6588, 'theta': 0.7647},
        {'id': 10, 'e_m': 10.000000, 'e_o_k': [1.190689, 0.812017, 0.738447], 'p_i': 20, 'u_i': 2.0659, 'theta': 0.7765},
        {'id': 11, 'e_m': 9.875215, 'e_o_k': [0.565832], 'p_i': 20, 'u_i': 1.7965, 'theta': 0.6280},
    ]
    B_BUDGET = 193.200000
    return processors, tasks, B_BUDGET
