"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 57.96, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1038, "set": 38, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 57.96, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1038, "set": 38, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.5, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.5, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.836921, 'e_o_k': [0.035771], 'p_i': 10, 'u_i': 3.0188, 'theta': 0.8655},
        {'id': 1, 'e_m': 5.877037, 'e_o_k': [0.717225, 0.685171], 'p_i': 20, 'u_i': 2.8843, 'theta': 0.7270},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [3.528366], 'p_i': 40, 'u_i': 3.4959, 'theta': 0.6893},
        {'id': 3, 'e_m': 7.555060, 'e_o_k': [0.042306, 0.054471, 0.026891], 'p_i': 20, 'u_i': 1.0101, 'theta': 0.6068},
        {'id': 4, 'e_m': 1.447030, 'e_o_k': [0.156211, 0.162895], 'p_i': 10, 'u_i': 4.9062, 'theta': 0.9783},
    ]
    B_BUDGET = 57.960000
    return processors, tasks, B_BUDGET
