"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600003, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1029, "set": 29, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.600003, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1029, "set": 29, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.7, 0.75, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.7, 0.75, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.351810, 'e_o_k': [0.058714, 0.118346, 0.096037, 0.092503], 'p_i': 10, 'u_i': 2.6459, 'theta': 0.8154},
        {'id': 1, 'e_m': 4.567645, 'e_o_k': [0.092610, 0.188719, 0.271447], 'p_i': 20, 'u_i': 1.7922, 'theta': 0.8780},
        {'id': 2, 'e_m': 5.457468, 'e_o_k': [10.914936], 'p_i': 40, 'u_i': 4.6189, 'theta': 0.6024},
        {'id': 3, 'e_m': 40.000000, 'e_o_k': [6.799644, 6.234588], 'p_i': 80, 'u_i': 4.6705, 'theta': 0.8131},
    ]
    B_BUDGET = 96.600003
    return processors, tasks, B_BUDGET
