"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 34.499997, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.5, "seed": 1089, "set": 89, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}
"""

_SPEC = '{"B": 34.499997, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.5, "seed": 1089, "set": 89, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [1.802576, 1.497146], 'p_i': 10, 'u_i': 1.4880, 'theta': 0.9780},
        {'id': 1, 'e_m': 0.671568, 'e_o_k': [0.728103, 0.615033], 'p_i': 20, 'u_i': 4.7396, 'theta': 0.9197},
        {'id': 2, 'e_m': 1.291787, 'e_o_k': [0.665243, 1.918332], 'p_i': 40, 'u_i': 1.2208, 'theta': 0.6897},
        {'id': 3, 'e_m': 2.450024, 'e_o_k': [0.038617, 0.052820, 0.045098, 0.037880, 0.051837], 'p_i': 20, 'u_i': 1.4702, 'theta': 0.7324},
        {'id': 4, 'e_m': 3.116257, 'e_o_k': [0.136319, 0.133370], 'p_i': 10, 'u_i': 3.8735, 'theta': 0.6595},
    ]
    B_BUDGET = 34.499997
    return processors, tasks, B_BUDGET
