"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.200004, "H": 40, "J": 26, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1003, "set": 3, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 193.200004, "H": 40, "J": 26, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1003, "set": 3, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
        {'id': 4, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
        {'id': 5, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
        {'id': 6, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
        {'id': 7, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.790845, 'e_o_k': [0.853699, 1.652085], 'p_i': 10, 'u_i': 1.7945, 'theta': 0.7026},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [3.172084], 'p_i': 20, 'u_i': 1.5443, 'theta': 0.8969},
        {'id': 2, 'e_m': 14.800219, 'e_o_k': [12.841896, 16.758542], 'p_i': 40, 'u_i': 1.8110, 'theta': 0.7364},
        {'id': 3, 'e_m': 12.901039, 'e_o_k': [1.335561, 0.818914, 1.169262], 'p_i': 40, 'u_i': 4.3893, 'theta': 0.7548},
        {'id': 4, 'e_m': 5.314171, 'e_o_k': [5.222855], 'p_i': 20, 'u_i': 3.0100, 'theta': 0.8032},
        {'id': 5, 'e_m': 5.361996, 'e_o_k': [1.724844], 'p_i': 20, 'u_i': 2.8057, 'theta': 0.7701},
        {'id': 6, 'e_m': 2.638835, 'e_o_k': [0.024720, 0.021479, 0.024138], 'p_i': 10, 'u_i': 3.2808, 'theta': 0.6510},
        {'id': 7, 'e_m': 20.000000, 'e_o_k': [6.604223], 'p_i': 40, 'u_i': 3.8953, 'theta': 0.8049},
        {'id': 8, 'e_m': 6.727830, 'e_o_k': [1.764050], 'p_i': 20, 'u_i': 3.5095, 'theta': 0.6939},
        {'id': 9, 'e_m': 2.661602, 'e_o_k': [0.028429, 0.017048, 0.027068], 'p_i': 10, 'u_i': 3.1439, 'theta': 0.8387},
        {'id': 10, 'e_m': 7.287144, 'e_o_k': [0.439352], 'p_i': 20, 'u_i': 2.4214, 'theta': 0.7644},
        {'id': 11, 'e_m': 10.551334, 'e_o_k': [2.059820, 3.170751], 'p_i': 40, 'u_i': 4.3137, 'theta': 0.7322},
    ]
    B_BUDGET = 193.200004
    return processors, tasks, B_BUDGET
