"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 115.919992, "H": 80, "J": 27, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1003, "set": 3, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 115.919992, "H": 80, "J": 27, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1003, "set": 3, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.55, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.111060], 'p_i': 10, 'u_i': 3.1630, 'theta': 0.8797},
        {'id': 1, 'e_m': 2.355174, 'e_o_k': [0.053736, 0.055982, 0.050652, 0.063181], 'p_i': 20, 'u_i': 2.5101, 'theta': 0.9676},
        {'id': 2, 'e_m': 4.974941, 'e_o_k': [0.344043, 0.255935], 'p_i': 40, 'u_i': 4.0806, 'theta': 0.9018},
        {'id': 3, 'e_m': 2.995282, 'e_o_k': [0.475681, 0.708914], 'p_i': 80, 'u_i': 3.4844, 'theta': 0.7003},
        {'id': 4, 'e_m': 2.898659, 'e_o_k': [2.157924], 'p_i': 80, 'u_i': 4.4326, 'theta': 0.6811},
        {'id': 5, 'e_m': 14.901376, 'e_o_k': [1.371913, 1.777364, 1.055587], 'p_i': 80, 'u_i': 2.5476, 'theta': 0.6797},
        {'id': 6, 'e_m': 2.954249, 'e_o_k': [0.046276, 0.056059, 0.060049, 0.053263], 'p_i': 10, 'u_i': 2.7013, 'theta': 0.8517},
        {'id': 7, 'e_m': 12.100056, 'e_o_k': [0.816890, 0.667029, 0.388477], 'p_i': 40, 'u_i': 3.4222, 'theta': 0.9582},
    ]
    B_BUDGET = 115.919992
    return processors, tasks, B_BUDGET
