"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 38.640003, "H": 40, "J": 15, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1098, "set": 98, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 38.640003, "H": 40, "J": 15, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1098, "set": 98, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.5, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.5, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.065200, 'e_o_k': [0.216995, 0.271713, 0.251381, 0.195048], 'p_i': 10, 'u_i': 3.4489, 'theta': 0.8312},
        {'id': 1, 'e_m': 9.414161, 'e_o_k': [0.005893, 0.002382], 'p_i': 20, 'u_i': 1.4704, 'theta': 0.9775},
        {'id': 2, 'e_m': 3.681307, 'e_o_k': [0.392189], 'p_i': 40, 'u_i': 4.4803, 'theta': 0.8028},
        {'id': 3, 'e_m': 2.547636, 'e_o_k': [0.168146, 0.163036, 0.171539], 'p_i': 10, 'u_i': 4.2804, 'theta': 0.8105},
        {'id': 4, 'e_m': 0.759757, 'e_o_k': [0.115078, 0.085651, 0.135560, 0.123669], 'p_i': 10, 'u_i': 3.1631, 'theta': 0.8828},
    ]
    B_BUDGET = 38.640003
    return processors, tasks, B_BUDGET
