"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 77.279994, "H": 80, "J": 37, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1085, "set": 85, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 77.279994, "H": 80, "J": 37, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1085, "set": 85, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.8, 0.85, 0.9, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.8, 0.85, 0.9, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.156130, 'e_o_k': [0.130521], 'p_i': 10, 'u_i': 1.6478, 'theta': 0.7808},
        {'id': 1, 'e_m': 5.118532, 'e_o_k': [0.058931, 0.058391], 'p_i': 20, 'u_i': 4.4296, 'theta': 0.8608},
        {'id': 2, 'e_m': 3.382726, 'e_o_k': [1.151694, 0.886281], 'p_i': 40, 'u_i': 4.3499, 'theta': 0.9586},
        {'id': 3, 'e_m': 5.779171, 'e_o_k': [3.473781], 'p_i': 80, 'u_i': 1.0468, 'theta': 0.6634},
        {'id': 4, 'e_m': 0.321911, 'e_o_k': [0.049479, 0.031301], 'p_i': 10, 'u_i': 4.3216, 'theta': 0.7374},
        {'id': 5, 'e_m': 1.360006, 'e_o_k': [0.094948, 0.086266, 0.082793, 0.096530], 'p_i': 10, 'u_i': 1.0302, 'theta': 0.8358},
        {'id': 6, 'e_m': 1.313179, 'e_o_k': [0.086443, 0.108689], 'p_i': 40, 'u_i': 2.8697, 'theta': 0.9923},
        {'id': 7, 'e_m': 1.412628, 'e_o_k': [0.296627, 0.457375], 'p_i': 20, 'u_i': 2.0976, 'theta': 0.8230},
    ]
    B_BUDGET = 77.279994
    return processors, tasks, B_BUDGET
