"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600003, "H": 80, "J": 26, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.9}
"""

_SPEC = '{"B": 96.600003, "H": 80, "J": 26, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.9}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.357137, 'e_o_k': [0.224099, 0.248838, 0.222907, 0.259678], 'p_i': 10, 'u_i': 2.3485, 'theta': 0.9829},
        {'id': 1, 'e_m': 4.602886, 'e_o_k': [1.590442], 'p_i': 20, 'u_i': 1.5032, 'theta': 0.9812},
        {'id': 2, 'e_m': 7.321138, 'e_o_k': [2.575224, 2.335922], 'p_i': 40, 'u_i': 3.6197, 'theta': 0.9257},
        {'id': 3, 'e_m': 0.790605, 'e_o_k': [0.658196, 0.923015], 'p_i': 80, 'u_i': 4.9551, 'theta': 0.9235},
        {'id': 4, 'e_m': 3.283775, 'e_o_k': [0.807914, 1.040527], 'p_i': 80, 'u_i': 4.8822, 'theta': 0.9271},
        {'id': 5, 'e_m': 2.360239, 'e_o_k': [1.582694], 'p_i': 20, 'u_i': 4.2738, 'theta': 0.9833},
        {'id': 6, 'e_m': 2.867608, 'e_o_k': [2.301384], 'p_i': 40, 'u_i': 1.4125, 'theta': 0.9593},
        {'id': 7, 'e_m': 2.209634, 'e_o_k': [0.217252, 0.234890], 'p_i': 20, 'u_i': 2.7426, 'theta': 0.9450},
    ]
    B_BUDGET = 96.600003
    return processors, tasks, B_BUDGET
