"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300001, "H": 40, "J": 14, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1043, "set": 43, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}
"""

_SPEC = '{"B": 48.300001, "H": 40, "J": 14, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1043, "set": 43, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.55, 0.65, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.55, 0.65, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.159613, 'e_o_k': [0.136815, 0.085964, 0.096446], 'p_i': 10, 'u_i': 4.4173, 'theta': 0.9391},
        {'id': 1, 'e_m': 1.373297, 'e_o_k': [2.746595], 'p_i': 20, 'u_i': 2.4366, 'theta': 0.8322},
        {'id': 2, 'e_m': 3.162135, 'e_o_k': [0.714772, 0.590472, 0.783292], 'p_i': 40, 'u_i': 1.8297, 'theta': 0.8585},
        {'id': 3, 'e_m': 4.341617, 'e_o_k': [1.886874], 'p_i': 10, 'u_i': 3.3407, 'theta': 0.7041},
        {'id': 4, 'e_m': 2.106531, 'e_o_k': [0.390298, 0.468028, 0.521315], 'p_i': 20, 'u_i': 2.2255, 'theta': 0.7477},
        {'id': 5, 'e_m': 11.873290, 'e_o_k': [0.834596], 'p_i': 40, 'u_i': 4.7201, 'theta': 0.9258},
    ]
    B_BUDGET = 48.300001
    return processors, tasks, B_BUDGET
