"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300003, "H": 40, "J": 23, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 48.300003, "H": 40, "J": 23, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.654742, 'e_o_k': [0.622981, 0.650930], 'p_i': 10, 'u_i': 4.8915, 'theta': 0.6197},
        {'id': 1, 'e_m': 5.117180, 'e_o_k': [0.553902, 0.550774], 'p_i': 20, 'u_i': 4.0450, 'theta': 0.7068},
        {'id': 2, 'e_m': 1.740349, 'e_o_k': [0.282131], 'p_i': 40, 'u_i': 4.6571, 'theta': 0.7650},
        {'id': 3, 'e_m': 1.084958, 'e_o_k': [2.169915], 'p_i': 40, 'u_i': 1.0774, 'theta': 0.9632},
        {'id': 4, 'e_m': 1.841674, 'e_o_k': [0.935486, 1.027934], 'p_i': 40, 'u_i': 4.1364, 'theta': 0.7922},
        {'id': 5, 'e_m': 2.634205, 'e_o_k': [0.687900], 'p_i': 10, 'u_i': 2.4995, 'theta': 0.6693},
        {'id': 6, 'e_m': 0.118464, 'e_o_k': [0.236928], 'p_i': 10, 'u_i': 3.5004, 'theta': 0.7002},
        {'id': 7, 'e_m': 3.799919, 'e_o_k': [0.901851, 0.480232, 0.732368], 'p_i': 40, 'u_i': 4.4669, 'theta': 0.9265},
        {'id': 8, 'e_m': 0.268455, 'e_o_k': [0.063345, 0.075338, 0.087034], 'p_i': 10, 'u_i': 2.2775, 'theta': 0.8570},
        {'id': 9, 'e_m': 2.595275, 'e_o_k': [0.911463, 0.651449], 'p_i': 40, 'u_i': 2.8663, 'theta': 0.9141},
    ]
    B_BUDGET = 48.300003
    return processors, tasks, B_BUDGET
