"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 18, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 18, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.034378, 'e_o_k': [0.040275, 0.028482], 'p_i': 10, 'u_i': 2.1776, 'theta': 0.6911},
        {'id': 1, 'e_m': 1.458207, 'e_o_k': [2.156471], 'p_i': 20, 'u_i': 1.9722, 'theta': 0.6045},
        {'id': 2, 'e_m': 4.068514, 'e_o_k': [0.077390, 0.069856, 0.060852], 'p_i': 40, 'u_i': 2.5739, 'theta': 0.9045},
        {'id': 3, 'e_m': 6.004377, 'e_o_k': [0.193516, 0.146358], 'p_i': 40, 'u_i': 4.8557, 'theta': 0.9657},
        {'id': 4, 'e_m': 9.222250, 'e_o_k': [3.156959, 3.363211], 'p_i': 40, 'u_i': 3.0660, 'theta': 0.7982},
        {'id': 5, 'e_m': 0.221826, 'e_o_k': [0.022856, 0.019461, 0.025018], 'p_i': 10, 'u_i': 1.9481, 'theta': 0.7455},
        {'id': 6, 'e_m': 4.053927, 'e_o_k': [0.758814, 0.985863], 'p_i': 10, 'u_i': 3.5004, 'theta': 0.7002},
        {'id': 7, 'e_m': 0.547920, 'e_o_k': [0.339508, 0.493530, 0.262803], 'p_i': 40, 'u_i': 4.5431, 'theta': 0.8248},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
