"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300001, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1015, "set": 15, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 48.300001, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1015, "set": 15, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 1.0]},
        {'id': 1, 'frequencies': [0.35, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.792870, 'e_o_k': [0.488536], 'p_i': 10, 'u_i': 4.4310, 'theta': 0.9218},
        {'id': 1, 'e_m': 1.609087, 'e_o_k': [1.574851, 1.364266], 'p_i': 20, 'u_i': 3.9907, 'theta': 0.8872},
        {'id': 2, 'e_m': 12.314161, 'e_o_k': [0.769074, 0.972031], 'p_i': 40, 'u_i': 4.7249, 'theta': 0.8363},
        {'id': 3, 'e_m': 6.000936, 'e_o_k': [1.962618], 'p_i': 20, 'u_i': 2.0216, 'theta': 0.7125},
        {'id': 4, 'e_m': 9.294312, 'e_o_k': [3.868059, 2.633224], 'p_i': 40, 'u_i': 2.3636, 'theta': 0.6820},
    ]
    B_BUDGET = 48.300001
    return processors, tasks, B_BUDGET
