"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.859999, "H": 40, "J": 11, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1012, "set": 12, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.3, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.859999, "H": 40, "J": 11, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1012, "set": 12, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.3, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.45, 0.55, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.45, 0.55, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.018280, 'e_o_k': [0.153267, 0.075436, 0.089565, 0.112419, 0.125611], 'p_i': 10, 'u_i': 4.5368, 'theta': 0.8241},
        {'id': 1, 'e_m': 4.387595, 'e_o_k': [2.630478, 1.336499], 'p_i': 20, 'u_i': 2.1438, 'theta': 0.6432},
        {'id': 2, 'e_m': 6.285991, 'e_o_k': [0.258167, 0.343183], 'p_i': 40, 'u_i': 4.8131, 'theta': 0.9604},
        {'id': 3, 'e_m': 3.704060, 'e_o_k': [0.554732], 'p_i': 20, 'u_i': 3.0442, 'theta': 0.6902},
        {'id': 4, 'e_m': 6.728790, 'e_o_k': [0.012596, 0.014218, 0.011581, 0.014460, 0.012164], 'p_i': 20, 'u_i': 3.6043, 'theta': 0.9673},
    ]
    B_BUDGET = 41.859999
    return processors, tasks, B_BUDGET
