"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600002, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.600002, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.227491, 'e_o_k': [0.288899], 'p_i': 10, 'u_i': 3.4259, 'theta': 0.7062},
        {'id': 1, 'e_m': 6.169180, 'e_o_k': [2.162481, 2.563749, 2.285902], 'p_i': 20, 'u_i': 3.1655, 'theta': 0.7096},
        {'id': 2, 'e_m': 14.086532, 'e_o_k': [0.468022, 0.590327, 0.536180, 0.605786], 'p_i': 40, 'u_i': 2.9364, 'theta': 0.8450},
        {'id': 3, 'e_m': 9.330289, 'e_o_k': [5.239652], 'p_i': 80, 'u_i': 1.1647, 'theta': 0.7557},
    ]
    B_BUDGET = 96.600002
    return processors, tasks, B_BUDGET
