"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 13.8, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.2, "seed": 1088, "set": 88, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 13.8, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.2, "seed": 1088, "set": 88, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.65, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.65, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.909964, 'e_o_k': [0.726289, 0.876131, 0.671042], 'p_i': 10, 'u_i': 2.9718, 'theta': 0.9562},
        {'id': 1, 'e_m': 0.992079, 'e_o_k': [1.984159], 'p_i': 20, 'u_i': 3.9189, 'theta': 0.9602},
        {'id': 2, 'e_m': 10.807643, 'e_o_k': [1.135219, 1.631481, 1.126855], 'p_i': 40, 'u_i': 1.1658, 'theta': 0.8715},
        {'id': 3, 'e_m': 2.878710, 'e_o_k': [0.224999, 0.159417, 0.165711, 0.173347], 'p_i': 10, 'u_i': 2.2188, 'theta': 0.9960},
        {'id': 4, 'e_m': 2.026751, 'e_o_k': [0.023717, 0.025910, 0.025566], 'p_i': 20, 'u_i': 2.3002, 'theta': 0.8705},
    ]
    B_BUDGET = 13.800000
    return processors, tasks, B_BUDGET
