"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1079, "set": 79, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1079, "set": 79, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.7, 1.0]},
        {'id': 1, 'frequencies': [0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.564705, 'e_o_k': [0.160373, 0.178216, 0.204483, 0.280957], 'p_i': 10, 'u_i': 3.1608, 'theta': 0.8783},
        {'id': 1, 'e_m': 1.973912, 'e_o_k': [2.064309], 'p_i': 20, 'u_i': 4.3282, 'theta': 0.9101},
        {'id': 2, 'e_m': 1.541315, 'e_o_k': [0.618029, 0.585731, 0.296115, 0.567659, 0.636475], 'p_i': 40, 'u_i': 2.4883, 'theta': 0.9773},
        {'id': 3, 'e_m': 4.235816, 'e_o_k': [0.728678, 0.651553], 'p_i': 10, 'u_i': 2.6529, 'theta': 0.9684},
        {'id': 4, 'e_m': 3.308773, 'e_o_k': [1.304948, 1.625076, 1.420310], 'p_i': 40, 'u_i': 4.7040, 'theta': 0.8670},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
