"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.55, 0.6, 0.7, 0.75, 0.8, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.55, 0.6, 0.7, 0.75, 0.8, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.030512, 'e_o_k': [0.565685, 0.557938, 0.633187, 0.483159], 'p_i': 10, 'u_i': 3.2091, 'theta': 0.6990},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [1.101948], 'p_i': 20, 'u_i': 2.1408, 'theta': 0.7776},
        {'id': 2, 'e_m': 1.993724, 'e_o_k': [1.456592, 1.576369], 'p_i': 40, 'u_i': 2.9643, 'theta': 0.8874},
        {'id': 3, 'e_m': 0.945800, 'e_o_k': [0.239671, 0.386054, 0.413492, 0.366587], 'p_i': 10, 'u_i': 1.6303, 'theta': 0.7855},
        {'id': 4, 'e_m': 2.101028, 'e_o_k': [0.038457, 0.033592, 0.036040, 0.031943, 0.040019], 'p_i': 40, 'u_i': 3.6141, 'theta': 0.9506},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
