"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 23, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1029, "set": 29, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 23, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1029, "set": 29, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.7, 0.75, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.7, 0.75, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.110192, 'e_o_k': [0.045300], 'p_i': 10, 'u_i': 1.3082, 'theta': 0.8128},
        {'id': 1, 'e_m': 2.164664, 'e_o_k': [1.359908, 1.580457, 1.034744], 'p_i': 20, 'u_i': 4.5319, 'theta': 0.9603},
        {'id': 2, 'e_m': 1.378530, 'e_o_k': [2.340294], 'p_i': 40, 'u_i': 4.2208, 'theta': 0.6195},
        {'id': 3, 'e_m': 2.608116, 'e_o_k': [0.062094, 0.040886, 0.044733], 'p_i': 40, 'u_i': 2.1439, 'theta': 0.9179},
        {'id': 4, 'e_m': 2.523137, 'e_o_k': [0.153539, 0.155469, 0.220685], 'p_i': 40, 'u_i': 2.7570, 'theta': 0.9116},
        {'id': 5, 'e_m': 0.142225, 'e_o_k': [0.284450], 'p_i': 40, 'u_i': 3.3404, 'theta': 0.8151},
        {'id': 6, 'e_m': 0.046502, 'e_o_k': [0.038686, 0.028768, 0.025549], 'p_i': 40, 'u_i': 2.2794, 'theta': 0.7109},
        {'id': 7, 'e_m': 0.398885, 'e_o_k': [0.779045], 'p_i': 20, 'u_i': 3.6303, 'theta': 0.9510},
        {'id': 8, 'e_m': 4.949611, 'e_o_k': [1.238368], 'p_i': 20, 'u_i': 3.5002, 'theta': 0.9878},
        {'id': 9, 'e_m': 1.150750, 'e_o_k': [0.416202, 0.395307], 'p_i': 20, 'u_i': 2.3532, 'theta': 0.7237},
        {'id': 10, 'e_m': 0.067909, 'e_o_k': [0.135819], 'p_i': 20, 'u_i': 4.1268, 'theta': 0.6387},
        {'id': 11, 'e_m': 2.849270, 'e_o_k': [0.635987], 'p_i': 10, 'u_i': 2.8025, 'theta': 0.7017},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
