"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 12, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1055, "set": 55, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 12, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1055, "set": 55, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.55, 0.75, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.55, 0.75, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.545411, 'e_o_k': [0.394039], 'p_i': 10, 'u_i': 4.9671, 'theta': 0.9644},
        {'id': 1, 'e_m': 0.985954, 'e_o_k': [0.264252, 0.152468, 0.245712], 'p_i': 20, 'u_i': 2.5248, 'theta': 0.8923},
        {'id': 2, 'e_m': 3.689876, 'e_o_k': [3.299716], 'p_i': 40, 'u_i': 2.2979, 'theta': 0.6317},
        {'id': 3, 'e_m': 5.623906, 'e_o_k': [1.420234], 'p_i': 20, 'u_i': 4.9798, 'theta': 0.7880},
        {'id': 4, 'e_m': 4.281859, 'e_o_k': [0.233503, 0.185690, 0.145957], 'p_i': 20, 'u_i': 4.4552, 'theta': 0.8367},
        {'id': 5, 'e_m': 12.345045, 'e_o_k': [4.790741, 5.037755], 'p_i': 40, 'u_i': 2.5245, 'theta': 0.8059},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
