"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600004, "H": 80, "J": 36, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1041, "set": 41, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 96.600004, "H": 80, "J": 36, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1041, "set": 41, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 1.0]},
        {'id': 1, 'frequencies': [0.4, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.015534, 'e_o_k': [0.089345, 0.066361], 'p_i': 10, 'u_i': 3.6091, 'theta': 0.6779},
        {'id': 1, 'e_m': 5.542753, 'e_o_k': [1.786279], 'p_i': 20, 'u_i': 3.1207, 'theta': 0.8083},
        {'id': 2, 'e_m': 3.597516, 'e_o_k': [1.803016, 1.360850, 1.239822], 'p_i': 40, 'u_i': 1.7300, 'theta': 0.9781},
        {'id': 3, 'e_m': 0.728334, 'e_o_k': [0.442243, 0.564361, 0.450065], 'p_i': 80, 'u_i': 4.8394, 'theta': 0.6299},
        {'id': 4, 'e_m': 2.085784, 'e_o_k': [1.391937, 1.127753], 'p_i': 80, 'u_i': 4.0265, 'theta': 0.7380},
        {'id': 5, 'e_m': 1.102967, 'e_o_k': [0.689694, 0.837450], 'p_i': 10, 'u_i': 2.1788, 'theta': 0.6920},
        {'id': 6, 'e_m': 0.278305, 'e_o_k': [0.007595, 0.013228, 0.014799, 0.009533], 'p_i': 20, 'u_i': 4.0183, 'theta': 0.9600},
        {'id': 7, 'e_m': 2.719826, 'e_o_k': [0.209268, 0.199062, 0.171032, 0.224105], 'p_i': 10, 'u_i': 3.7621, 'theta': 0.9511},
    ]
    B_BUDGET = 96.600004
    return processors, tasks, B_BUDGET
