"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.6, "H": 80, "J": 30, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1091, "set": 91, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 96.6, "H": 80, "J": 30, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1091, "set": 91, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.7, 0.8, 0.85, 0.9, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.7, 0.8, 0.85, 0.9, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.101517, 'e_o_k': [1.254981], 'p_i': 10, 'u_i': 4.6424, 'theta': 0.8435},
        {'id': 1, 'e_m': 1.063319, 'e_o_k': [0.108004, 0.100061, 0.138964], 'p_i': 20, 'u_i': 1.1976, 'theta': 0.6831},
        {'id': 2, 'e_m': 7.957914, 'e_o_k': [5.678547], 'p_i': 40, 'u_i': 3.9329, 'theta': 0.8672},
        {'id': 3, 'e_m': 4.049133, 'e_o_k': [1.828019, 1.407848, 1.448559, 1.404517], 'p_i': 80, 'u_i': 2.6598, 'theta': 0.9893},
        {'id': 4, 'e_m': 0.158512, 'e_o_k': [0.096739], 'p_i': 10, 'u_i': 1.4707, 'theta': 0.6443},
        {'id': 5, 'e_m': 2.208223, 'e_o_k': [1.480372, 1.158980, 0.608953, 1.168140], 'p_i': 80, 'u_i': 3.0479, 'theta': 0.9130},
        {'id': 6, 'e_m': 4.021194, 'e_o_k': [0.100209, 0.152562], 'p_i': 40, 'u_i': 2.7003, 'theta': 0.9194},
        {'id': 7, 'e_m': 2.862730, 'e_o_k': [1.357525], 'p_i': 20, 'u_i': 3.7721, 'theta': 0.9569},
    ]
    B_BUDGET = 96.600000
    return processors, tasks, B_BUDGET
