"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299999, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1024, "set": 24, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.299999, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1024, "set": 24, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.55, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.55, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.328263, 'e_o_k': [0.101020, 0.243666, 0.160952], 'p_i': 10, 'u_i': 4.1906, 'theta': 0.6409},
        {'id': 1, 'e_m': 8.461123, 'e_o_k': [0.746954, 0.987403], 'p_i': 20, 'u_i': 3.0998, 'theta': 0.9687},
        {'id': 2, 'e_m': 9.764702, 'e_o_k': [2.901637, 3.401688, 2.588984, 2.892730, 2.723694], 'p_i': 40, 'u_i': 4.0799, 'theta': 0.6328},
    ]
    B_BUDGET = 48.299999
    return processors, tasks, B_BUDGET
