"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299996, "H": 40, "J": 15, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1074, "set": 74, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.299996, "H": 40, "J": 15, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1074, "set": 74, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.6, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.6, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.171979, 'e_o_k': [0.322221, 0.266782], 'p_i': 10, 'u_i': 3.9733, 'theta': 0.9455},
        {'id': 1, 'e_m': 2.387366, 'e_o_k': [0.677176, 0.532088, 0.762720], 'p_i': 20, 'u_i': 4.4277, 'theta': 0.7780},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [0.641968, 0.452164, 0.464439], 'p_i': 40, 'u_i': 2.3021, 'theta': 0.7856},
        {'id': 3, 'e_m': 1.157196, 'e_o_k': [0.560133, 0.679972, 0.408337], 'p_i': 10, 'u_i': 4.5827, 'theta': 0.7262},
        {'id': 4, 'e_m': 1.477141, 'e_o_k': [0.639481, 0.747439], 'p_i': 10, 'u_i': 2.0036, 'theta': 0.6541},
    ]
    B_BUDGET = 48.299996
    return processors, tasks, B_BUDGET
