"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.75, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.75, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.357008, 'e_o_k': [2.714016], 'p_i': 10, 'u_i': 3.5344, 'theta': 0.9567},
        {'id': 1, 'e_m': 4.075457, 'e_o_k': [0.288091, 0.211534, 0.250712, 0.276753], 'p_i': 20, 'u_i': 1.3657, 'theta': 0.9892},
        {'id': 2, 'e_m': 12.356597, 'e_o_k': [3.649350], 'p_i': 40, 'u_i': 3.3646, 'theta': 0.7774},
        {'id': 3, 'e_m': 1.378485, 'e_o_k': [0.038659, 0.063685, 0.052344, 0.055314], 'p_i': 40, 'u_i': 2.0826, 'theta': 0.9482},
        {'id': 4, 'e_m': 3.171493, 'e_o_k': [0.217150, 0.231336, 0.158076, 0.201039], 'p_i': 10, 'u_i': 3.4309, 'theta': 0.9600},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
