"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 35.419999, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1001, "set": 1, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 35.419999, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1001, "set": 1, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.45, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.45, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.982115, 'e_o_k': [0.088501, 0.067590, 0.093549, 0.082389], 'p_i': 10, 'u_i': 3.0079, 'theta': 0.9580},
        {'id': 1, 'e_m': 3.201900, 'e_o_k': [0.032145, 0.023960], 'p_i': 20, 'u_i': 3.5452, 'theta': 0.7627},
        {'id': 2, 'e_m': 3.803606, 'e_o_k': [1.093790, 1.017841], 'p_i': 40, 'u_i': 2.7382, 'theta': 0.9653},
        {'id': 3, 'e_m': 1.466034, 'e_o_k': [0.000885, 0.001014, 0.001043, 0.001212, 0.001521], 'p_i': 10, 'u_i': 3.4312, 'theta': 0.6023},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [0.047074, 0.046965, 0.036323, 0.051503, 0.030805], 'p_i': 20, 'u_i': 1.5512, 'theta': 0.7775},
    ]
    B_BUDGET = 35.419999
    return processors, tasks, B_BUDGET
