"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 90.159996, "H": 80, "J": 32, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.4, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 90.159996, "H": 80, "J": 32, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.4, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.613334, 'e_o_k': [0.192500, 0.123130], 'p_i': 10, 'u_i': 3.6851, 'theta': 0.6779},
        {'id': 1, 'e_m': 1.797667, 'e_o_k': [1.652065, 1.580658], 'p_i': 20, 'u_i': 1.3040, 'theta': 0.9485},
        {'id': 2, 'e_m': 4.510331, 'e_o_k': [0.629819, 0.558769, 0.554926, 0.548720], 'p_i': 40, 'u_i': 2.7216, 'theta': 0.9576},
        {'id': 3, 'e_m': 8.958860, 'e_o_k': [0.801929, 1.474846], 'p_i': 80, 'u_i': 3.8735, 'theta': 0.6356},
        {'id': 4, 'e_m': 0.136455, 'e_o_k': [0.116527, 0.156383], 'p_i': 20, 'u_i': 4.4850, 'theta': 0.9217},
        {'id': 5, 'e_m': 0.837071, 'e_o_k': [0.269384, 0.393986], 'p_i': 20, 'u_i': 3.1202, 'theta': 0.7184},
        {'id': 6, 'e_m': 1.367929, 'e_o_k': [0.070592, 0.056956, 0.076548, 0.056397], 'p_i': 10, 'u_i': 2.9303, 'theta': 0.6285},
        {'id': 7, 'e_m': 27.085600, 'e_o_k': [1.275919, 1.268383, 1.309456], 'p_i': 80, 'u_i': 2.3278, 'theta': 0.8173},
    ]
    B_BUDGET = 90.159996
    return processors, tasks, B_BUDGET
