"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600001, "H": 80, "J": 36, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 96.600001, "H": 80, "J": 36, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 1.0]},
        {'id': 1, 'frequencies': [0.55, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.070452, 'e_o_k': [0.140904], 'p_i': 10, 'u_i': 4.3172, 'theta': 0.7746},
        {'id': 1, 'e_m': 2.243228, 'e_o_k': [0.494139, 0.536351], 'p_i': 20, 'u_i': 2.0085, 'theta': 0.8952},
        {'id': 2, 'e_m': 5.472494, 'e_o_k': [0.761607, 0.699064, 0.748783], 'p_i': 40, 'u_i': 1.1725, 'theta': 0.8760},
        {'id': 3, 'e_m': 8.345968, 'e_o_k': [1.785253, 0.749793], 'p_i': 80, 'u_i': 1.0524, 'theta': 0.7329},
        {'id': 4, 'e_m': 31.747896, 'e_o_k': [12.378079], 'p_i': 80, 'u_i': 4.4871, 'theta': 0.8862},
        {'id': 5, 'e_m': 1.225020, 'e_o_k': [0.164501, 0.196324, 0.165571, 0.251911], 'p_i': 10, 'u_i': 4.7408, 'theta': 0.8630},
        {'id': 6, 'e_m': 1.154704, 'e_o_k': [0.737907, 0.367460], 'p_i': 10, 'u_i': 2.4424, 'theta': 0.7445},
        {'id': 7, 'e_m': 0.096707, 'e_o_k': [0.030660, 0.032428, 0.024258], 'p_i': 20, 'u_i': 2.5244, 'theta': 0.6476},
    ]
    B_BUDGET = 96.600001
    return processors, tasks, B_BUDGET
