"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 9, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1081, "set": 81, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 9, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1081, "set": 81, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.65, 1.0]},
        {'id': 1, 'frequencies': [0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.916122, 'e_o_k': [0.029709, 0.043888, 0.034728], 'p_i': 10, 'u_i': 1.5612, 'theta': 0.8131},
        {'id': 1, 'e_m': 4.228913, 'e_o_k': [1.214984, 1.409461, 1.741698], 'p_i': 20, 'u_i': 4.9673, 'theta': 0.7061},
        {'id': 2, 'e_m': 0.531496, 'e_o_k': [0.539667, 0.523325], 'p_i': 40, 'u_i': 4.8244, 'theta': 0.7105},
        {'id': 3, 'e_m': 7.568228, 'e_o_k': [2.492640, 4.297651, 2.675106], 'p_i': 40, 'u_i': 1.1007, 'theta': 0.8253},
        {'id': 4, 'e_m': 3.777963, 'e_o_k': [0.209840, 0.096184], 'p_i': 40, 'u_i': 2.3817, 'theta': 0.6587},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
