"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599997, "H": 40, "J": 10, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1066, "set": 66, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.599997, "H": 40, "J": 10, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1066, "set": 66, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.65, 0.7, 0.85, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.65, 0.7, 0.85, 0.95, 1.0]},
        {'id': 2, 'frequencies': [0.65, 0.7, 0.85, 0.95, 1.0]},
        {'id': 3, 'frequencies': [0.65, 0.7, 0.85, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.378087, 'e_o_k': [0.411480, 0.381336], 'p_i': 10, 'u_i': 3.8709, 'theta': 0.8887},
        {'id': 1, 'e_m': 5.086640, 'e_o_k': [2.577636], 'p_i': 20, 'u_i': 1.0058, 'theta': 0.6154},
        {'id': 2, 'e_m': 10.021423, 'e_o_k': [5.251688, 5.501247], 'p_i': 40, 'u_i': 2.9769, 'theta': 0.9702},
        {'id': 3, 'e_m': 12.220451, 'e_o_k': [3.944515, 4.543287], 'p_i': 40, 'u_i': 2.5435, 'theta': 0.9867},
        {'id': 4, 'e_m': 20.000000, 'e_o_k': [3.273325], 'p_i': 40, 'u_i': 1.4780, 'theta': 0.8696},
        {'id': 5, 'e_m': 10.072499, 'e_o_k': [1.365114, 1.438195, 2.125274, 2.356754, 1.874060], 'p_i': 40, 'u_i': 2.7537, 'theta': 0.7309},
    ]
    B_BUDGET = 96.599997
    return processors, tasks, B_BUDGET
