"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599999, "H": 80, "J": 30, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 96.599999, "H": 80, "J": 30, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.5, 0.65, 0.8, 0.9, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.5, 0.65, 0.8, 0.9, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.852551, 'e_o_k': [1.186744], 'p_i': 10, 'u_i': 3.9870, 'theta': 0.8842},
        {'id': 1, 'e_m': 2.683676, 'e_o_k': [0.068911, 0.099017, 0.071372, 0.069498], 'p_i': 20, 'u_i': 2.4102, 'theta': 0.6740},
        {'id': 2, 'e_m': 5.777656, 'e_o_k': [5.250573], 'p_i': 40, 'u_i': 1.1953, 'theta': 0.8957},
        {'id': 3, 'e_m': 5.317509, 'e_o_k': [1.613651], 'p_i': 80, 'u_i': 2.0587, 'theta': 0.7812},
        {'id': 4, 'e_m': 14.277524, 'e_o_k': [8.763541], 'p_i': 80, 'u_i': 4.3203, 'theta': 0.6004},
        {'id': 5, 'e_m': 1.751504, 'e_o_k': [0.359988, 0.205901, 0.372827], 'p_i': 10, 'u_i': 4.9929, 'theta': 0.6277},
        {'id': 6, 'e_m': 0.102730, 'e_o_k': [0.100351, 0.105109], 'p_i': 20, 'u_i': 4.6704, 'theta': 0.7780},
        {'id': 7, 'e_m': 4.435795, 'e_o_k': [0.009161, 0.008537, 0.012777], 'p_i': 40, 'u_i': 4.5030, 'theta': 0.8760},
    ]
    B_BUDGET = 96.599999
    return processors, tasks, B_BUDGET
