"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.233785, 'e_o_k': [0.208433, 0.250029, 0.248416], 'p_i': 10, 'u_i': 3.6642, 'theta': 0.7013},
        {'id': 1, 'e_m': 5.763484, 'e_o_k': [2.463775, 2.523446], 'p_i': 20, 'u_i': 1.2929, 'theta': 0.7230},
        {'id': 2, 'e_m': 1.668640, 'e_o_k': [1.572532], 'p_i': 40, 'u_i': 3.4498, 'theta': 0.6043},
        {'id': 3, 'e_m': 8.350065, 'e_o_k': [0.623532, 0.575506, 0.444593], 'p_i': 20, 'u_i': 4.9535, 'theta': 0.7269},
        {'id': 4, 'e_m': 0.292281, 'e_o_k': [0.305053, 0.279510], 'p_i': 10, 'u_i': 3.5602, 'theta': 0.8401},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
