"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.039995, "H": 80, "J": 24, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1053, "set": 53, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.039995, "H": 80, "J": 24, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1053, "set": 53, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.8, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.8, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.533943, 'e_o_k': [0.006405, 0.008284, 0.007065], 'p_i': 10, 'u_i': 3.0328, 'theta': 0.8780},
        {'id': 1, 'e_m': 2.511519, 'e_o_k': [0.157786, 0.157812], 'p_i': 20, 'u_i': 3.3495, 'theta': 0.8235},
        {'id': 2, 'e_m': 2.108460, 'e_o_k': [1.911226, 2.305694], 'p_i': 40, 'u_i': 4.4861, 'theta': 0.6976},
        {'id': 3, 'e_m': 40.000000, 'e_o_k': [0.632225, 0.552968, 0.753575], 'p_i': 80, 'u_i': 2.0193, 'theta': 0.7516},
        {'id': 4, 'e_m': 3.355817, 'e_o_k': [1.145474], 'p_i': 20, 'u_i': 2.4573, 'theta': 0.7663},
        {'id': 5, 'e_m': 7.803630, 'e_o_k': [3.319696], 'p_i': 40, 'u_i': 4.6189, 'theta': 0.6279},
        {'id': 6, 'e_m': 4.082201, 'e_o_k': [0.495899, 0.435809, 0.626347], 'p_i': 80, 'u_i': 3.7091, 'theta': 0.7530},
        {'id': 7, 'e_m': 2.176363, 'e_o_k': [3.705812], 'p_i': 40, 'u_i': 4.0383, 'theta': 0.8712},
    ]
    B_BUDGET = 103.039995
    return processors, tasks, B_BUDGET
