"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 124.200005, "H": 80, "J": 25, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.9, "seed": 1010, "set": 10, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 124.200005, "H": 80, "J": 25, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.9, "seed": 1010, "set": 10, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.116076, 'e_o_k': [0.135650, 0.050839, 0.192934], 'p_i': 10, 'u_i': 1.6916, 'theta': 0.9935},
        {'id': 1, 'e_m': 0.912404, 'e_o_k': [1.824809], 'p_i': 20, 'u_i': 1.7632, 'theta': 0.7733},
        {'id': 2, 'e_m': 9.173258, 'e_o_k': [1.843175], 'p_i': 40, 'u_i': 3.8070, 'theta': 0.6252},
        {'id': 3, 'e_m': 2.177855, 'e_o_k': [1.459901], 'p_i': 80, 'u_i': 3.4172, 'theta': 0.8276},
        {'id': 4, 'e_m': 9.431057, 'e_o_k': [6.139379], 'p_i': 80, 'u_i': 4.5319, 'theta': 0.6912},
        {'id': 5, 'e_m': 10.830952, 'e_o_k': [4.329657, 3.320476, 3.596322], 'p_i': 80, 'u_i': 3.1165, 'theta': 0.6816},
        {'id': 6, 'e_m': 0.022089, 'e_o_k': [0.018076, 0.026101], 'p_i': 20, 'u_i': 3.7180, 'theta': 0.7904},
        {'id': 7, 'e_m': 6.636760, 'e_o_k': [0.528013, 0.485321, 0.362693, 0.363121], 'p_i': 20, 'u_i': 4.4022, 'theta': 0.9490},
    ]
    B_BUDGET = 124.200005
    return processors, tasks, B_BUDGET
