"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 35.420002, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1022, "set": 22, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 35.420002, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1022, "set": 22, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.55, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.55, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.196801, 'e_o_k': [0.738598, 0.856865, 0.681127, 0.569105], 'p_i': 10, 'u_i': 4.5356, 'theta': 0.6614},
        {'id': 1, 'e_m': 0.373660, 'e_o_k': [0.623216, 0.660403, 0.725775, 0.516382, 0.525564], 'p_i': 20, 'u_i': 2.3987, 'theta': 0.8131},
        {'id': 2, 'e_m': 0.475411, 'e_o_k': [0.248176, 0.385807, 0.375506, 0.351024, 0.285367], 'p_i': 40, 'u_i': 4.3586, 'theta': 0.8052},
        {'id': 3, 'e_m': 4.567966, 'e_o_k': [4.241362, 4.517779], 'p_i': 40, 'u_i': 3.9986, 'theta': 0.8953},
        {'id': 4, 'e_m': 1.422100, 'e_o_k': [2.287552, 2.800715, 3.021253], 'p_i': 40, 'u_i': 4.0339, 'theta': 0.6847},
    ]
    B_BUDGET = 35.420002
    return processors, tasks, B_BUDGET
