"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1017, "set": 17, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1017, "set": 17, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.647308, 'e_o_k': [0.423757, 0.529522, 0.393159], 'p_i': 10, 'u_i': 4.6504, 'theta': 0.7952},
        {'id': 1, 'e_m': 1.614656, 'e_o_k': [1.594942], 'p_i': 20, 'u_i': 3.5497, 'theta': 0.7010},
        {'id': 2, 'e_m': 3.127774, 'e_o_k': [0.784730], 'p_i': 40, 'u_i': 1.6248, 'theta': 0.6811},
        {'id': 3, 'e_m': 10.000000, 'e_o_k': [2.266135], 'p_i': 20, 'u_i': 3.2811, 'theta': 0.6585},
        {'id': 4, 'e_m': 0.763421, 'e_o_k': [0.711954, 0.814887], 'p_i': 10, 'u_i': 3.8492, 'theta': 0.7951},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
