"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 109.480004, "H": 80, "J": 29, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1017, "set": 17, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 109.480004, "H": 80, "J": 29, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1017, "set": 17, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.152367, 'e_o_k': [0.047203, 0.052353, 0.051292, 0.044770], 'p_i': 10, 'u_i': 2.7614, 'theta': 0.7119},
        {'id': 1, 'e_m': 2.309933, 'e_o_k': [0.240442, 0.248436], 'p_i': 20, 'u_i': 2.1631, 'theta': 0.6261},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [0.600227, 0.636273, 0.576835, 0.596926], 'p_i': 40, 'u_i': 1.7973, 'theta': 0.8162},
        {'id': 3, 'e_m': 11.401996, 'e_o_k': [0.270294, 0.331735, 0.276185, 0.301927], 'p_i': 80, 'u_i': 1.4646, 'theta': 0.7895},
        {'id': 4, 'e_m': 4.576599, 'e_o_k': [0.489136, 0.516560, 0.266879, 0.358010], 'p_i': 40, 'u_i': 3.8388, 'theta': 0.8945},
        {'id': 5, 'e_m': 1.207666, 'e_o_k': [0.430060, 0.278390, 0.311060], 'p_i': 10, 'u_i': 2.3341, 'theta': 0.7676},
        {'id': 6, 'e_m': 4.568326, 'e_o_k': [0.007063, 0.006585, 0.011375], 'p_i': 40, 'u_i': 4.4701, 'theta': 0.8367},
        {'id': 7, 'e_m': 7.094081, 'e_o_k': [0.463521, 0.496836, 0.272771, 0.272665], 'p_i': 40, 'u_i': 2.4522, 'theta': 0.8233},
    ]
    B_BUDGET = 109.480004
    return processors, tasks, B_BUDGET
