"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 70.839996, "H": 80, "J": 24, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1053, "set": 53, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 70.839996, "H": 80, "J": 24, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1053, "set": 53, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.8, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.8, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.309948, 'e_o_k': [0.001601, 0.002071, 0.001766], 'p_i': 10, 'u_i': 3.0328, 'theta': 0.8780},
        {'id': 1, 'e_m': 2.092933, 'e_o_k': [0.039447, 0.039453], 'p_i': 20, 'u_i': 3.3495, 'theta': 0.8235},
        {'id': 2, 'e_m': 1.090383, 'e_o_k': [0.519223, 0.626389], 'p_i': 40, 'u_i': 4.4861, 'theta': 0.6976},
        {'id': 3, 'e_m': 40.000000, 'e_o_k': [0.098458, 0.086115, 0.117356], 'p_i': 80, 'u_i': 2.0193, 'theta': 0.7516},
        {'id': 4, 'e_m': 2.796514, 'e_o_k': [0.286368], 'p_i': 20, 'u_i': 2.4573, 'theta': 0.7663},
        {'id': 5, 'e_m': 6.503025, 'e_o_k': [0.829924], 'p_i': 40, 'u_i': 4.6189, 'theta': 0.6279},
        {'id': 6, 'e_m': 1.401834, 'e_o_k': [0.123975, 0.108952, 0.156587], 'p_i': 80, 'u_i': 3.7091, 'theta': 0.7530},
        {'id': 7, 'e_m': 0.686988, 'e_o_k': [0.926453], 'p_i': 40, 'u_i': 4.0383, 'theta': 0.8712},
    ]
    B_BUDGET = 70.839996
    return processors, tasks, B_BUDGET
