"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 61.179998, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1071, "set": 71, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 61.179998, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1071, "set": 71, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.65, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.65, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.976497, 'e_o_k': [0.032952, 0.032864, 0.029186], 'p_i': 10, 'u_i': 3.4010, 'theta': 0.8059},
        {'id': 1, 'e_m': 8.117899, 'e_o_k': [0.062021, 0.043021, 0.053280], 'p_i': 20, 'u_i': 1.3745, 'theta': 0.6851},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [0.440817], 'p_i': 40, 'u_i': 1.1223, 'theta': 0.9087},
        {'id': 3, 'e_m': 7.858215, 'e_o_k': [1.017147, 1.114433], 'p_i': 40, 'u_i': 2.2739, 'theta': 0.7465},
        {'id': 4, 'e_m': 20.000000, 'e_o_k': [0.222517, 0.293395, 0.215036], 'p_i': 40, 'u_i': 3.9940, 'theta': 0.8975},
    ]
    B_BUDGET = 61.179998
    return processors, tasks, B_BUDGET
