"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600005, "H": 80, "J": 32, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1044, "set": 44, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 96.600005, "H": 80, "J": 32, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1044, "set": 44, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.55, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.55, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.007365, 'e_o_k': [0.008915, 0.005816], 'p_i': 10, 'u_i': 1.9850, 'theta': 0.7018},
        {'id': 1, 'e_m': 1.888507, 'e_o_k': [1.090218], 'p_i': 20, 'u_i': 2.4741, 'theta': 0.7422},
        {'id': 2, 'e_m': 4.772231, 'e_o_k': [0.910299, 0.754626, 0.756183, 0.598824], 'p_i': 40, 'u_i': 1.9636, 'theta': 0.8671},
        {'id': 3, 'e_m': 38.009415, 'e_o_k': [5.000489, 4.747674, 5.225799], 'p_i': 80, 'u_i': 1.6306, 'theta': 0.9561},
        {'id': 4, 'e_m': 0.926241, 'e_o_k': [1.852482], 'p_i': 80, 'u_i': 1.9693, 'theta': 0.7427},
        {'id': 5, 'e_m': 1.273680, 'e_o_k': [0.146450, 0.134075, 0.182042, 0.068633], 'p_i': 10, 'u_i': 3.7209, 'theta': 0.7633},
        {'id': 6, 'e_m': 3.253407, 'e_o_k': [1.755674], 'p_i': 20, 'u_i': 2.4089, 'theta': 0.9616},
        {'id': 7, 'e_m': 0.175965, 'e_o_k': [0.112348, 0.117068, 0.116256], 'p_i': 20, 'u_i': 4.8966, 'theta': 0.9363},
    ]
    B_BUDGET = 96.600005
    return processors, tasks, B_BUDGET
