"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 61.180002, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1005, "set": 5, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.9, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 61.180002, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1005, "set": 5, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.9, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.6, 0.65, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.6, 0.65, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.980755, 'e_o_k': [0.469145], 'p_i': 10, 'u_i': 2.9627, 'theta': 0.7060},
        {'id': 1, 'e_m': 3.834011, 'e_o_k': [1.165601], 'p_i': 20, 'u_i': 2.1803, 'theta': 0.6491},
        {'id': 2, 'e_m': 6.911029, 'e_o_k': [1.447128, 1.746447, 1.888817, 0.865032], 'p_i': 40, 'u_i': 4.7861, 'theta': 0.9591},
        {'id': 3, 'e_m': 7.267547, 'e_o_k': [1.476125, 1.216575, 1.018432, 0.934014, 1.314417], 'p_i': 20, 'u_i': 2.8940, 'theta': 0.7777},
        {'id': 4, 'e_m': 6.962835, 'e_o_k': [2.491874, 2.991036, 2.036299, 3.728876, 2.677585], 'p_i': 40, 'u_i': 1.0735, 'theta': 0.8440},
    ]
    B_BUDGET = 61.180002
    return processors, tasks, B_BUDGET
