"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 45.079999, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1013, "set": 13, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 45.079999, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1013, "set": 13, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.5, 0.65, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.5, 0.65, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.699660, 'e_o_k': [0.231247, 0.203731, 0.270522], 'p_i': 10, 'u_i': 4.7825, 'theta': 0.8944},
        {'id': 1, 'e_m': 0.861025, 'e_o_k': [1.423551], 'p_i': 20, 'u_i': 1.4896, 'theta': 0.6592},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [13.488093], 'p_i': 40, 'u_i': 2.9263, 'theta': 0.8863},
        {'id': 3, 'e_m': 0.904487, 'e_o_k': [1.808566], 'p_i': 20, 'u_i': 4.4413, 'theta': 0.8550},
        {'id': 4, 'e_m': 0.417584, 'e_o_k': [0.127125, 0.179293], 'p_i': 10, 'u_i': 4.5038, 'theta': 0.7131},
    ]
    B_BUDGET = 45.079999
    return processors, tasks, B_BUDGET
