"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599999, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1067, "set": 67, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.599999, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1067, "set": 67, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.5, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.5, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.084090, 'e_o_k': [0.621146, 0.578698, 0.858334], 'p_i': 10, 'u_i': 2.5309, 'theta': 0.6741},
        {'id': 1, 'e_m': 4.595856, 'e_o_k': [0.271532], 'p_i': 20, 'u_i': 4.9574, 'theta': 0.6823},
        {'id': 2, 'e_m': 3.406652, 'e_o_k': [1.958187, 1.296626, 1.189198, 1.814289], 'p_i': 40, 'u_i': 1.4717, 'theta': 0.6669},
        {'id': 3, 'e_m': 38.130552, 'e_o_k': [2.695208, 2.843596, 1.906687, 2.486356], 'p_i': 80, 'u_i': 1.7048, 'theta': 0.9556},
    ]
    B_BUDGET = 96.599999
    return processors, tasks, B_BUDGET
