"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 90.160004, "H": 80, "J": 23, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 90.160004, "H": 80, "J": 23, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.5, 0.55, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.5, 0.55, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.099624, 'e_o_k': [1.811171], 'p_i': 10, 'u_i': 1.6615, 'theta': 0.8866},
        {'id': 1, 'e_m': 0.778327, 'e_o_k': [0.268779], 'p_i': 20, 'u_i': 2.0532, 'theta': 0.7783},
        {'id': 2, 'e_m': 0.873132, 'e_o_k': [0.738328, 0.341114, 0.666823], 'p_i': 40, 'u_i': 1.3641, 'theta': 0.7644},
        {'id': 3, 'e_m': 3.016257, 'e_o_k': [0.021067, 0.016526, 0.018555], 'p_i': 80, 'u_i': 4.0550, 'theta': 0.8661},
        {'id': 4, 'e_m': 1.067519, 'e_o_k': [0.551147, 0.515424, 0.532168, 0.536299], 'p_i': 80, 'u_i': 1.6058, 'theta': 0.6759},
        {'id': 5, 'e_m': 0.067241, 'e_o_k': [0.041673, 0.045600, 0.047209], 'p_i': 80, 'u_i': 4.7402, 'theta': 0.6922},
        {'id': 6, 'e_m': 12.399787, 'e_o_k': [3.327268, 4.156366, 4.353330], 'p_i': 40, 'u_i': 4.6213, 'theta': 0.8998},
        {'id': 7, 'e_m': 3.348212, 'e_o_k': [0.172661, 0.220559, 0.129895, 0.212733], 'p_i': 20, 'u_i': 1.4092, 'theta': 0.9913},
    ]
    B_BUDGET = 90.160004
    return processors, tasks, B_BUDGET
