"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1052, "set": 52, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1052, "set": 52, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.55, 0.65, 0.7, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.55, 0.65, 0.7, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.656396, 'e_o_k': [0.656530, 0.660502], 'p_i': 10, 'u_i': 4.6211, 'theta': 0.9193},
        {'id': 1, 'e_m': 3.726457, 'e_o_k': [0.629387], 'p_i': 20, 'u_i': 4.3826, 'theta': 0.6000},
        {'id': 2, 'e_m': 5.594470, 'e_o_k': [1.893376, 1.885196], 'p_i': 40, 'u_i': 2.5011, 'theta': 0.6751},
        {'id': 3, 'e_m': 1.159757, 'e_o_k': [2.319514], 'p_i': 20, 'u_i': 3.5907, 'theta': 0.6748},
        {'id': 4, 'e_m': 4.501880, 'e_o_k': [0.433467, 0.330210, 0.500197], 'p_i': 10, 'u_i': 4.2171, 'theta': 0.7756},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
