"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.200006, "H": 40, "J": 28, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1042, "set": 42, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 193.200006, "H": 40, "J": 28, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1042, "set": 42, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.45, 0.55, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.45, 0.55, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.4, 0.45, 0.55, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.4, 0.45, 0.55, 1.0]},
        {'id': 4, 'frequencies': [0.3, 0.4, 0.45, 0.55, 1.0]},
        {'id': 5, 'frequencies': [0.3, 0.4, 0.45, 0.55, 1.0]},
        {'id': 6, 'frequencies': [0.3, 0.4, 0.45, 0.55, 1.0]},
        {'id': 7, 'frequencies': [0.3, 0.4, 0.45, 0.55, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [2.679573], 'p_i': 10, 'u_i': 4.6515, 'theta': 0.8059},
        {'id': 1, 'e_m': 5.325516, 'e_o_k': [2.648157], 'p_i': 20, 'u_i': 1.4982, 'theta': 0.9250},
        {'id': 2, 'e_m': 10.619449, 'e_o_k': [12.466103], 'p_i': 40, 'u_i': 3.0158, 'theta': 0.9271},
        {'id': 3, 'e_m': 10.000000, 'e_o_k': [1.309547, 1.138490, 0.972029], 'p_i': 20, 'u_i': 4.6843, 'theta': 0.6774},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [1.476726], 'p_i': 20, 'u_i': 4.7488, 'theta': 0.6182},
        {'id': 5, 'e_m': 5.299438, 'e_o_k': [3.059331], 'p_i': 20, 'u_i': 1.8998, 'theta': 0.6423},
        {'id': 6, 'e_m': 2.651100, 'e_o_k': [2.004937, 1.326042], 'p_i': 10, 'u_i': 3.9627, 'theta': 0.9290},
        {'id': 7, 'e_m': 5.294261, 'e_o_k': [0.161520, 0.123965, 0.117577], 'p_i': 20, 'u_i': 3.2721, 'theta': 0.8518},
        {'id': 8, 'e_m': 5.350765, 'e_o_k': [3.273297], 'p_i': 20, 'u_i': 4.7767, 'theta': 0.9322},
        {'id': 9, 'e_m': 2.679529, 'e_o_k': [0.420623, 0.501537], 'p_i': 10, 'u_i': 1.8009, 'theta': 0.6697},
        {'id': 10, 'e_m': 7.445298, 'e_o_k': [0.573309, 0.537333], 'p_i': 20, 'u_i': 2.7356, 'theta': 0.9075},
        {'id': 11, 'e_m': 10.627482, 'e_o_k': [3.124416, 1.730127, 4.165948], 'p_i': 40, 'u_i': 2.6826, 'theta': 0.6219},
    ]
    B_BUDGET = 193.200006
    return processors, tasks, B_BUDGET
