"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.039987, "H": 80, "J": 36, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1039, "set": 39, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.039987, "H": 80, "J": 36, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1039, "set": 39, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.45, 0.8, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.45, 0.8, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.753757, 'e_o_k': [0.417388, 0.402516, 0.369562, 0.346233], 'p_i': 10, 'u_i': 2.2192, 'theta': 0.6829},
        {'id': 1, 'e_m': 4.737868, 'e_o_k': [1.549764], 'p_i': 20, 'u_i': 3.5623, 'theta': 0.8044},
        {'id': 2, 'e_m': 8.785122, 'e_o_k': [1.754124], 'p_i': 40, 'u_i': 1.9937, 'theta': 0.7165},
        {'id': 3, 'e_m': 15.866700, 'e_o_k': [0.228381, 0.197365, 0.130585], 'p_i': 80, 'u_i': 1.0161, 'theta': 0.6002},
        {'id': 4, 'e_m': 0.752794, 'e_o_k': [0.286412], 'p_i': 10, 'u_i': 2.2940, 'theta': 0.7460},
        {'id': 5, 'e_m': 3.261797, 'e_o_k': [0.164542, 0.211393, 0.157936], 'p_i': 20, 'u_i': 3.5624, 'theta': 0.8639},
        {'id': 6, 'e_m': 1.211119, 'e_o_k': [0.520220, 0.563269, 0.573161, 0.765588], 'p_i': 80, 'u_i': 3.4028, 'theta': 0.8064},
        {'id': 7, 'e_m': 0.162609, 'e_o_k': [0.093726, 0.109612, 0.121879], 'p_i': 10, 'u_i': 2.7963, 'theta': 0.9278},
    ]
    B_BUDGET = 103.039987
    return processors, tasks, B_BUDGET
