"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1095, "set": 95, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1095, "set": 95, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.75, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.75, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.439871, 'e_o_k': [0.434416, 0.487425, 0.441231, 0.479092], 'p_i': 10, 'u_i': 3.9666, 'theta': 0.8876},
        {'id': 1, 'e_m': 7.353790, 'e_o_k': [1.998399, 0.532813], 'p_i': 20, 'u_i': 1.9116, 'theta': 0.9967},
        {'id': 2, 'e_m': 15.532938, 'e_o_k': [2.517147, 1.130647, 2.237922, 1.683204], 'p_i': 40, 'u_i': 4.3118, 'theta': 0.8818},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
