"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599998, "H": 80, "J": 22, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 96.599998, "H": 80, "J": 22, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.5, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.5, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.345090, 'e_o_k': [0.114883, 0.144905, 0.131614, 0.148699], 'p_i': 10, 'u_i': 2.9364, 'theta': 0.8450},
        {'id': 1, 'e_m': 3.582153, 'e_o_k': [0.635293], 'p_i': 20, 'u_i': 1.1647, 'theta': 0.7557},
        {'id': 2, 'e_m': 0.963123, 'e_o_k': [0.665301, 1.260946], 'p_i': 40, 'u_i': 2.7378, 'theta': 0.7061},
        {'id': 3, 'e_m': 26.187379, 'e_o_k': [3.903981, 3.705353, 3.772792], 'p_i': 80, 'u_i': 4.9053, 'theta': 0.9955},
        {'id': 4, 'e_m': 4.928267, 'e_o_k': [3.936544, 4.263320], 'p_i': 80, 'u_i': 4.9995, 'theta': 0.9882},
        {'id': 5, 'e_m': 15.934103, 'e_o_k': [1.033984, 1.116102, 0.732993], 'p_i': 80, 'u_i': 4.8201, 'theta': 0.8438},
        {'id': 6, 'e_m': 2.309805, 'e_o_k': [4.619610], 'p_i': 80, 'u_i': 3.7358, 'theta': 0.7489},
        {'id': 7, 'e_m': 0.906216, 'e_o_k': [0.550212], 'p_i': 20, 'u_i': 2.7993, 'theta': 0.7859},
    ]
    B_BUDGET = 96.599998
    return processors, tasks, B_BUDGET
