"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600002, "H": 80, "J": 31, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1031, "set": 31, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 96.600002, "H": 80, "J": 31, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1031, "set": 31, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.7, 0.75, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.7, 0.75, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.837248, 'e_o_k': [0.424900, 0.294075, 0.411197, 0.454108], 'p_i': 10, 'u_i': 2.4295, 'theta': 0.9733},
        {'id': 1, 'e_m': 0.057815, 'e_o_k': [0.020773, 0.035651, 0.059207], 'p_i': 20, 'u_i': 1.9991, 'theta': 0.7119},
        {'id': 2, 'e_m': 12.397399, 'e_o_k': [0.682988, 0.588435, 0.479563], 'p_i': 40, 'u_i': 3.6507, 'theta': 0.7148},
        {'id': 3, 'e_m': 0.664699, 'e_o_k': [0.092858, 0.105259], 'p_i': 80, 'u_i': 3.3385, 'theta': 0.8876},
        {'id': 4, 'e_m': 6.810773, 'e_o_k': [0.160413, 0.268804, 0.346744, 0.113641], 'p_i': 40, 'u_i': 1.6477, 'theta': 0.6610},
        {'id': 5, 'e_m': 0.055717, 'e_o_k': [0.043043, 0.035384, 0.033008], 'p_i': 10, 'u_i': 3.8026, 'theta': 0.6892},
        {'id': 6, 'e_m': 7.256455, 'e_o_k': [3.731225, 3.223743], 'p_i': 40, 'u_i': 1.5864, 'theta': 0.7713},
        {'id': 7, 'e_m': 2.290043, 'e_o_k': [1.951607], 'p_i': 40, 'u_i': 2.0589, 'theta': 0.9038},
        {'id': 8, 'e_m': 4.362163, 'e_o_k': [0.950863, 0.821304, 0.616758], 'p_i': 80, 'u_i': 1.1190, 'theta': 0.7260},
        {'id': 9, 'e_m': 10.088817, 'e_o_k': [0.107533, 0.182859], 'p_i': 80, 'u_i': 4.0383, 'theta': 0.8958},
    ]
    B_BUDGET = 96.600002
    return processors, tasks, B_BUDGET
