"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599999, "H": 80, "J": 17, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1030, "set": 30, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}
"""

_SPEC = '{"B": 96.599999, "H": 80, "J": 17, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1030, "set": 30, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.6, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.6, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.549686, 'e_o_k': [0.301984, 0.379562, 0.417826], 'p_i': 10, 'u_i': 4.6003, 'theta': 0.9132},
        {'id': 1, 'e_m': 3.430899, 'e_o_k': [4.531585], 'p_i': 20, 'u_i': 4.0918, 'theta': 0.6581},
        {'id': 2, 'e_m': 14.775132, 'e_o_k': [0.740050, 0.816928, 0.670714], 'p_i': 40, 'u_i': 3.7257, 'theta': 0.6169},
        {'id': 3, 'e_m': 18.296927, 'e_o_k': [2.130131, 1.764543], 'p_i': 80, 'u_i': 4.8069, 'theta': 0.7478},
        {'id': 4, 'e_m': 1.477417, 'e_o_k': [0.209405, 0.297347, 0.350544, 0.293947], 'p_i': 80, 'u_i': 3.6230, 'theta': 0.7952},
        {'id': 5, 'e_m': 12.554306, 'e_o_k': [1.305863, 1.036583, 1.234938], 'p_i': 80, 'u_i': 1.5854, 'theta': 0.9036},
    ]
    B_BUDGET = 96.599999
    return processors, tasks, B_BUDGET
