"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.6, "H": 40, "J": 11, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1092, "set": 92, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.6, "H": 40, "J": 11, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1092, "set": 92, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.172060, 'e_o_k': [0.959215, 1.377569], 'p_i': 10, 'u_i': 2.5093, 'theta': 0.6711},
        {'id': 1, 'e_m': 4.351480, 'e_o_k': [1.727902, 1.282266], 'p_i': 20, 'u_i': 4.8005, 'theta': 0.7075},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [6.824061, 4.511272], 'p_i': 40, 'u_i': 3.2159, 'theta': 0.9186},
        {'id': 3, 'e_m': 4.292419, 'e_o_k': [2.519402, 2.790380], 'p_i': 20, 'u_i': 2.3298, 'theta': 0.9101},
        {'id': 4, 'e_m': 8.541871, 'e_o_k': [1.042380, 0.424148, 0.791380], 'p_i': 40, 'u_i': 4.4838, 'theta': 0.9240},
        {'id': 5, 'e_m': 17.482093, 'e_o_k': [0.141305, 0.105090, 0.173326], 'p_i': 40, 'u_i': 4.9024, 'theta': 0.6992},
    ]
    B_BUDGET = 96.600000
    return processors, tasks, B_BUDGET
