"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 83.719995, "H": 80, "J": 36, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1061, "set": 61, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 83.719995, "H": 80, "J": 36, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1061, "set": 61, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.55, 0.6, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.55, 0.6, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.110399, 'e_o_k': [0.042355, 0.076703, 0.101740], 'p_i': 10, 'u_i': 4.3192, 'theta': 0.6232},
        {'id': 1, 'e_m': 1.911305, 'e_o_k': [0.464995, 0.634700, 0.554214, 0.387013], 'p_i': 20, 'u_i': 4.1944, 'theta': 0.9801},
        {'id': 2, 'e_m': 3.167611, 'e_o_k': [0.493295, 0.389764, 0.432182, 0.402372], 'p_i': 40, 'u_i': 3.5189, 'theta': 0.6621},
        {'id': 3, 'e_m': 8.436698, 'e_o_k': [2.403828, 3.172463, 1.531986], 'p_i': 80, 'u_i': 1.4258, 'theta': 0.6442},
        {'id': 4, 'e_m': 0.046074, 'e_o_k': [0.092149], 'p_i': 10, 'u_i': 3.2765, 'theta': 0.6814},
        {'id': 5, 'e_m': 1.447786, 'e_o_k': [1.690145], 'p_i': 10, 'u_i': 4.0995, 'theta': 0.6504},
        {'id': 6, 'e_m': 3.151899, 'e_o_k': [1.740714, 1.531660, 1.530822], 'p_i': 80, 'u_i': 1.7010, 'theta': 0.6256},
        {'id': 7, 'e_m': 2.399221, 'e_o_k': [1.565099, 1.042239, 1.508881], 'p_i': 20, 'u_i': 4.4369, 'theta': 0.9943},
    ]
    B_BUDGET = 83.719995
    return processors, tasks, B_BUDGET
