"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 9, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1010, "set": 10, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 9, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1010, "set": 10, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.043244, 'e_o_k': [1.043816], 'p_i': 10, 'u_i': 2.1418, 'theta': 0.8828},
        {'id': 1, 'e_m': 5.215797, 'e_o_k': [1.232677], 'p_i': 20, 'u_i': 1.5757, 'theta': 0.9980},
        {'id': 2, 'e_m': 12.225773, 'e_o_k': [1.960649], 'p_i': 40, 'u_i': 4.9958, 'theta': 0.8937},
        {'id': 3, 'e_m': 4.024369, 'e_o_k': [5.487277], 'p_i': 40, 'u_i': 4.9449, 'theta': 0.6428},
        {'id': 4, 'e_m': 9.145290, 'e_o_k': [5.911457], 'p_i': 40, 'u_i': 3.8070, 'theta': 0.6252},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
