"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299999, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1060, "set": 60, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.299999, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1060, "set": 60, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [1.132666], 'p_i': 10, 'u_i': 1.0700, 'theta': 0.9997},
        {'id': 1, 'e_m': 6.867675, 'e_o_k': [1.225670, 0.767085], 'p_i': 20, 'u_i': 4.2993, 'theta': 0.6905},
        {'id': 2, 'e_m': 6.264650, 'e_o_k': [11.483825], 'p_i': 40, 'u_i': 4.4078, 'theta': 0.9790},
    ]
    B_BUDGET = 48.299999
    return processors, tasks, B_BUDGET
