"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 386.399991, "H": 80, "J": 69, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1089, "set": 89, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 386.399991, "H": 80, "J": 69, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1089, "set": 89, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
        {'id': 4, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
        {'id': 5, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
        {'id': 6, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
        {'id': 7, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.519106, 'e_o_k': [0.672657], 'p_i': 10, 'u_i': 4.1263, 'theta': 0.9514},
        {'id': 1, 'e_m': 4.995986, 'e_o_k': [5.011520, 4.980452], 'p_i': 20, 'u_i': 3.8735, 'theta': 0.6595},
        {'id': 2, 'e_m': 10.081781, 'e_o_k': [7.966119], 'p_i': 40, 'u_i': 2.8596, 'theta': 0.7998},
        {'id': 3, 'e_m': 20.069413, 'e_o_k': [22.672640], 'p_i': 80, 'u_i': 4.9504, 'theta': 0.6638},
        {'id': 4, 'e_m': 10.891786, 'e_o_k': [6.099289, 5.651769], 'p_i': 40, 'u_i': 4.0367, 'theta': 0.9925},
        {'id': 5, 'e_m': 10.000000, 'e_o_k': [0.760125, 0.832695, 0.671963, 0.680317], 'p_i': 20, 'u_i': 4.8843, 'theta': 0.8709},
        {'id': 6, 'e_m': 2.527499, 'e_o_k': [0.207276, 0.188406, 0.171240, 0.173523], 'p_i': 10, 'u_i': 1.7770, 'theta': 0.8642},
        {'id': 7, 'e_m': 2.481344, 'e_o_k': [0.125476, 0.163398, 0.142779, 0.122587], 'p_i': 10, 'u_i': 2.1531, 'theta': 0.6840},
        {'id': 8, 'e_m': 5.000000, 'e_o_k': [2.229257], 'p_i': 10, 'u_i': 3.8453, 'theta': 0.7276},
        {'id': 9, 'e_m': 4.729200, 'e_o_k': [0.217950, 0.221789, 0.216766], 'p_i': 10, 'u_i': 1.3342, 'theta': 0.7422},
        {'id': 10, 'e_m': 5.000000, 'e_o_k': [0.121515, 0.196986, 0.220301, 0.189563], 'p_i': 10, 'u_i': 2.9632, 'theta': 0.6612},
        {'id': 11, 'e_m': 2.492789, 'e_o_k': [0.073732, 0.048138, 0.064750], 'p_i': 10, 'u_i': 4.6961, 'theta': 0.7980},
    ]
    B_BUDGET = 386.399991
    return processors, tasks, B_BUDGET
