"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.860003, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1044, "set": 44, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.860003, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1044, "set": 44, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.55, 0.65, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.55, 0.65, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.291215, 'e_o_k': [1.745455, 2.201987], 'p_i': 10, 'u_i': 3.7708, 'theta': 0.7146},
        {'id': 1, 'e_m': 3.607681, 'e_o_k': [0.937870, 1.007686], 'p_i': 20, 'u_i': 1.9100, 'theta': 0.8622},
        {'id': 2, 'e_m': 4.094188, 'e_o_k': [0.416905, 0.479057, 0.371981], 'p_i': 40, 'u_i': 1.9743, 'theta': 0.7474},
        {'id': 3, 'e_m': 0.428340, 'e_o_k': [0.434934, 0.421746], 'p_i': 10, 'u_i': 2.6829, 'theta': 0.7965},
        {'id': 4, 'e_m': 1.812230, 'e_o_k': [1.090535, 1.019569, 1.514357], 'p_i': 40, 'u_i': 1.9636, 'theta': 0.8671},
    ]
    B_BUDGET = 41.860003
    return processors, tasks, B_BUDGET
