"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 54.739999, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1044, "set": 44, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 54.739999, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1044, "set": 44, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.55, 0.65, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.55, 0.65, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.748052, 0.943709], 'p_i': 10, 'u_i': 3.7708, 'theta': 0.7146},
        {'id': 1, 'e_m': 8.417923, 'e_o_k': [0.025630, 0.027538], 'p_i': 20, 'u_i': 1.9100, 'theta': 0.8622},
        {'id': 2, 'e_m': 9.553106, 'e_o_k': [0.178673, 0.205310, 0.159420], 'p_i': 40, 'u_i': 1.9743, 'theta': 0.7474},
        {'id': 3, 'e_m': 1.199460, 'e_o_k': [0.273465, 0.265173], 'p_i': 10, 'u_i': 2.6829, 'theta': 0.7965},
        {'id': 4, 'e_m': 4.813209, 'e_o_k': [0.730741, 0.683188, 1.014734], 'p_i': 40, 'u_i': 1.9636, 'theta': 0.8671},
    ]
    B_BUDGET = 54.739999
    return processors, tasks, B_BUDGET
