"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.860001, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1072, "set": 72, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.860001, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1072, "set": 72, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.6, 0.65, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.6, 0.65, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.409652, 'e_o_k': [0.260045, 0.266675, 0.115424], 'p_i': 10, 'u_i': 2.8289, 'theta': 0.7504},
        {'id': 1, 'e_m': 2.613110, 'e_o_k': [0.483336, 0.467569, 0.335330], 'p_i': 20, 'u_i': 3.2553, 'theta': 0.9563},
        {'id': 2, 'e_m': 0.568499, 'e_o_k': [0.357775, 0.394524, 0.384699], 'p_i': 40, 'u_i': 4.2966, 'theta': 0.7636},
        {'id': 3, 'e_m': 1.070595, 'e_o_k': [1.118487, 1.022703], 'p_i': 20, 'u_i': 4.4047, 'theta': 0.8289},
        {'id': 4, 'e_m': 3.606370, 'e_o_k': [4.359895], 'p_i': 10, 'u_i': 4.8190, 'theta': 0.8812},
    ]
    B_BUDGET = 41.860001
    return processors, tasks, B_BUDGET
