"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600001, "H": 80, "J": 30, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 96.600001, "H": 80, "J": 30, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.75, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.75, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.436038, 'e_o_k': [0.279335], 'p_i': 10, 'u_i': 1.9722, 'theta': 0.6045},
        {'id': 1, 'e_m': 1.455911, 'e_o_k': [0.056772, 0.056337, 0.056019, 0.049768], 'p_i': 20, 'u_i': 1.1293, 'theta': 0.7083},
        {'id': 2, 'e_m': 17.357707, 'e_o_k': [2.060819, 2.577319, 2.745702, 1.876185], 'p_i': 40, 'u_i': 3.4309, 'theta': 0.9600},
        {'id': 3, 'e_m': 1.621852, 'e_o_k': [0.784228, 0.842532, 0.915341, 0.701604], 'p_i': 80, 'u_i': 1.6934, 'theta': 0.6577},
        {'id': 4, 'e_m': 3.241144, 'e_o_k': [0.196170, 0.149031, 0.095104], 'p_i': 20, 'u_i': 4.8596, 'theta': 0.9543},
        {'id': 5, 'e_m': 0.424968, 'e_o_k': [0.239461, 0.139556, 0.201230], 'p_i': 10, 'u_i': 1.8936, 'theta': 0.7278},
        {'id': 6, 'e_m': 16.711513, 'e_o_k': [2.403048, 3.791665], 'p_i': 80, 'u_i': 3.1446, 'theta': 0.7866},
        {'id': 7, 'e_m': 0.637479, 'e_o_k': [0.283017, 0.260447, 0.430600, 0.289970], 'p_i': 40, 'u_i': 4.7605, 'theta': 0.8361},
    ]
    B_BUDGET = 96.600001
    return processors, tasks, B_BUDGET
