"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.200001, "H": 40, "J": 19, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1026, "set": 26, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 193.200001, "H": 40, "J": 19, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1026, "set": 26, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.5, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.5, 0.6, 0.65, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.5, 0.6, 0.65, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.5, 0.6, 0.65, 1.0]},
        {'id': 4, 'frequencies': [0.3, 0.5, 0.6, 0.65, 1.0]},
        {'id': 5, 'frequencies': [0.3, 0.5, 0.6, 0.65, 1.0]},
        {'id': 6, 'frequencies': [0.3, 0.5, 0.6, 0.65, 1.0]},
        {'id': 7, 'frequencies': [0.3, 0.5, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.910663], 'p_i': 10, 'u_i': 1.3249, 'theta': 0.7910},
        {'id': 1, 'e_m': 5.018265, 'e_o_k': [2.383534, 1.501760], 'p_i': 20, 'u_i': 2.5770, 'theta': 0.7474},
        {'id': 2, 'e_m': 13.261195, 'e_o_k': [1.333096, 0.557123, 1.824467], 'p_i': 40, 'u_i': 1.1723, 'theta': 0.8353},
        {'id': 3, 'e_m': 7.984947, 'e_o_k': [2.934039], 'p_i': 40, 'u_i': 1.3594, 'theta': 0.8787},
        {'id': 4, 'e_m': 9.298922, 'e_o_k': [7.336196], 'p_i': 20, 'u_i': 1.2286, 'theta': 0.8841},
        {'id': 5, 'e_m': 8.073635, 'e_o_k': [1.636096, 1.931544, 1.740321], 'p_i': 20, 'u_i': 1.9112, 'theta': 0.8679},
        {'id': 6, 'e_m': 7.800468, 'e_o_k': [6.932304], 'p_i': 40, 'u_i': 4.7212, 'theta': 0.7164},
        {'id': 7, 'e_m': 16.709673, 'e_o_k': [6.207974], 'p_i': 40, 'u_i': 2.0280, 'theta': 0.8828},
        {'id': 8, 'e_m': 3.922487, 'e_o_k': [0.170427], 'p_i': 20, 'u_i': 1.9994, 'theta': 0.7973},
        {'id': 9, 'e_m': 7.870072, 'e_o_k': [5.139872, 4.905315], 'p_i': 40, 'u_i': 1.3454, 'theta': 0.7637},
        {'id': 10, 'e_m': 13.747028, 'e_o_k': [8.746248], 'p_i': 40, 'u_i': 2.1490, 'theta': 0.6069},
        {'id': 11, 'e_m': 20.000000, 'e_o_k': [1.656574, 2.720580], 'p_i': 40, 'u_i': 2.6831, 'theta': 0.7468},
    ]
    B_BUDGET = 193.200001
    return processors, tasks, B_BUDGET
