"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 109.48, "H": 80, "J": 23, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1095, "set": 95, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.7, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 109.48, "H": 80, "J": 23, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1095, "set": 95, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.7, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.75, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.75, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.022326, 'e_o_k': [0.000454, 0.000407, 0.000502], 'p_i': 10, 'u_i': 2.0134, 'theta': 0.9407},
        {'id': 1, 'e_m': 3.137564, 'e_o_k': [0.674540, 0.794885, 0.838021, 0.750264], 'p_i': 20, 'u_i': 3.7568, 'theta': 0.6022},
        {'id': 2, 'e_m': 7.927667, 'e_o_k': [0.014866, 0.021826], 'p_i': 40, 'u_i': 4.1796, 'theta': 0.8842},
        {'id': 3, 'e_m': 2.963524, 'e_o_k': [1.594990, 2.295710, 2.036349], 'p_i': 80, 'u_i': 4.4815, 'theta': 0.9487},
        {'id': 4, 'e_m': 1.468750, 'e_o_k': [1.286933], 'p_i': 20, 'u_i': 1.3170, 'theta': 0.8013},
        {'id': 5, 'e_m': 1.620317, 'e_o_k': [0.534165], 'p_i': 80, 'u_i': 4.6129, 'theta': 0.8858},
        {'id': 6, 'e_m': 5.704518, 'e_o_k': [11.409037], 'p_i': 80, 'u_i': 3.5707, 'theta': 0.9599},
        {'id': 7, 'e_m': 13.626220, 'e_o_k': [5.796197, 4.537249], 'p_i': 40, 'u_i': 3.1846, 'theta': 0.7675},
    ]
    B_BUDGET = 109.480000
    return processors, tasks, B_BUDGET
