"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 109.479995, "H": 80, "J": 29, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1017, "set": 17, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.7, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 109.479995, "H": 80, "J": 29, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1017, "set": 17, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.7, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.476955, 'e_o_k': [0.110141, 0.122156, 0.119681, 0.104464], 'p_i': 10, 'u_i': 2.7614, 'theta': 0.7119},
        {'id': 1, 'e_m': 0.885138, 'e_o_k': [0.561031, 0.579685], 'p_i': 20, 'u_i': 2.1631, 'theta': 0.6261},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [2.876967, 3.049742, 2.764849, 2.861144], 'p_i': 40, 'u_i': 1.7973, 'theta': 0.8162},
        {'id': 3, 'e_m': 8.144283, 'e_o_k': [0.630685, 0.774048, 0.644431, 0.704497], 'p_i': 80, 'u_i': 1.4646, 'theta': 0.7895},
        {'id': 4, 'e_m': 2.411856, 'e_o_k': [1.141316, 1.205307, 0.622717, 0.835357], 'p_i': 40, 'u_i': 3.8388, 'theta': 0.8945},
        {'id': 5, 'e_m': 0.448333, 'e_o_k': [0.378240, 0.244846, 0.273579], 'p_i': 10, 'u_i': 2.3341, 'theta': 0.7676},
        {'id': 6, 'e_m': 2.977376, 'e_o_k': [0.016481, 0.015366, 0.026542], 'p_i': 40, 'u_i': 4.4701, 'theta': 0.8367},
        {'id': 7, 'e_m': 5.067200, 'e_o_k': [1.081550, 1.159284, 0.636465, 0.636218], 'p_i': 40, 'u_i': 2.4522, 'theta': 0.8233},
    ]
    B_BUDGET = 109.479995
    return processors, tasks, B_BUDGET
