"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 38.639999, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1094, "set": 94, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 38.639999, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1094, "set": 94, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.7, 0.8, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.7, 0.8, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.484342, 'e_o_k': [0.176420, 0.143837], 'p_i': 10, 'u_i': 4.3331, 'theta': 0.9083},
        {'id': 1, 'e_m': 4.037510, 'e_o_k': [0.527749, 0.608627], 'p_i': 20, 'u_i': 3.5950, 'theta': 0.8691},
        {'id': 2, 'e_m': 2.571020, 'e_o_k': [1.246063], 'p_i': 40, 'u_i': 4.3548, 'theta': 0.6356},
        {'id': 3, 'e_m': 0.111418, 'e_o_k': [0.047870, 0.033763, 0.047153, 0.043261, 0.050788], 'p_i': 10, 'u_i': 2.5731, 'theta': 0.7266},
        {'id': 4, 'e_m': 9.485460, 'e_o_k': [0.230746, 0.232652, 0.329486, 0.361524], 'p_i': 20, 'u_i': 4.4223, 'theta': 0.6027},
    ]
    B_BUDGET = 38.639999
    return processors, tasks, B_BUDGET
