"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.039996, "H": 80, "J": 28, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.039996, "H": 80, "J": 28, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.401886, 'e_o_k': [0.072932, 0.056657, 0.057455, 0.071458], 'p_i': 10, 'u_i': 1.4642, 'theta': 0.9452},
        {'id': 1, 'e_m': 3.564516, 'e_o_k': [0.034408, 0.038236, 0.036829], 'p_i': 20, 'u_i': 2.6472, 'theta': 0.7334},
        {'id': 2, 'e_m': 6.336196, 'e_o_k': [1.866155, 2.262346], 'p_i': 40, 'u_i': 3.7577, 'theta': 0.6076},
        {'id': 3, 'e_m': 32.439253, 'e_o_k': [1.683351, 3.551193, 4.111634, 2.781279], 'p_i': 80, 'u_i': 4.1236, 'theta': 0.7069},
        {'id': 4, 'e_m': 0.014822, 'e_o_k': [0.007871, 0.008642, 0.003857, 0.009273], 'p_i': 40, 'u_i': 3.3661, 'theta': 0.7466},
        {'id': 5, 'e_m': 2.018864, 'e_o_k': [0.551105], 'p_i': 10, 'u_i': 4.0853, 'theta': 0.7239},
        {'id': 6, 'e_m': 0.800203, 'e_o_k': [0.168840, 0.133290, 0.121448, 0.164206], 'p_i': 80, 'u_i': 3.3611, 'theta': 0.6565},
        {'id': 7, 'e_m': 8.217220, 'e_o_k': [0.739110, 0.709042, 0.578709], 'p_i': 40, 'u_i': 1.3291, 'theta': 0.8571},
    ]
    B_BUDGET = 103.039996
    return processors, tasks, B_BUDGET
