"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 90.16001, "H": 80, "J": 28, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 90.16001, "H": 80, "J": 28, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.267924, 'e_o_k': [0.109398, 0.084985, 0.086183, 0.107187], 'p_i': 10, 'u_i': 1.4642, 'theta': 0.9452},
        {'id': 1, 'e_m': 2.376344, 'e_o_k': [0.051613, 0.057354, 0.055244], 'p_i': 20, 'u_i': 2.6472, 'theta': 0.7334},
        {'id': 2, 'e_m': 4.224131, 'e_o_k': [2.799232, 3.393520], 'p_i': 40, 'u_i': 3.7577, 'theta': 0.6076},
        {'id': 3, 'e_m': 21.626169, 'e_o_k': [2.531885, 5.341257, 6.184202, 4.183249], 'p_i': 80, 'u_i': 4.1236, 'theta': 0.7069},
        {'id': 4, 'e_m': 0.009881, 'e_o_k': [0.005248, 0.005761, 0.002571, 0.006182], 'p_i': 40, 'u_i': 3.3661, 'theta': 0.7466},
        {'id': 5, 'e_m': 1.345910, 'e_o_k': [0.826658], 'p_i': 10, 'u_i': 4.0853, 'theta': 0.7239},
        {'id': 6, 'e_m': 0.533469, 'e_o_k': [0.253260, 0.199936, 0.182171, 0.246309], 'p_i': 80, 'u_i': 3.3611, 'theta': 0.6565},
        {'id': 7, 'e_m': 5.478146, 'e_o_k': [1.108665, 1.063563, 0.868063], 'p_i': 40, 'u_i': 1.3291, 'theta': 0.8571},
    ]
    B_BUDGET = 90.160010
    return processors, tasks, B_BUDGET
