"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 35.419998, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1080, "set": 80, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 35.419998, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1080, "set": 80, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.65, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.65, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.670326, 'e_o_k': [0.794210, 0.460012], 'p_i': 10, 'u_i': 4.8493, 'theta': 0.6104},
        {'id': 1, 'e_m': 0.849571, 'e_o_k': [2.009826, 2.874020], 'p_i': 20, 'u_i': 3.9460, 'theta': 0.8424},
        {'id': 2, 'e_m': 1.420311, 'e_o_k': [2.263555, 2.936241, 3.654919], 'p_i': 40, 'u_i': 1.3860, 'theta': 0.8836},
        {'id': 3, 'e_m': 0.497377, 'e_o_k': [0.792117, 0.637660], 'p_i': 10, 'u_i': 2.9947, 'theta': 0.7557},
        {'id': 4, 'e_m': 0.104868, 'e_o_k': [1.332983, 0.965773, 1.022041], 'p_i': 20, 'u_i': 2.0894, 'theta': 0.7176},
    ]
    B_BUDGET = 35.419998
    return processors, tasks, B_BUDGET
