"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600001, "H": 80, "J": 23, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1067, "set": 67, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.9}
"""

_SPEC = '{"B": 96.600001, "H": 80, "J": 23, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1067, "set": 67, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.9}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.5, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.5, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.033327, 'e_o_k': [0.077069, 0.073011], 'p_i': 10, 'u_i': 3.9820, 'theta': 0.9118},
        {'id': 1, 'e_m': 0.248980, 'e_o_k': [0.218590, 0.279369], 'p_i': 20, 'u_i': 1.6047, 'theta': 0.9788},
        {'id': 2, 'e_m': 4.720665, 'e_o_k': [1.365588, 1.606311, 1.758522], 'p_i': 40, 'u_i': 3.2028, 'theta': 0.9414},
        {'id': 3, 'e_m': 6.340082, 'e_o_k': [1.141574], 'p_i': 80, 'u_i': 3.8814, 'theta': 0.9264},
        {'id': 4, 'e_m': 4.882832, 'e_o_k': [0.038107, 0.041910], 'p_i': 80, 'u_i': 3.3190, 'theta': 0.9157},
        {'id': 5, 'e_m': 29.698668, 'e_o_k': [10.214450, 11.188914], 'p_i': 80, 'u_i': 1.0727, 'theta': 0.9890},
        {'id': 6, 'e_m': 0.072443, 'e_o_k': [0.044019, 0.052738, 0.048130], 'p_i': 20, 'u_i': 2.5549, 'theta': 0.9317},
        {'id': 7, 'e_m': 6.042390, 'e_o_k': [2.071090], 'p_i': 40, 'u_i': 3.1977, 'theta': 0.9926},
    ]
    B_BUDGET = 96.600001
    return processors, tasks, B_BUDGET
