"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600002, "H": 80, "J": 29, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1030, "set": 30, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 96.600002, "H": 80, "J": 29, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1030, "set": 30, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 1.0]},
        {'id': 1, 'frequencies': [0.3, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.081550, 'e_o_k': [0.407812, 0.380888], 'p_i': 10, 'u_i': 2.5160, 'theta': 0.8304},
        {'id': 1, 'e_m': 4.944261, 'e_o_k': [0.706338, 0.831240, 0.849554, 0.333043], 'p_i': 20, 'u_i': 4.0171, 'theta': 0.6646},
        {'id': 2, 'e_m': 7.318923, 'e_o_k': [0.664570, 0.969788, 0.527278, 0.781774], 'p_i': 40, 'u_i': 2.9676, 'theta': 0.6175},
        {'id': 3, 'e_m': 1.013101, 'e_o_k': [0.808466, 0.628572, 0.589164], 'p_i': 80, 'u_i': 2.2124, 'theta': 0.9904},
        {'id': 4, 'e_m': 4.233831, 'e_o_k': [0.293441, 0.437470, 0.460642, 0.280707], 'p_i': 20, 'u_i': 3.3081, 'theta': 0.6961},
        {'id': 5, 'e_m': 16.845805, 'e_o_k': [4.730667], 'p_i': 80, 'u_i': 2.2140, 'theta': 0.6050},
        {'id': 6, 'e_m': 0.352546, 'e_o_k': [0.264120, 0.191579, 0.249392], 'p_i': 80, 'u_i': 4.7249, 'theta': 0.7106},
        {'id': 7, 'e_m': 0.223242, 'e_o_k': [0.138731, 0.118246, 0.189508], 'p_i': 10, 'u_i': 1.7093, 'theta': 0.6768},
    ]
    B_BUDGET = 96.600002
    return processors, tasks, B_BUDGET
