"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 20, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1053, "set": 53, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 20, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1053, "set": 53, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.8, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.8, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.241912, 'e_o_k': [0.483824], 'p_i': 10, 'u_i': 1.8938, 'theta': 0.6429},
        {'id': 1, 'e_m': 1.603082, 'e_o_k': [0.130884, 0.103970], 'p_i': 20, 'u_i': 3.8436, 'theta': 0.9910},
        {'id': 2, 'e_m': 0.810731, 'e_o_k': [0.713230, 0.908232], 'p_i': 40, 'u_i': 2.2713, 'theta': 0.9663},
        {'id': 3, 'e_m': 16.116354, 'e_o_k': [3.581777, 3.964350], 'p_i': 40, 'u_i': 3.4535, 'theta': 0.8079},
        {'id': 4, 'e_m': 5.286644, 'e_o_k': [0.230980, 0.213292], 'p_i': 40, 'u_i': 3.8809, 'theta': 0.6018},
        {'id': 5, 'e_m': 2.068852, 'e_o_k': [0.362382, 0.473207], 'p_i': 10, 'u_i': 2.1566, 'theta': 0.9836},
        {'id': 6, 'e_m': 0.691558, 'e_o_k': [0.880231], 'p_i': 20, 'u_i': 3.4620, 'theta': 0.9313},
        {'id': 7, 'e_m': 0.037376, 'e_o_k': [0.024005, 0.027633, 0.023115], 'p_i': 20, 'u_i': 3.4571, 'theta': 0.7665},
        {'id': 8, 'e_m': 0.836368, 'e_o_k': [0.288284], 'p_i': 40, 'u_i': 4.2932, 'theta': 0.9685},
        {'id': 9, 'e_m': 1.521407, 'e_o_k': [0.391221, 0.458694, 0.371350], 'p_i': 20, 'u_i': 2.4327, 'theta': 0.8408},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
