"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.6, "H": 40, "J": 14, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1018, "set": 18, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.6, "H": 40, "J": 14, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1018, "set": 18, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 2, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 3, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.485268, 'e_o_k': [0.272900, 0.281215], 'p_i': 10, 'u_i': 3.3304, 'theta': 0.9596},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [3.841999, 4.089890], 'p_i': 20, 'u_i': 4.9290, 'theta': 0.6429},
        {'id': 2, 'e_m': 9.921126, 'e_o_k': [2.350965], 'p_i': 40, 'u_i': 2.9402, 'theta': 0.7029},
        {'id': 3, 'e_m': 10.053805, 'e_o_k': [0.909556, 0.671300, 0.572028], 'p_i': 40, 'u_i': 1.1574, 'theta': 0.7365},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [1.137268, 0.809483], 'p_i': 20, 'u_i': 3.6914, 'theta': 0.6024},
        {'id': 5, 'e_m': 2.520999, 'e_o_k': [0.653077, 0.740597, 0.722736, 0.636890, 0.627303], 'p_i': 10, 'u_i': 1.1445, 'theta': 0.6843},
    ]
    B_BUDGET = 96.600000
    return processors, tasks, B_BUDGET
