"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 38.640002, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1009, "set": 9, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 38.640002, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1009, "set": 9, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.4, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.4, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.253888, 'e_o_k': [0.131652, 0.097980, 0.101561, 0.139549, 0.156080], 'p_i': 10, 'u_i': 4.8824, 'theta': 0.6552},
        {'id': 1, 'e_m': 0.636954, 'e_o_k': [0.397346, 0.361278, 0.296056, 0.371215], 'p_i': 20, 'u_i': 2.8329, 'theta': 0.7218},
        {'id': 2, 'e_m': 7.019665, 'e_o_k': [8.385122, 5.266678], 'p_i': 40, 'u_i': 2.3560, 'theta': 0.7776},
        {'id': 3, 'e_m': 1.212834, 'e_o_k': [0.859008, 0.619359, 0.899529], 'p_i': 10, 'u_i': 1.5562, 'theta': 0.9107},
        {'id': 4, 'e_m': 1.839541, 'e_o_k': [1.145344, 1.027840, 1.304355], 'p_i': 40, 'u_i': 3.7774, 'theta': 0.6041},
    ]
    B_BUDGET = 38.640002
    return processors, tasks, B_BUDGET
