"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 28, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1065, "set": 65, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 28, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1065, "set": 65, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.55, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.55, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.211310, 'e_o_k': [0.302628], 'p_i': 10, 'u_i': 2.1055, 'theta': 0.9770},
        {'id': 1, 'e_m': 2.716508, 'e_o_k': [0.117852], 'p_i': 20, 'u_i': 4.1589, 'theta': 0.8048},
        {'id': 2, 'e_m': 3.210270, 'e_o_k': [1.440751, 1.695067], 'p_i': 40, 'u_i': 3.9112, 'theta': 0.6238},
        {'id': 3, 'e_m': 0.193664, 'e_o_k': [0.104605, 0.127085, 0.155637], 'p_i': 10, 'u_i': 2.4877, 'theta': 0.8462},
        {'id': 4, 'e_m': 3.949809, 'e_o_k': [0.764739, 0.979636], 'p_i': 20, 'u_i': 3.3294, 'theta': 0.6585},
        {'id': 5, 'e_m': 6.796750, 'e_o_k': [3.238892], 'p_i': 40, 'u_i': 2.5753, 'theta': 0.9182},
        {'id': 6, 'e_m': 0.484134, 'e_o_k': [0.148448, 0.186275, 0.111697], 'p_i': 10, 'u_i': 1.7054, 'theta': 0.8085},
        {'id': 7, 'e_m': 0.410303, 'e_o_k': [0.266066, 0.273659, 0.280881], 'p_i': 20, 'u_i': 2.1766, 'theta': 0.8358},
        {'id': 8, 'e_m': 0.196453, 'e_o_k': [0.142861, 0.132846], 'p_i': 10, 'u_i': 1.6704, 'theta': 0.6504},
        {'id': 9, 'e_m': 1.874374, 'e_o_k': [0.354056, 0.298768], 'p_i': 10, 'u_i': 2.9798, 'theta': 0.6406},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
