"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 9, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1073, "set": 73, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 9, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1073, "set": 73, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.55, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.55, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.832550, 'e_o_k': [1.738470], 'p_i': 10, 'u_i': 1.2918, 'theta': 0.6565},
        {'id': 1, 'e_m': 1.746979, 'e_o_k': [3.493958], 'p_i': 20, 'u_i': 4.4075, 'theta': 0.6042},
        {'id': 2, 'e_m': 1.372837, 'e_o_k': [0.800840, 0.812949, 0.513807], 'p_i': 40, 'u_i': 2.4961, 'theta': 0.6693},
        {'id': 3, 'e_m': 0.363621, 'e_o_k': [0.238464, 0.334363], 'p_i': 40, 'u_i': 3.3701, 'theta': 0.9610},
        {'id': 4, 'e_m': 15.439382, 'e_o_k': [3.357780], 'p_i': 40, 'u_i': 1.7928, 'theta': 0.9234},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
