"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 51.519997, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1019, "set": 19, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 51.519997, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1019, "set": 19, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.45, 0.55, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.45, 0.55, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.023108, 'e_o_k': [0.014346, 0.015661, 0.016209], 'p_i': 10, 'u_i': 2.8900, 'theta': 0.9690},
        {'id': 1, 'e_m': 9.316417, 'e_o_k': [2.934124], 'p_i': 20, 'u_i': 4.3433, 'theta': 0.7977},
        {'id': 2, 'e_m': 3.226663, 'e_o_k': [1.840794, 1.265588, 1.233830], 'p_i': 40, 'u_i': 1.6754, 'theta': 0.8806},
        {'id': 3, 'e_m': 18.370430, 'e_o_k': [5.198121], 'p_i': 40, 'u_i': 1.4079, 'theta': 0.7167},
        {'id': 4, 'e_m': 7.677639, 'e_o_k': [0.408553], 'p_i': 40, 'u_i': 4.2115, 'theta': 0.9078},
    ]
    B_BUDGET = 51.519997
    return processors, tasks, B_BUDGET
