"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 20.7, "H": 40, "J": 15, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.3, "seed": 1035, "set": 35, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 20.7, "H": 40, "J": 15, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.3, "seed": 1035, "set": 35, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [1.336612, 2.221680], 'p_i': 10, 'u_i': 2.9783, 'theta': 0.6198},
        {'id': 1, 'e_m': 6.688688, 'e_o_k': [0.145584, 0.121132, 0.148269, 0.144941, 0.188143], 'p_i': 20, 'u_i': 4.5368, 'theta': 0.8987},
        {'id': 2, 'e_m': 1.620509, 'e_o_k': [0.108715, 0.240196, 0.133815], 'p_i': 40, 'u_i': 3.1574, 'theta': 0.8277},
        {'id': 3, 'e_m': 0.860027, 'e_o_k': [0.206168, 0.221988, 0.199737], 'p_i': 10, 'u_i': 4.2592, 'theta': 0.7037},
        {'id': 4, 'e_m': 0.390502, 'e_o_k': [0.153292, 0.165807], 'p_i': 10, 'u_i': 4.9113, 'theta': 0.9713},
    ]
    B_BUDGET = 20.700000
    return processors, tasks, B_BUDGET
