"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300001, "H": 40, "J": 15, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1002, "set": 2, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 48.300001, "H": 40, "J": 15, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1002, "set": 2, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.7, 1.0]},
        {'id': 1, 'frequencies': [0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.991487, 'e_o_k': [1.158405], 'p_i': 10, 'u_i': 3.7056, 'theta': 0.9027},
        {'id': 1, 'e_m': 2.582223, 'e_o_k': [2.219942], 'p_i': 20, 'u_i': 2.2476, 'theta': 0.9013},
        {'id': 2, 'e_m': 3.938882, 'e_o_k': [2.075584, 3.217576, 2.584605], 'p_i': 40, 'u_i': 3.3146, 'theta': 0.9742},
        {'id': 3, 'e_m': 1.414231, 'e_o_k': [0.299815, 0.290507], 'p_i': 10, 'u_i': 1.2870, 'theta': 0.7712},
        {'id': 4, 'e_m': 2.318450, 'e_o_k': [0.171861], 'p_i': 10, 'u_i': 3.5798, 'theta': 0.7565},
    ]
    B_BUDGET = 48.300001
    return processors, tasks, B_BUDGET
