"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.039993, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1086, "set": 86, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.039993, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1086, "set": 86, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.6, 0.75, 0.8, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.6, 0.75, 0.8, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.194517, 'e_o_k': [0.389034], 'p_i': 10, 'u_i': 2.5000, 'theta': 0.7427},
        {'id': 1, 'e_m': 4.257857, 'e_o_k': [0.248112, 0.278367, 0.234423], 'p_i': 20, 'u_i': 4.5914, 'theta': 0.9820},
        {'id': 2, 'e_m': 4.230348, 'e_o_k': [2.035496, 2.176197, 1.671864, 1.809424], 'p_i': 40, 'u_i': 4.9966, 'theta': 0.6966},
        {'id': 3, 'e_m': 7.203097, 'e_o_k': [0.467117, 0.305072], 'p_i': 80, 'u_i': 4.3617, 'theta': 0.7916},
        {'id': 4, 'e_m': 14.391897, 'e_o_k': [2.853418], 'p_i': 80, 'u_i': 3.4650, 'theta': 0.8352},
        {'id': 5, 'e_m': 4.799167, 'e_o_k': [0.085057, 0.072441, 0.063886, 0.067149], 'p_i': 20, 'u_i': 4.5543, 'theta': 0.9506},
        {'id': 6, 'e_m': 13.546545, 'e_o_k': [0.608985, 0.336338, 0.663797, 0.540323], 'p_i': 40, 'u_i': 4.6035, 'theta': 0.8169},
        {'id': 7, 'e_m': 0.266747, 'e_o_k': [0.175650, 0.169231], 'p_i': 20, 'u_i': 4.5279, 'theta': 0.7629},
    ]
    B_BUDGET = 103.039993
    return processors, tasks, B_BUDGET
