"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 35.419998, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1014, "set": 14, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 35.419998, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1014, "set": 14, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.5, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.5, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.013357, 'e_o_k': [1.390964, 0.940354], 'p_i': 10, 'u_i': 1.9931, 'theta': 0.9545},
        {'id': 1, 'e_m': 0.581695, 'e_o_k': [0.429614, 0.507206, 0.487896], 'p_i': 20, 'u_i': 1.9801, 'theta': 0.9034},
        {'id': 2, 'e_m': 2.148881, 'e_o_k': [1.394547, 1.269697, 1.242384, 1.380309], 'p_i': 40, 'u_i': 4.8973, 'theta': 0.9205},
        {'id': 3, 'e_m': 1.128688, 'e_o_k': [1.346057, 1.469780, 1.625523, 1.190987, 1.347198], 'p_i': 20, 'u_i': 1.8205, 'theta': 0.8080},
        {'id': 4, 'e_m': 2.376924, 'e_o_k': [4.579267], 'p_i': 40, 'u_i': 4.9535, 'theta': 0.7907},
    ]
    B_BUDGET = 35.419998
    return processors, tasks, B_BUDGET
