"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 38.640002, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1090, "set": 90, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 38.640002, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1090, "set": 90, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.55, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.55, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.477636, 'e_o_k': [0.251913, 0.330892, 0.328299], 'p_i': 10, 'u_i': 3.4235, 'theta': 0.6683},
        {'id': 1, 'e_m': 1.482124, 'e_o_k': [2.779038], 'p_i': 20, 'u_i': 3.8684, 'theta': 0.9950},
        {'id': 2, 'e_m': 2.498176, 'e_o_k': [3.257284, 2.270972], 'p_i': 40, 'u_i': 4.4932, 'theta': 0.6486},
        {'id': 3, 'e_m': 1.493692, 'e_o_k': [0.964092, 0.843950, 1.085835], 'p_i': 10, 'u_i': 3.6924, 'theta': 0.9834},
        {'id': 4, 'e_m': 2.652263, 'e_o_k': [1.436050, 2.058358, 2.199340], 'p_i': 40, 'u_i': 2.3215, 'theta': 0.8009},
    ]
    B_BUDGET = 38.640002
    return processors, tasks, B_BUDGET
