"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.60001, "H": 80, "J": 35, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1037, "set": 37, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.4}
"""

_SPEC = '{"B": 96.60001, "H": 80, "J": 35, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1037, "set": 37, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.4}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.65, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.65, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.749396, 'e_o_k': [0.369975, 0.220124, 0.383957, 0.524737], 'p_i': 10, 'u_i': 2.4987, 'theta': 0.7321},
        {'id': 1, 'e_m': 1.393525, 'e_o_k': [0.039723, 0.046798], 'p_i': 20, 'u_i': 4.1789, 'theta': 0.6768},
        {'id': 2, 'e_m': 0.804121, 'e_o_k': [0.834230, 0.774011], 'p_i': 40, 'u_i': 4.1005, 'theta': 0.6198},
        {'id': 3, 'e_m': 3.792721, 'e_o_k': [1.781511, 1.115004, 2.780012, 1.908915], 'p_i': 80, 'u_i': 1.7296, 'theta': 0.5497},
        {'id': 4, 'e_m': 1.571512, 'e_o_k': [0.105453, 0.122790, 0.079881, 0.130336], 'p_i': 10, 'u_i': 3.9876, 'theta': 0.5803},
        {'id': 5, 'e_m': 1.194177, 'e_o_k': [0.013536], 'p_i': 10, 'u_i': 2.0927, 'theta': 0.8509},
        {'id': 6, 'e_m': 19.599486, 'e_o_k': [4.917551], 'p_i': 40, 'u_i': 2.9850, 'theta': 0.4532},
        {'id': 7, 'e_m': 0.852646, 'e_o_k': [0.604578, 0.409731, 0.279810, 0.411173], 'p_i': 40, 'u_i': 4.7563, 'theta': 0.4135},
    ]
    B_BUDGET = 96.600010
    return processors, tasks, B_BUDGET
