"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 70.839997, "H": 80, "J": 35, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1082, "set": 82, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 70.839997, "H": 80, "J": 35, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1082, "set": 82, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.079662, 'e_o_k': [0.470876], 'p_i': 10, 'u_i': 2.2002, 'theta': 0.9995},
        {'id': 1, 'e_m': 0.461758, 'e_o_k': [3.024921], 'p_i': 20, 'u_i': 4.7373, 'theta': 0.7516},
        {'id': 2, 'e_m': 2.224244, 'e_o_k': [8.492589], 'p_i': 40, 'u_i': 2.8710, 'theta': 0.9511},
        {'id': 3, 'e_m': 6.630817, 'e_o_k': [12.911035], 'p_i': 80, 'u_i': 2.5650, 'theta': 0.6497},
        {'id': 4, 'e_m': 0.554035, 'e_o_k': [0.541299, 0.999758, 0.701379], 'p_i': 40, 'u_i': 3.1573, 'theta': 0.7411},
        {'id': 5, 'e_m': 0.104193, 'e_o_k': [1.943286, 1.271963, 1.275288], 'p_i': 40, 'u_i': 1.8500, 'theta': 0.6812},
        {'id': 6, 'e_m': 0.015895, 'e_o_k': [0.086067, 0.087614, 0.072094, 0.087385], 'p_i': 10, 'u_i': 3.3146, 'theta': 0.8934},
        {'id': 7, 'e_m': 0.124093, 'e_o_k': [0.319013, 0.337411, 0.260282, 0.346528], 'p_i': 10, 'u_i': 4.6347, 'theta': 0.7406},
    ]
    B_BUDGET = 70.839997
    return processors, tasks, B_BUDGET
