"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 45.079998, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1087, "set": 87, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 45.079998, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1087, "set": 87, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.657890, 'e_o_k': [0.845164, 1.342052], 'p_i': 10, 'u_i': 1.9244, 'theta': 0.6027},
        {'id': 1, 'e_m': 0.492895, 'e_o_k': [0.234946, 0.257420, 0.366875, 0.126549], 'p_i': 20, 'u_i': 3.1301, 'theta': 0.9461},
        {'id': 2, 'e_m': 9.804985, 'e_o_k': [1.263565, 1.229587, 0.966412, 1.347037, 1.381455], 'p_i': 40, 'u_i': 1.0253, 'theta': 0.9952},
        {'id': 3, 'e_m': 1.470922, 'e_o_k': [1.028442], 'p_i': 10, 'u_i': 4.4386, 'theta': 0.8067},
        {'id': 4, 'e_m': 2.346987, 'e_o_k': [0.447437, 0.405583, 0.318714, 0.317132], 'p_i': 20, 'u_i': 3.8018, 'theta': 0.9746},
    ]
    B_BUDGET = 45.079998
    return processors, tasks, B_BUDGET
