"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600004, "H": 80, "J": 18, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1028, "set": 28, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}
"""

_SPEC = '{"B": 96.600004, "H": 80, "J": 18, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1028, "set": 28, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.6, 0.65, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.6, 0.65, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.139277, 'e_o_k': [0.415046], 'p_i': 10, 'u_i': 4.8771, 'theta': 0.9602},
        {'id': 1, 'e_m': 1.506800, 'e_o_k': [0.060795, 0.101934], 'p_i': 20, 'u_i': 4.8003, 'theta': 0.6578},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [1.931453, 1.882312, 1.880867], 'p_i': 40, 'u_i': 3.1015, 'theta': 0.6469},
        {'id': 3, 'e_m': 13.159757, 'e_o_k': [0.643071, 0.598721], 'p_i': 80, 'u_i': 3.7989, 'theta': 0.8181},
        {'id': 4, 'e_m': 5.750951, 'e_o_k': [11.501903], 'p_i': 80, 'u_i': 2.0870, 'theta': 0.7918},
        {'id': 5, 'e_m': 2.973940, 'e_o_k': [3.233345, 2.714534], 'p_i': 40, 'u_i': 4.0454, 'theta': 0.7463},
    ]
    B_BUDGET = 96.600004
    return processors, tasks, B_BUDGET
