"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599994, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1028, "set": 28, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.599994, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1028, "set": 28, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.6, 0.65, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.6, 0.65, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.244184, 'e_o_k': [3.545047], 'p_i': 10, 'u_i': 3.2922, 'theta': 0.6308},
        {'id': 1, 'e_m': 4.047783, 'e_o_k': [1.933592], 'p_i': 20, 'u_i': 4.8639, 'theta': 0.9877},
        {'id': 2, 'e_m': 3.444712, 'e_o_k': [0.439847], 'p_i': 40, 'u_i': 2.7113, 'theta': 0.9800},
        {'id': 3, 'e_m': 38.965969, 'e_o_k': [1.395908, 1.629649], 'p_i': 80, 'u_i': 1.4980, 'theta': 0.7537},
    ]
    B_BUDGET = 96.599994
    return processors, tasks, B_BUDGET
