"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600006, "H": 80, "J": 55, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1028, "set": 28, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 96.600006, "H": 80, "J": 55, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1028, "set": 28, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.6, 0.65, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.6, 0.65, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.122567, 'e_o_k': [0.245134], 'p_i': 10, 'u_i': 2.0870, 'theta': 0.7918},
        {'id': 1, 'e_m': 0.144577, 'e_o_k': [0.157188, 0.131966], 'p_i': 20, 'u_i': 4.0454, 'theta': 0.7463},
        {'id': 2, 'e_m': 2.352882, 'e_o_k': [0.374799], 'p_i': 40, 'u_i': 1.4077, 'theta': 0.8893},
        {'id': 3, 'e_m': 20.214007, 'e_o_k': [7.061952, 6.765874], 'p_i': 80, 'u_i': 4.9126, 'theta': 0.8276},
        {'id': 4, 'e_m': 14.675629, 'e_o_k': [1.813909, 1.709700], 'p_i': 80, 'u_i': 2.7810, 'theta': 0.6509},
        {'id': 5, 'e_m': 3.409290, 'e_o_k': [0.408218, 0.424505, 0.391645], 'p_i': 40, 'u_i': 3.6618, 'theta': 0.7630},
        {'id': 6, 'e_m': 0.718933, 'e_o_k': [0.447587, 0.529342, 0.460937], 'p_i': 80, 'u_i': 4.8901, 'theta': 0.9521},
        {'id': 7, 'e_m': 4.013637, 'e_o_k': [0.755608, 0.679947], 'p_i': 20, 'u_i': 3.4912, 'theta': 0.6276},
        {'id': 8, 'e_m': 0.843527, 'e_o_k': [0.146264, 0.116982], 'p_i': 10, 'u_i': 1.0991, 'theta': 0.6567},
        {'id': 9, 'e_m': 0.232513, 'e_o_k': [0.121113, 0.172823, 0.130427], 'p_i': 10, 'u_i': 1.6586, 'theta': 0.8398},
        {'id': 10, 'e_m': 0.642222, 'e_o_k': [0.047217, 0.023058, 0.046061], 'p_i': 10, 'u_i': 1.8786, 'theta': 0.8442},
        {'id': 11, 'e_m': 0.188451, 'e_o_k': [0.103374, 0.125513, 0.111225], 'p_i': 10, 'u_i': 4.8718, 'theta': 0.8937},
    ]
    B_BUDGET = 96.600006
    return processors, tasks, B_BUDGET
