"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.859998, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1046, "set": 46, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.3, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.859998, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1046, "set": 46, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.3, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.65, 0.75, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.65, 0.75, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.845175, 'e_o_k': [0.059135, 0.075382, 0.065960, 0.088087], 'p_i': 10, 'u_i': 1.8853, 'theta': 0.8981},
        {'id': 1, 'e_m': 0.749980, 'e_o_k': [0.110183, 0.086659, 0.104409, 0.101852, 0.082242], 'p_i': 20, 'u_i': 3.0945, 'theta': 0.8138},
        {'id': 2, 'e_m': 18.245906, 'e_o_k': [3.024187, 4.000434], 'p_i': 40, 'u_i': 2.5491, 'theta': 0.8227},
        {'id': 3, 'e_m': 0.459449, 'e_o_k': [0.918899], 'p_i': 20, 'u_i': 1.1781, 'theta': 0.7461},
        {'id': 4, 'e_m': 0.988634, 'e_o_k': [0.062047, 0.066144, 0.052862, 0.072105], 'p_i': 10, 'u_i': 2.7848, 'theta': 0.6882},
    ]
    B_BUDGET = 41.859998
    return processors, tasks, B_BUDGET
