"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 45.079998, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1053, "set": 53, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 45.079998, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1053, "set": 53, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.8, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.8, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.456990, 'e_o_k': [0.945211], 'p_i': 10, 'u_i': 4.8835, 'theta': 0.6234},
        {'id': 1, 'e_m': 0.526242, 'e_o_k': [0.095816, 0.093371, 0.117824, 0.120955, 0.097810], 'p_i': 20, 'u_i': 2.9136, 'theta': 0.6747},
        {'id': 2, 'e_m': 4.849165, 'e_o_k': [2.065313, 2.149036, 1.919062, 2.103389, 1.461529], 'p_i': 40, 'u_i': 3.2349, 'theta': 0.8844},
        {'id': 3, 'e_m': 3.218283, 'e_o_k': [0.746227, 1.083715, 0.599604], 'p_i': 40, 'u_i': 1.9756, 'theta': 0.7271},
        {'id': 4, 'e_m': 13.052109, 'e_o_k': [2.116164, 1.706157, 1.368190, 1.849214], 'p_i': 40, 'u_i': 3.0790, 'theta': 0.7457},
    ]
    B_BUDGET = 45.079998
    return processors, tasks, B_BUDGET
