"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.6, "H": 80, "J": 19, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1012, "set": 12, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}
"""

_SPEC = '{"B": 96.6, "H": 80, "J": 19, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1012, "set": 12, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.45, 0.55, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.45, 0.55, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.823277, 'e_o_k': [0.317682, 0.398743, 0.445535, 0.484594], 'p_i': 10, 'u_i': 4.5368, 'theta': 0.8241},
        {'id': 1, 'e_m': 3.476950, 'e_o_k': [0.247983, 0.410959], 'p_i': 20, 'u_i': 2.1438, 'theta': 0.6432},
        {'id': 2, 'e_m': 4.790495, 'e_o_k': [1.853554, 1.330809], 'p_i': 40, 'u_i': 4.8131, 'theta': 0.9604},
        {'id': 3, 'e_m': 9.830473, 'e_o_k': [1.242051], 'p_i': 80, 'u_i': 3.0133, 'theta': 0.7462},
        {'id': 4, 'e_m': 11.221282, 'e_o_k': [3.142834, 3.381487], 'p_i': 40, 'u_i': 1.2469, 'theta': 0.6745},
        {'id': 5, 'e_m': 8.825979, 'e_o_k': [1.221192, 0.544998], 'p_i': 40, 'u_i': 3.1829, 'theta': 0.8687},
    ]
    B_BUDGET = 96.600000
    return processors, tasks, B_BUDGET
