"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300003, "H": 40, "J": 25, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.300003, "H": 40, "J": 25, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.902975, 'e_o_k': [1.155837], 'p_i': 10, 'u_i': 4.7591, 'theta': 0.9537},
        {'id': 1, 'e_m': 3.953824, 'e_o_k': [0.020793, 0.020182, 0.016825], 'p_i': 20, 'u_i': 2.8801, 'theta': 0.6918},
        {'id': 2, 'e_m': 7.101955, 'e_o_k': [0.931488, 1.108809, 0.591544], 'p_i': 40, 'u_i': 1.2068, 'theta': 0.9259},
        {'id': 3, 'e_m': 1.264388, 'e_o_k': [0.080743, 0.085186], 'p_i': 10, 'u_i': 2.5480, 'theta': 0.9911},
        {'id': 4, 'e_m': 1.338601, 'e_o_k': [1.385696], 'p_i': 10, 'u_i': 4.3203, 'theta': 0.6004},
        {'id': 5, 'e_m': 0.637681, 'e_o_k': [0.137121, 0.078429], 'p_i': 10, 'u_i': 1.6821, 'theta': 0.6794},
        {'id': 6, 'e_m': 3.205065, 'e_o_k': [1.950697], 'p_i': 20, 'u_i': 4.2890, 'theta': 0.9385},
        {'id': 7, 'e_m': 0.501422, 'e_o_k': [0.414780], 'p_i': 10, 'u_i': 2.7802, 'theta': 0.7319},
    ]
    B_BUDGET = 48.300003
    return processors, tasks, B_BUDGET
