"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 45.080007, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 45.080007, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.162793, 'e_o_k': [0.431294, 0.328403, 0.206015, 0.259040, 0.307485], 'p_i': 10, 'u_i': 2.4344, 'theta': 0.7719},
        {'id': 1, 'e_m': 4.708093, 'e_o_k': [2.292430], 'p_i': 20, 'u_i': 1.9085, 'theta': 0.8191},
        {'id': 2, 'e_m': 0.805441, 'e_o_k': [0.832124, 0.778758], 'p_i': 40, 'u_i': 2.2654, 'theta': 0.7866},
        {'id': 3, 'e_m': 3.226911, 'e_o_k': [0.631337, 0.462670, 0.355105, 0.726232, 0.633706], 'p_i': 10, 'u_i': 3.6211, 'theta': 0.6252},
        {'id': 4, 'e_m': 0.109779, 'e_o_k': [0.053613, 0.049012, 0.064087, 0.052847], 'p_i': 20, 'u_i': 3.1655, 'theta': 0.7901},
    ]
    B_BUDGET = 45.080007
    return processors, tasks, B_BUDGET
