"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300001, "H": 40, "J": 18, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1078, "set": 78, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.300001, "H": 40, "J": 18, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1078, "set": 78, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.5, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.5, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.559216, 'e_o_k': [0.427950, 0.351902], 'p_i': 10, 'u_i': 1.2376, 'theta': 0.7021},
        {'id': 1, 'e_m': 1.271950, 'e_o_k': [1.177184, 1.366716], 'p_i': 20, 'u_i': 3.6406, 'theta': 0.9568},
        {'id': 2, 'e_m': 1.741762, 'e_o_k': [2.835559], 'p_i': 40, 'u_i': 4.1768, 'theta': 0.8798},
        {'id': 3, 'e_m': 5.174545, 'e_o_k': [2.007412], 'p_i': 20, 'u_i': 1.1960, 'theta': 0.7370},
        {'id': 4, 'e_m': 0.210335, 'e_o_k': [0.086094], 'p_i': 20, 'u_i': 3.0599, 'theta': 0.9395},
        {'id': 5, 'e_m': 2.765560, 'e_o_k': [3.575566], 'p_i': 40, 'u_i': 2.6805, 'theta': 0.9049},
        {'id': 6, 'e_m': 0.842735, 'e_o_k': [0.001364], 'p_i': 10, 'u_i': 3.4798, 'theta': 0.8352},
        {'id': 7, 'e_m': 8.285607, 'e_o_k': [0.227996, 0.199393, 0.167211], 'p_i': 20, 'u_i': 4.2978, 'theta': 0.6056},
    ]
    B_BUDGET = 48.300001
    return processors, tasks, B_BUDGET
