"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.859997, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.3, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.859997, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.3, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.020595, 'e_o_k': [0.361636, 0.262009], 'p_i': 10, 'u_i': 4.6615, 'theta': 0.6774},
        {'id': 1, 'e_m': 1.075800, 'e_o_k': [0.556685, 0.622724, 0.480652], 'p_i': 20, 'u_i': 2.5264, 'theta': 0.7336},
        {'id': 2, 'e_m': 13.919066, 'e_o_k': [0.073416, 0.047940, 0.059624], 'p_i': 40, 'u_i': 1.4642, 'theta': 0.9452},
        {'id': 3, 'e_m': 6.349614, 'e_o_k': [0.645214, 0.716984], 'p_i': 20, 'u_i': 2.3811, 'theta': 0.8284},
        {'id': 4, 'e_m': 1.786931, 'e_o_k': [0.382444, 0.437536], 'p_i': 10, 'u_i': 4.2272, 'theta': 0.9006},
    ]
    B_BUDGET = 41.859997
    return processors, tasks, B_BUDGET
