"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300001, "H": 40, "J": 15, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.300001, "H": 40, "J": 15, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.5, 0.55, 0.6, 0.65, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.5, 0.55, 0.6, 0.65, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.740963, 'e_o_k': [0.131237, 0.308926, 0.127580], 'p_i': 10, 'u_i': 1.6257, 'theta': 0.6026},
        {'id': 1, 'e_m': 5.502133, 'e_o_k': [2.496403, 2.083442], 'p_i': 20, 'u_i': 3.8662, 'theta': 0.6386},
        {'id': 2, 'e_m': 2.373133, 'e_o_k': [2.239787, 2.384597], 'p_i': 40, 'u_i': 4.8494, 'theta': 0.6523},
        {'id': 3, 'e_m': 3.047809, 'e_o_k': [0.240817, 0.168509, 0.152760], 'p_i': 10, 'u_i': 1.7973, 'theta': 0.7246},
        {'id': 4, 'e_m': 1.866879, 'e_o_k': [0.424152], 'p_i': 10, 'u_i': 2.8808, 'theta': 0.6221},
    ]
    B_BUDGET = 48.300001
    return processors, tasks, B_BUDGET
