"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 57.959999, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1014, "set": 14, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 57.959999, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1014, "set": 14, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.5, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.5, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.066787, 'e_o_k': [0.079696, 0.053878], 'p_i': 10, 'u_i': 1.9931, 'theta': 0.9545},
        {'id': 1, 'e_m': 2.908475, 'e_o_k': [0.381879, 0.450850, 0.433686], 'p_i': 20, 'u_i': 1.9801, 'theta': 0.9034},
        {'id': 2, 'e_m': 10.744403, 'e_o_k': [1.667305, 1.518035, 1.485381, 1.650282], 'p_i': 40, 'u_i': 4.8973, 'theta': 0.9205},
        {'id': 3, 'e_m': 5.643439, 'e_o_k': [1.333638, 1.456220, 1.610525, 1.179999, 1.334768], 'p_i': 20, 'u_i': 1.8205, 'theta': 0.8080},
        {'id': 4, 'e_m': 11.884621, 'e_o_k': [8.781570], 'p_i': 40, 'u_i': 4.9535, 'theta': 0.7907},
    ]
    B_BUDGET = 57.959999
    return processors, tasks, B_BUDGET
