"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 70.840008, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 70.840008, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.679480, 'e_o_k': [0.885273, 0.819552, 0.565380, 1.081964], 'p_i': 10, 'u_i': 4.8579, 'theta': 0.6157},
        {'id': 1, 'e_m': 0.412772, 'e_o_k': [0.175039, 0.212728, 0.252394], 'p_i': 20, 'u_i': 2.8364, 'theta': 0.9742},
        {'id': 2, 'e_m': 1.256454, 'e_o_k': [0.363830, 0.651744, 0.557215, 0.642913], 'p_i': 40, 'u_i': 2.5400, 'theta': 0.8202},
        {'id': 3, 'e_m': 1.374328, 'e_o_k': [1.454044, 1.215184], 'p_i': 80, 'u_i': 3.1655, 'theta': 0.7901},
        {'id': 4, 'e_m': 0.620159, 'e_o_k': [1.369631, 1.904737], 'p_i': 20, 'u_i': 1.9656, 'theta': 0.6665},
        {'id': 5, 'e_m': 1.001883, 'e_o_k': [2.782238, 2.611131, 2.658124, 3.119602], 'p_i': 80, 'u_i': 3.5220, 'theta': 0.7736},
        {'id': 6, 'e_m': 0.024880, 'e_o_k': [3.608740], 'p_i': 40, 'u_i': 2.3507, 'theta': 0.9362},
        {'id': 7, 'e_m': 0.373389, 'e_o_k': [0.659333, 0.349501], 'p_i': 20, 'u_i': 1.9884, 'theta': 0.7576},
    ]
    B_BUDGET = 70.840008
    return processors, tasks, B_BUDGET
