"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599998, "H": 40, "J": 17, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1087, "set": 87, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.599998, "H": 40, "J": 17, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1087, "set": 87, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.094162, 0.112847], 'p_i': 10, 'u_i': 4.8034, 'theta': 0.9129},
        {'id': 1, 'e_m': 5.800101, 'e_o_k': [0.917744, 0.666145, 0.578996, 0.751836, 0.761493], 'p_i': 20, 'u_i': 3.6003, 'theta': 0.6591},
        {'id': 2, 'e_m': 13.218843, 'e_o_k': [0.199417, 0.220907, 0.194941, 0.427850, 0.237386], 'p_i': 40, 'u_i': 2.6908, 'theta': 0.9792},
        {'id': 3, 'e_m': 2.958655, 'e_o_k': [2.917593], 'p_i': 10, 'u_i': 2.5549, 'theta': 0.7125},
        {'id': 4, 'e_m': 5.800293, 'e_o_k': [0.676085, 0.635274, 0.632122, 0.711216], 'p_i': 20, 'u_i': 4.8390, 'theta': 0.6533},
        {'id': 5, 'e_m': 2.936437, 'e_o_k': [0.453916, 0.843068, 0.950265, 1.142568], 'p_i': 10, 'u_i': 2.2557, 'theta': 0.7061},
    ]
    B_BUDGET = 96.599998
    return processors, tasks, B_BUDGET
