"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 45.08, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1093, "set": 93, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 45.08, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1093, "set": 93, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.6, 0.75, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.6, 0.75, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.458953, 0.490319, 0.474665], 'p_i': 10, 'u_i': 1.8233, 'theta': 0.7359},
        {'id': 1, 'e_m': 1.242429, 'e_o_k': [0.471541, 0.424132, 0.337445], 'p_i': 20, 'u_i': 3.1280, 'theta': 0.8476},
        {'id': 2, 'e_m': 2.524084, 'e_o_k': [0.439600, 0.430057, 0.597653, 0.479695, 0.379111], 'p_i': 40, 'u_i': 3.4294, 'theta': 0.8791},
        {'id': 3, 'e_m': 1.363048, 'e_o_k': [0.710644, 0.690394, 1.325058], 'p_i': 20, 'u_i': 3.0558, 'theta': 0.8309},
        {'id': 4, 'e_m': 4.264962, 'e_o_k': [1.608526, 0.811780, 2.368482, 1.908688, 1.362232], 'p_i': 40, 'u_i': 2.6038, 'theta': 0.6078},
    ]
    B_BUDGET = 45.080000
    return processors, tasks, B_BUDGET
