"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300003, "H": 40, "J": 14, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1076, "set": 76, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}
"""

_SPEC = '{"B": 48.300003, "H": 40, "J": 14, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1076, "set": 76, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.55, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.55, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.585409, 'e_o_k': [0.089490, 0.082047, 0.094746], 'p_i': 10, 'u_i': 1.7953, 'theta': 0.8404},
        {'id': 1, 'e_m': 1.140979, 'e_o_k': [2.281957], 'p_i': 20, 'u_i': 3.8298, 'theta': 0.9259},
        {'id': 2, 'e_m': 2.228713, 'e_o_k': [1.288577, 1.005294, 1.047677], 'p_i': 40, 'u_i': 1.4994, 'theta': 0.6879},
        {'id': 3, 'e_m': 0.630934, 'e_o_k': [0.715450], 'p_i': 10, 'u_i': 3.4182, 'theta': 0.6888},
        {'id': 4, 'e_m': 10.623960, 'e_o_k': [3.993389], 'p_i': 40, 'u_i': 3.2238, 'theta': 0.7366},
        {'id': 5, 'e_m': 10.000000, 'e_o_k': [0.785522, 0.629843, 0.671744], 'p_i': 20, 'u_i': 1.0080, 'theta': 0.8752},
    ]
    B_BUDGET = 48.300003
    return processors, tasks, B_BUDGET
