"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300006, "H": 40, "J": 21, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1076, "set": 76, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 48.300006, "H": 40, "J": 21, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1076, "set": 76, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.55, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.55, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.564745, 'e_o_k': [0.103015, 0.112862], 'p_i': 10, 'u_i': 1.8789, 'theta': 0.6248},
        {'id': 1, 'e_m': 3.275920, 'e_o_k': [1.749401], 'p_i': 20, 'u_i': 2.0698, 'theta': 0.8224},
        {'id': 2, 'e_m': 4.297690, 'e_o_k': [0.500965, 0.596455], 'p_i': 40, 'u_i': 1.3211, 'theta': 0.6008},
        {'id': 3, 'e_m': 0.311447, 'e_o_k': [0.234293, 0.216184, 0.172418], 'p_i': 10, 'u_i': 1.6778, 'theta': 0.8512},
        {'id': 4, 'e_m': 6.740652, 'e_o_k': [0.897050], 'p_i': 40, 'u_i': 1.1133, 'theta': 0.6264},
        {'id': 5, 'e_m': 2.150987, 'e_o_k': [0.104794, 0.114832], 'p_i': 20, 'u_i': 3.0737, 'theta': 0.8121},
        {'id': 6, 'e_m': 9.506263, 'e_o_k': [6.116799], 'p_i': 40, 'u_i': 2.0620, 'theta': 0.8239},
        {'id': 7, 'e_m': 0.702648, 'e_o_k': [0.357450, 0.630780], 'p_i': 10, 'u_i': 2.8583, 'theta': 0.8574},
        {'id': 8, 'e_m': 1.974505, 'e_o_k': [0.019234], 'p_i': 40, 'u_i': 1.6819, 'theta': 0.7175},
        {'id': 9, 'e_m': 0.311720, 'e_o_k': [0.623439], 'p_i': 40, 'u_i': 1.9159, 'theta': 0.9567},
    ]
    B_BUDGET = 48.300006
    return processors, tasks, B_BUDGET
