"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.60001, "H": 80, "J": 37, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1090, "set": 90, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 96.60001, "H": 80, "J": 37, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1090, "set": 90, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 1.0]},
        {'id': 1, 'frequencies': [0.4, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.962787, 'e_o_k': [0.414569], 'p_i': 10, 'u_i': 3.3237, 'theta': 0.9493},
        {'id': 1, 'e_m': 1.469041, 'e_o_k': [0.182947], 'p_i': 20, 'u_i': 1.6064, 'theta': 0.8830},
        {'id': 2, 'e_m': 6.978856, 'e_o_k': [0.409043, 0.623770, 0.799533], 'p_i': 40, 'u_i': 4.2470, 'theta': 0.6636},
        {'id': 3, 'e_m': 0.728613, 'e_o_k': [1.457227], 'p_i': 80, 'u_i': 2.3215, 'theta': 0.8009},
        {'id': 4, 'e_m': 2.916724, 'e_o_k': [0.175599, 0.130121, 0.116797, 0.160587], 'p_i': 40, 'u_i': 4.6410, 'theta': 0.7851},
        {'id': 5, 'e_m': 2.429836, 'e_o_k': [0.663474, 0.779889, 0.794391, 0.712900], 'p_i': 20, 'u_i': 1.3550, 'theta': 0.6154},
        {'id': 6, 'e_m': 0.896702, 'e_o_k': [0.684791, 0.371005, 0.456141], 'p_i': 10, 'u_i': 3.0573, 'theta': 0.6117},
        {'id': 7, 'e_m': 3.626101, 'e_o_k': [0.180880, 0.182257, 0.173581, 0.183961], 'p_i': 10, 'u_i': 4.6517, 'theta': 0.7745},
    ]
    B_BUDGET = 96.600010
    return processors, tasks, B_BUDGET
