"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300003, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1000, "set": 0, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 48.300003, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1000, "set": 0, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.619285, 'e_o_k': [0.504718, 0.596869, 0.745868], 'p_i': 10, 'u_i': 2.9499, 'theta': 0.7846},
        {'id': 1, 'e_m': 0.090996, 'e_o_k': [0.051897, 0.043449, 0.039937, 0.046709], 'p_i': 20, 'u_i': 3.8665, 'theta': 0.9084},
        {'id': 2, 'e_m': 8.579928, 'e_o_k': [0.048283, 0.072029], 'p_i': 40, 'u_i': 3.7946, 'theta': 0.6435},
        {'id': 3, 'e_m': 3.260759, 'e_o_k': [0.582961, 0.589557], 'p_i': 10, 'u_i': 4.2567, 'theta': 0.8544},
        {'id': 4, 'e_m': 1.858953, 'e_o_k': [1.151744, 1.040332, 1.525831], 'p_i': 20, 'u_i': 3.1924, 'theta': 0.6777},
    ]
    B_BUDGET = 48.300003
    return processors, tasks, B_BUDGET
