"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.199996, "H": 80, "J": 32, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 8, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 193.199996, "H": 80, "J": 32, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 8, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [1.154210, 0.852172], 'p_i': 10, 'u_i': 2.4940, 'theta': 0.6329},
        {'id': 1, 'e_m': 2.187790, 'e_o_k': [0.455166, 0.325392], 'p_i': 20, 'u_i': 1.5900, 'theta': 0.6501},
        {'id': 2, 'e_m': 4.419293, 'e_o_k': [1.824546, 2.335269, 2.581041], 'p_i': 40, 'u_i': 1.1793, 'theta': 0.8507},
        {'id': 3, 'e_m': 18.033527, 'e_o_k': [0.092085, 0.085118, 0.122662, 0.070710], 'p_i': 80, 'u_i': 4.0815, 'theta': 0.9652},
        {'id': 4, 'e_m': 38.119519, 'e_o_k': [0.975114, 1.516701, 1.133023, 1.155522], 'p_i': 80, 'u_i': 4.1264, 'theta': 0.8618},
        {'id': 5, 'e_m': 2.177003, 'e_o_k': [2.196520], 'p_i': 10, 'u_i': 3.9514, 'theta': 0.6049},
        {'id': 6, 'e_m': 2.035103, 'e_o_k': [2.450315], 'p_i': 20, 'u_i': 2.0914, 'theta': 0.6425},
        {'id': 7, 'e_m': 5.175192, 'e_o_k': [1.383158, 2.322003], 'p_i': 20, 'u_i': 3.2074, 'theta': 0.6363},
    ]
    B_BUDGET = 193.199996
    return processors, tasks, B_BUDGET
