"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 386.400017, "H": 80, "J": 45, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 386.400017, "H": 80, "J": 45, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 4, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 5, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 6, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
        {'id': 7, 'frequencies': [0.3, 0.45, 0.55, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.941479, 'e_o_k': [0.702843, 0.650642, 0.829040, 0.703882], 'p_i': 10, 'u_i': 2.9445, 'theta': 0.7887},
        {'id': 1, 'e_m': 4.586898, 'e_o_k': [2.703698, 2.737417, 3.732681], 'p_i': 20, 'u_i': 2.8271, 'theta': 0.6512},
        {'id': 2, 'e_m': 9.102646, 'e_o_k': [1.821131], 'p_i': 40, 'u_i': 1.4029, 'theta': 0.9285},
        {'id': 3, 'e_m': 40.000000, 'e_o_k': [9.640055], 'p_i': 80, 'u_i': 1.0493, 'theta': 0.6349},
        {'id': 4, 'e_m': 18.378732, 'e_o_k': [0.207776, 0.252650, 0.267654, 0.413518], 'p_i': 80, 'u_i': 4.7125, 'theta': 0.8933},
        {'id': 5, 'e_m': 5.000000, 'e_o_k': [0.204269, 0.192498], 'p_i': 10, 'u_i': 3.2074, 'theta': 0.6363},
        {'id': 6, 'e_m': 4.622893, 'e_o_k': [0.747787, 0.867278, 0.929072], 'p_i': 20, 'u_i': 3.2392, 'theta': 0.6376},
        {'id': 7, 'e_m': 4.577242, 'e_o_k': [4.313205, 2.519818], 'p_i': 20, 'u_i': 4.7393, 'theta': 0.7989},
        {'id': 8, 'e_m': 2.326838, 'e_o_k': [2.782516], 'p_i': 10, 'u_i': 2.6465, 'theta': 0.8164},
        {'id': 9, 'e_m': 9.310225, 'e_o_k': [1.942946, 1.630683, 1.235780], 'p_i': 40, 'u_i': 2.0659, 'theta': 0.7765},
        {'id': 10, 'e_m': 20.000000, 'e_o_k': [2.677869, 2.804438], 'p_i': 40, 'u_i': 3.7243, 'theta': 0.7160},
        {'id': 11, 'e_m': 39.500860, 'e_o_k': [0.548621, 0.693378, 1.021329], 'p_i': 80, 'u_i': 3.9218, 'theta': 0.6022},
    ]
    B_BUDGET = 386.400017
    return processors, tasks, B_BUDGET
