"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1081, "set": 81, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1081, "set": 81, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.65, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.65, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.405573, 'e_o_k': [0.365903, 0.410804], 'p_i': 10, 'u_i': 1.1253, 'theta': 0.9948},
        {'id': 1, 'e_m': 7.779829, 'e_o_k': [0.869824, 1.284964, 1.016770, 1.009994, 1.330119], 'p_i': 20, 'u_i': 3.6938, 'theta': 0.7667},
        {'id': 2, 'e_m': 14.818048, 'e_o_k': [2.092532, 2.033558, 1.743740], 'p_i': 40, 'u_i': 4.4913, 'theta': 0.9359},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
