"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 8, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1081, "set": 81, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 8, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1081, "set": 81, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.65, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.65, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.159141, 'e_o_k': [1.872917], 'p_i': 10, 'u_i': 2.7135, 'theta': 0.8396},
        {'id': 1, 'e_m': 0.522727, 'e_o_k': [0.317953, 0.320882, 0.406619], 'p_i': 20, 'u_i': 4.7556, 'theta': 0.6953},
        {'id': 2, 'e_m': 14.886722, 'e_o_k': [0.583396, 0.896046, 0.789531, 0.696631, 0.946558], 'p_i': 40, 'u_i': 1.2876, 'theta': 0.7015},
        {'id': 3, 'e_m': 7.431262, 'e_o_k': [2.488955, 1.810892, 2.205416], 'p_i': 40, 'u_i': 3.5757, 'theta': 0.9515},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
