"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.859999, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1010, "set": 10, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.859999, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1010, "set": 10, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.179800, 'e_o_k': [0.461081, 0.402096, 0.366636, 0.399644, 0.478134], 'p_i': 10, 'u_i': 3.0735, 'theta': 0.8975},
        {'id': 1, 'e_m': 1.843523, 'e_o_k': [1.117068, 1.573388], 'p_i': 20, 'u_i': 1.6916, 'theta': 0.9935},
        {'id': 2, 'e_m': 1.695920, 'e_o_k': [3.391841], 'p_i': 40, 'u_i': 1.7632, 'theta': 0.7733},
        {'id': 3, 'e_m': 3.937751, 'e_o_k': [3.376111], 'p_i': 20, 'u_i': 3.8070, 'theta': 0.6252},
        {'id': 4, 'e_m': 1.011165, 'e_o_k': [2.022331], 'p_i': 20, 'u_i': 3.4172, 'theta': 0.8276},
    ]
    B_BUDGET = 41.859999
    return processors, tasks, B_BUDGET
