"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.860001, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1012, "set": 12, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.860001, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1012, "set": 12, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.45, 0.55, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.45, 0.55, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.610968, 'e_o_k': [0.336658, 0.165698, 0.196734, 0.246934, 0.275911], 'p_i': 10, 'u_i': 4.5368, 'theta': 0.8241},
        {'id': 1, 'e_m': 2.632557, 'e_o_k': [3.491265, 1.773849], 'p_i': 20, 'u_i': 2.1438, 'theta': 0.6432},
        {'id': 2, 'e_m': 3.771595, 'e_o_k': [0.602389, 0.800761], 'p_i': 40, 'u_i': 4.8131, 'theta': 0.9604},
        {'id': 3, 'e_m': 2.222436, 'e_o_k': [1.294376], 'p_i': 20, 'u_i': 3.0442, 'theta': 0.6902},
        {'id': 4, 'e_m': 4.037274, 'e_o_k': [0.832044, 0.939227, 0.765032, 0.955226, 0.803536], 'p_i': 20, 'u_i': 3.6043, 'theta': 0.9673},
    ]
    B_BUDGET = 41.860001
    return processors, tasks, B_BUDGET
