"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 28, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1054, "set": 54, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 28, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1054, "set": 54, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.364024, 'e_o_k': [0.034077, 0.028868, 0.046476], 'p_i': 10, 'u_i': 4.3896, 'theta': 0.9408},
        {'id': 1, 'e_m': 0.611646, 'e_o_k': [0.304020, 0.403490], 'p_i': 20, 'u_i': 4.8484, 'theta': 0.7101},
        {'id': 2, 'e_m': 1.075111, 'e_o_k': [0.690757, 0.724353, 0.735112], 'p_i': 40, 'u_i': 4.4434, 'theta': 0.8054},
        {'id': 3, 'e_m': 0.890382, 'e_o_k': [0.043610], 'p_i': 10, 'u_i': 1.8318, 'theta': 0.7415},
        {'id': 4, 'e_m': 2.068971, 'e_o_k': [0.272392, 0.268984, 0.321937], 'p_i': 20, 'u_i': 2.0832, 'theta': 0.8712},
        {'id': 5, 'e_m': 5.899442, 'e_o_k': [0.731129, 1.130797, 0.861093], 'p_i': 20, 'u_i': 1.5203, 'theta': 0.9242},
        {'id': 6, 'e_m': 1.690676, 'e_o_k': [1.127122, 1.312697], 'p_i': 40, 'u_i': 3.6014, 'theta': 0.9031},
        {'id': 7, 'e_m': 0.158503, 'e_o_k': [0.317007], 'p_i': 40, 'u_i': 4.0067, 'theta': 0.6694},
        {'id': 8, 'e_m': 0.922141, 'e_o_k': [1.560281], 'p_i': 20, 'u_i': 3.0771, 'theta': 0.7500},
        {'id': 9, 'e_m': 1.503107, 'e_o_k': [0.269908, 0.176087], 'p_i': 40, 'u_i': 1.1324, 'theta': 0.7545},
        {'id': 10, 'e_m': 0.000588, 'e_o_k': [0.000435, 0.000742], 'p_i': 10, 'u_i': 1.7968, 'theta': 0.6374},
        {'id': 11, 'e_m': 1.887057, 'e_o_k': [0.179870, 0.227748, 0.172852], 'p_i': 10, 'u_i': 2.0797, 'theta': 0.6434},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
