"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 12, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1081, "set": 81, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 12, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1081, "set": 81, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.65, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.65, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.642834, 'e_o_k': [0.324838, 0.271884, 0.318246, 0.263165], 'p_i': 10, 'u_i': 2.5114, 'theta': 0.9756},
        {'id': 1, 'e_m': 1.779173, 'e_o_k': [0.101109, 0.129138], 'p_i': 20, 'u_i': 4.1867, 'theta': 0.6127},
        {'id': 2, 'e_m': 12.262845, 'e_o_k': [0.656768, 0.636879, 0.749488], 'p_i': 40, 'u_i': 3.5154, 'theta': 0.7168},
        {'id': 3, 'e_m': 13.461438, 'e_o_k': [1.652725, 1.381719, 1.457328], 'p_i': 40, 'u_i': 1.1007, 'theta': 0.8253},
        {'id': 4, 'e_m': 1.036508, 'e_o_k': [0.326419, 0.955697, 0.790901], 'p_i': 10, 'u_i': 1.7556, 'theta': 0.7768},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
