"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 70.840008, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1038, "set": 38, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 70.840008, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1038, "set": 38, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.5, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.5, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.077186, 'e_o_k': [0.394468, 0.351311, 0.329782], 'p_i': 10, 'u_i': 4.4301, 'theta': 0.6951},
        {'id': 1, 'e_m': 1.599098, 'e_o_k': [1.219988, 0.984785, 0.950219], 'p_i': 20, 'u_i': 2.0617, 'theta': 0.7900},
        {'id': 2, 'e_m': 0.425219, 'e_o_k': [1.443228, 1.531867, 1.036801], 'p_i': 40, 'u_i': 4.8781, 'theta': 0.7009},
        {'id': 3, 'e_m': 2.174965, 'e_o_k': [1.357174, 0.992745, 1.722691, 1.257237], 'p_i': 80, 'u_i': 4.1678, 'theta': 0.8559},
        {'id': 4, 'e_m': 0.085600, 'e_o_k': [2.822626, 2.202751, 2.853832], 'p_i': 80, 'u_i': 4.1702, 'theta': 0.7607},
        {'id': 5, 'e_m': 0.066694, 'e_o_k': [1.182972], 'p_i': 10, 'u_i': 3.6911, 'theta': 0.7236},
        {'id': 6, 'e_m': 2.369699, 'e_o_k': [5.975292], 'p_i': 80, 'u_i': 4.5612, 'theta': 0.9814},
        {'id': 7, 'e_m': 2.971871, 'e_o_k': [14.103633], 'p_i': 80, 'u_i': 4.0267, 'theta': 0.6963},
    ]
    B_BUDGET = 70.840008
    return processors, tasks, B_BUDGET
