"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 386.399995, "H": 80, "J": 43, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1092, "set": 92, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 386.399995, "H": 80, "J": 43, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1092, "set": 92, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 4, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 5, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 6, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 7, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.428025, 'e_o_k': [0.124418, 0.188661], 'p_i': 10, 'u_i': 4.4838, 'theta': 0.9240},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [0.058132, 0.034355, 0.049660], 'p_i': 20, 'u_i': 4.0627, 'theta': 0.6868},
        {'id': 2, 'e_m': 9.717022, 'e_o_k': [0.626825, 0.751442], 'p_i': 40, 'u_i': 2.6872, 'theta': 0.9768},
        {'id': 3, 'e_m': 29.881570, 'e_o_k': [2.311456, 2.688832, 2.832212, 3.139848], 'p_i': 80, 'u_i': 3.6018, 'theta': 0.8430},
        {'id': 4, 'e_m': 9.797926, 'e_o_k': [1.147565, 1.140817], 'p_i': 40, 'u_i': 3.7334, 'theta': 0.9857},
        {'id': 5, 'e_m': 13.708656, 'e_o_k': [0.748658, 0.567979, 0.635207, 0.634239], 'p_i': 40, 'u_i': 2.1947, 'theta': 0.9324},
        {'id': 6, 'e_m': 5.000000, 'e_o_k': [2.217644, 1.661781], 'p_i': 10, 'u_i': 2.0143, 'theta': 0.6505},
        {'id': 7, 'e_m': 27.928776, 'e_o_k': [43.268769], 'p_i': 80, 'u_i': 2.1824, 'theta': 0.8652},
        {'id': 8, 'e_m': 3.122122, 'e_o_k': [1.091664, 1.179844], 'p_i': 10, 'u_i': 4.6080, 'theta': 0.8330},
        {'id': 9, 'e_m': 9.787883, 'e_o_k': [2.449593], 'p_i': 40, 'u_i': 3.7352, 'theta': 0.6819},
        {'id': 10, 'e_m': 19.071070, 'e_o_k': [0.207136, 0.252147, 0.169234, 0.200800], 'p_i': 80, 'u_i': 4.2749, 'theta': 0.7104},
        {'id': 11, 'e_m': 8.173608, 'e_o_k': [3.115070, 2.964943, 2.731044], 'p_i': 20, 'u_i': 1.3924, 'theta': 0.6044},
    ]
    B_BUDGET = 386.399995
    return processors, tasks, B_BUDGET
