"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 9, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1052, "set": 52, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 9, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1052, "set": 52, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.55, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.55, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.306383, 'e_o_k': [0.663134, 0.453427], 'p_i': 10, 'u_i': 2.1441, 'theta': 0.8702},
        {'id': 1, 'e_m': 7.523173, 'e_o_k': [1.676275], 'p_i': 20, 'u_i': 1.6290, 'theta': 0.8832},
        {'id': 2, 'e_m': 8.105723, 'e_o_k': [0.770235, 0.619760], 'p_i': 40, 'u_i': 2.0372, 'theta': 0.9082},
        {'id': 3, 'e_m': 3.811200, 'e_o_k': [5.395606], 'p_i': 20, 'u_i': 4.3946, 'theta': 0.8650},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
