"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 27, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1052, "set": 52, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 27, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1052, "set": 52, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.55, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.55, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.807884, 'e_o_k': [0.150296, 0.180473, 0.194660], 'p_i': 10, 'u_i': 4.3441, 'theta': 0.9984},
        {'id': 1, 'e_m': 1.084119, 'e_o_k': [0.647687, 0.527662, 0.672177], 'p_i': 20, 'u_i': 4.2241, 'theta': 0.7400},
        {'id': 2, 'e_m': 0.593738, 'e_o_k': [0.350612, 0.332704], 'p_i': 40, 'u_i': 1.0107, 'theta': 0.7682},
        {'id': 3, 'e_m': 3.135141, 'e_o_k': [0.889630], 'p_i': 20, 'u_i': 3.2541, 'theta': 0.7886},
        {'id': 4, 'e_m': 0.723642, 'e_o_k': [1.447285], 'p_i': 20, 'u_i': 3.0204, 'theta': 0.7169},
        {'id': 5, 'e_m': 0.997263, 'e_o_k': [0.043757, 0.038420], 'p_i': 10, 'u_i': 1.1836, 'theta': 0.9860},
        {'id': 6, 'e_m': 2.686339, 'e_o_k': [3.650891], 'p_i': 20, 'u_i': 2.9730, 'theta': 0.8756},
        {'id': 7, 'e_m': 1.543972, 'e_o_k': [0.028394], 'p_i': 10, 'u_i': 1.9389, 'theta': 0.8113},
        {'id': 8, 'e_m': 0.825401, 'e_o_k': [0.006950, 0.008483, 0.004594], 'p_i': 20, 'u_i': 2.2285, 'theta': 0.9951},
        {'id': 9, 'e_m': 2.275125, 'e_o_k': [0.265492], 'p_i': 10, 'u_i': 4.4721, 'theta': 0.9160},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
