"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599999, "H": 80, "J": 19, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1096, "set": 96, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}
"""

_SPEC = '{"B": 96.599999, "H": 80, "J": 19, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1096, "set": 96, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.65, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.65, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [1.755476], 'p_i': 10, 'u_i': 3.6032, 'theta': 0.7280},
        {'id': 1, 'e_m': 2.005299, 'e_o_k': [0.282752, 0.305613, 0.257752, 0.285198], 'p_i': 20, 'u_i': 1.8410, 'theta': 0.6679},
        {'id': 2, 'e_m': 3.792486, 'e_o_k': [1.042223, 2.146069, 1.237026], 'p_i': 40, 'u_i': 4.6914, 'theta': 0.7906},
        {'id': 3, 'e_m': 7.594187, 'e_o_k': [2.943050, 3.823348], 'p_i': 80, 'u_i': 4.8426, 'theta': 0.7607},
        {'id': 4, 'e_m': 4.694391, 'e_o_k': [2.126797], 'p_i': 40, 'u_i': 3.1382, 'theta': 0.7191},
        {'id': 5, 'e_m': 3.705431, 'e_o_k': [0.359778, 0.420374], 'p_i': 40, 'u_i': 4.9005, 'theta': 0.9755},
    ]
    B_BUDGET = 96.599999
    return processors, tasks, B_BUDGET
