"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 109.480002, "H": 80, "J": 20, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1079, "set": 79, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 109.480002, "H": 80, "J": 20, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1079, "set": 79, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.456462, 'e_o_k': [0.013257, 0.011107, 0.010770], 'p_i': 10, 'u_i': 4.7732, 'theta': 0.9139},
        {'id': 1, 'e_m': 3.266889, 'e_o_k': [0.069765, 0.063306, 0.064548, 0.051004], 'p_i': 20, 'u_i': 3.8173, 'theta': 0.8021},
        {'id': 2, 'e_m': 14.235705, 'e_o_k': [4.489438], 'p_i': 40, 'u_i': 1.9011, 'theta': 0.9663},
        {'id': 3, 'e_m': 17.358865, 'e_o_k': [0.842542, 0.656915], 'p_i': 80, 'u_i': 2.3921, 'theta': 0.8427},
        {'id': 4, 'e_m': 1.564714, 'e_o_k': [0.159907, 0.175026, 0.227109, 0.165982], 'p_i': 80, 'u_i': 3.1766, 'theta': 0.8058},
        {'id': 5, 'e_m': 27.367214, 'e_o_k': [1.355306, 1.330938, 2.067736, 1.547286], 'p_i': 80, 'u_i': 3.9794, 'theta': 0.6813},
        {'id': 6, 'e_m': 6.204640, 'e_o_k': [2.499141], 'p_i': 40, 'u_i': 2.1553, 'theta': 0.9094},
        {'id': 7, 'e_m': 0.109266, 'e_o_k': [0.046379, 0.074916, 0.045240, 0.051997], 'p_i': 80, 'u_i': 2.6541, 'theta': 0.6242},
    ]
    B_BUDGET = 109.480002
    return processors, tasks, B_BUDGET
