"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 83.720006, "H": 80, "J": 36, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 83.720006, "H": 80, "J": 36, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.55, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.55, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.585825, 'e_o_k': [0.796381], 'p_i': 10, 'u_i': 1.8620, 'theta': 0.7301},
        {'id': 1, 'e_m': 1.420968, 'e_o_k': [1.701478], 'p_i': 20, 'u_i': 2.5370, 'theta': 0.9227},
        {'id': 2, 'e_m': 2.142035, 'e_o_k': [0.546669, 0.800598, 0.577601], 'p_i': 40, 'u_i': 3.1495, 'theta': 0.9269},
        {'id': 3, 'e_m': 17.219577, 'e_o_k': [12.300136], 'p_i': 80, 'u_i': 2.3975, 'theta': 0.7186},
        {'id': 4, 'e_m': 0.753571, 'e_o_k': [1.156552], 'p_i': 10, 'u_i': 4.4871, 'theta': 0.8862},
        {'id': 5, 'e_m': 1.009126, 'e_o_k': [0.426572, 0.509095, 0.429347, 0.653238], 'p_i': 10, 'u_i': 4.7408, 'theta': 0.8630},
        {'id': 6, 'e_m': 0.413891, 'e_o_k': [0.089662, 0.044649], 'p_i': 20, 'u_i': 2.4424, 'theta': 0.7445},
        {'id': 7, 'e_m': 0.368747, 'e_o_k': [0.258873, 0.273803, 0.204817], 'p_i': 80, 'u_i': 2.5244, 'theta': 0.6476},
    ]
    B_BUDGET = 83.720006
    return processors, tasks, B_BUDGET
