"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 70.84001, "H": 80, "J": 36, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 70.84001, "H": 80, "J": 36, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.55, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.55, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.976375, 'e_o_k': [0.113769], 'p_i': 10, 'u_i': 1.8620, 'theta': 0.7301},
        {'id': 1, 'e_m': 2.368279, 'e_o_k': [0.243068], 'p_i': 20, 'u_i': 2.5370, 'theta': 0.9227},
        {'id': 2, 'e_m': 3.570058, 'e_o_k': [0.078096, 0.114371, 0.082514], 'p_i': 40, 'u_i': 3.1495, 'theta': 0.9269},
        {'id': 3, 'e_m': 28.699295, 'e_o_k': [1.035504], 'p_i': 80, 'u_i': 2.3975, 'theta': 0.7186},
        {'id': 4, 'e_m': 1.255951, 'e_o_k': [0.165222], 'p_i': 10, 'u_i': 4.4871, 'theta': 0.8862},
        {'id': 5, 'e_m': 1.681877, 'e_o_k': [0.068281, 0.081490, 0.068725, 0.104563], 'p_i': 10, 'u_i': 4.7408, 'theta': 0.8630},
        {'id': 6, 'e_m': 0.689818, 'e_o_k': [0.012809, 0.006378], 'p_i': 20, 'u_i': 2.4424, 'theta': 0.7445},
        {'id': 7, 'e_m': 0.614578, 'e_o_k': [0.192753, 0.203869, 0.152504], 'p_i': 80, 'u_i': 2.5244, 'theta': 0.6476},
    ]
    B_BUDGET = 70.840010
    return processors, tasks, B_BUDGET
