"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 386.399992, "H": 80, "J": 52, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1082, "set": 82, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 386.399992, "H": 80, "J": 52, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1082, "set": 82, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 4, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 5, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 6, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 7, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.815927, 'e_o_k': [0.282055, 0.281779, 0.212378], 'p_i': 10, 'u_i': 4.9868, 'theta': 0.6826},
        {'id': 1, 'e_m': 5.607491, 'e_o_k': [1.979773], 'p_i': 20, 'u_i': 2.4106, 'theta': 0.7374},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [4.700974, 4.430394], 'p_i': 40, 'u_i': 1.8119, 'theta': 0.8001},
        {'id': 3, 'e_m': 22.289207, 'e_o_k': [0.005246, 0.005340, 0.004394, 0.005326], 'p_i': 80, 'u_i': 3.3146, 'theta': 0.8934},
        {'id': 4, 'e_m': 13.478789, 'e_o_k': [0.541298, 0.572515, 0.441643, 0.587984], 'p_i': 40, 'u_i': 4.6347, 'theta': 0.7406},
        {'id': 5, 'e_m': 20.000000, 'e_o_k': [2.123660, 1.724362, 1.646240], 'p_i': 40, 'u_i': 2.0303, 'theta': 0.8167},
        {'id': 6, 'e_m': 4.127309, 'e_o_k': [0.715725, 0.716369, 0.619769, 0.636600], 'p_i': 10, 'u_i': 4.4766, 'theta': 0.7542},
        {'id': 7, 'e_m': 2.985791, 'e_o_k': [1.220466, 1.486474, 1.480474, 1.784168], 'p_i': 10, 'u_i': 2.3546, 'theta': 0.8816},
        {'id': 8, 'e_m': 22.130386, 'e_o_k': [11.060034, 7.450555], 'p_i': 80, 'u_i': 4.7708, 'theta': 0.9279},
        {'id': 9, 'e_m': 5.512624, 'e_o_k': [3.048828], 'p_i': 20, 'u_i': 1.0541, 'theta': 0.6922},
        {'id': 10, 'e_m': 2.797847, 'e_o_k': [0.142043, 0.172172, 0.220633, 0.197132], 'p_i': 10, 'u_i': 1.9965, 'theta': 0.9810},
        {'id': 11, 'e_m': 5.581844, 'e_o_k': [0.574061, 0.448629, 0.594974], 'p_i': 20, 'u_i': 4.4548, 'theta': 0.9895},
    ]
    B_BUDGET = 386.399992
    return processors, tasks, B_BUDGET
