"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600001, "H": 80, "J": 21, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1062, "set": 62, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 96.600001, "H": 80, "J": 21, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1062, "set": 62, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.218437, 'e_o_k': [0.164620, 0.107726, 0.164528], 'p_i': 10, 'u_i': 1.2397, 'theta': 0.9612},
        {'id': 1, 'e_m': 2.004014, 'e_o_k': [0.075012, 0.073715, 0.108441], 'p_i': 20, 'u_i': 1.4615, 'theta': 0.7047},
        {'id': 2, 'e_m': 6.719005, 'e_o_k': [1.237034, 1.176671], 'p_i': 40, 'u_i': 1.6788, 'theta': 0.9346},
        {'id': 3, 'e_m': 5.254675, 'e_o_k': [1.477455, 1.522222, 2.750861, 1.724330], 'p_i': 80, 'u_i': 2.2859, 'theta': 0.7225},
        {'id': 4, 'e_m': 3.973246, 'e_o_k': [0.187599, 0.280772, 0.382994, 0.308389], 'p_i': 80, 'u_i': 2.9068, 'theta': 0.8722},
        {'id': 5, 'e_m': 15.973434, 'e_o_k': [9.744401], 'p_i': 40, 'u_i': 1.7526, 'theta': 0.9399},
        {'id': 6, 'e_m': 7.722438, 'e_o_k': [0.288022, 0.312117, 0.217953, 0.265885], 'p_i': 40, 'u_i': 3.8639, 'theta': 0.7061},
        {'id': 7, 'e_m': 0.178774, 'e_o_k': [0.074002, 0.100323, 0.123932, 0.059291], 'p_i': 80, 'u_i': 2.5195, 'theta': 0.7993},
    ]
    B_BUDGET = 96.600001
    return processors, tasks, B_BUDGET
