"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300004, "H": 40, "J": 11, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.300004, "H": 40, "J": 11, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.198085, 'e_o_k': [0.181988, 0.214182], 'p_i': 10, 'u_i': 2.2836, 'theta': 0.6704},
        {'id': 1, 'e_m': 3.494628, 'e_o_k': [1.430872], 'p_i': 20, 'u_i': 3.2500, 'theta': 0.6125},
        {'id': 2, 'e_m': 17.406136, 'e_o_k': [1.746455], 'p_i': 40, 'u_i': 2.4255, 'theta': 0.6347},
        {'id': 3, 'e_m': 2.623764, 'e_o_k': [0.516602, 0.760157, 0.926656], 'p_i': 20, 'u_i': 2.4760, 'theta': 0.6602},
        {'id': 4, 'e_m': 4.782371, 'e_o_k': [2.661773, 2.038374], 'p_i': 20, 'u_i': 4.0552, 'theta': 0.6304},
    ]
    B_BUDGET = 48.300004
    return processors, tasks, B_BUDGET
