"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 54.739998, "H": 40, "J": 15, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1036, "set": 36, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 54.739998, "H": 40, "J": 15, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1036, "set": 36, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.8, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.8, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.102937, 'e_o_k': [1.291975], 'p_i': 10, 'u_i': 3.3226, 'theta': 0.9404},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [0.680953], 'p_i': 20, 'u_i': 1.7011, 'theta': 0.8822},
        {'id': 2, 'e_m': 9.162300, 'e_o_k': [0.576643], 'p_i': 40, 'u_i': 1.6172, 'theta': 0.6038},
        {'id': 3, 'e_m': 1.505697, 'e_o_k': [0.914943], 'p_i': 10, 'u_i': 2.0614, 'theta': 0.7133},
        {'id': 4, 'e_m': 2.100791, 'e_o_k': [0.117258, 0.191186], 'p_i': 10, 'u_i': 4.2070, 'theta': 0.8174},
    ]
    B_BUDGET = 54.739998
    return processors, tasks, B_BUDGET
