"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 115.919986, "H": 80, "J": 36, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 115.919986, "H": 80, "J": 36, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.113804], 'p_i': 10, 'u_i': 4.4219, 'theta': 0.9759},
        {'id': 1, 'e_m': 1.626821, 'e_o_k': [0.174288, 0.242349, 0.135014], 'p_i': 20, 'u_i': 3.1574, 'theta': 0.8277},
        {'id': 2, 'e_m': 8.553711, 'e_o_k': [0.104408, 0.112420, 0.101151], 'p_i': 40, 'u_i': 4.2592, 'theta': 0.7037},
        {'id': 3, 'e_m': 38.419092, 'e_o_k': [0.949533, 1.027052], 'p_i': 80, 'u_i': 4.9113, 'theta': 0.9713},
        {'id': 4, 'e_m': 1.609618, 'e_o_k': [1.625026], 'p_i': 20, 'u_i': 1.5378, 'theta': 0.9042},
        {'id': 5, 'e_m': 0.762875, 'e_o_k': [0.038980, 0.040925, 0.039421], 'p_i': 10, 'u_i': 4.8305, 'theta': 0.9289},
        {'id': 6, 'e_m': 0.847425, 'e_o_k': [0.076699, 0.063839], 'p_i': 10, 'u_i': 3.4664, 'theta': 0.6230},
        {'id': 7, 'e_m': 6.645327, 'e_o_k': [0.520151, 0.443147, 0.371007, 0.357086], 'p_i': 80, 'u_i': 1.2223, 'theta': 0.7125},
    ]
    B_BUDGET = 115.919986
    return processors, tasks, B_BUDGET
