"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 61.179996, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1099, "set": 99, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 61.179996, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1099, "set": 99, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.45, 0.5, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.45, 0.5, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.550497, 'e_o_k': [0.049252, 0.048559], 'p_i': 10, 'u_i': 2.2433, 'theta': 0.7902},
        {'id': 1, 'e_m': 3.431187, 'e_o_k': [0.693884, 0.382816], 'p_i': 20, 'u_i': 1.5674, 'theta': 0.9816},
        {'id': 2, 'e_m': 6.935637, 'e_o_k': [0.100202, 0.078249, 0.082574], 'p_i': 40, 'u_i': 4.2083, 'theta': 0.6844},
        {'id': 3, 'e_m': 5.000000, 'e_o_k': [0.110191, 0.138393], 'p_i': 10, 'u_i': 2.0672, 'theta': 0.9097},
        {'id': 4, 'e_m': 20.000000, 'e_o_k': [0.062065, 0.064963, 0.072963], 'p_i': 40, 'u_i': 4.2137, 'theta': 0.7881},
    ]
    B_BUDGET = 61.179996
    return processors, tasks, B_BUDGET
