"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 51.519998, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1010, "set": 10, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 51.519998, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1010, "set": 10, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.359600, 'e_o_k': [0.119585, 0.104287, 0.095090], 'p_i': 10, 'u_i': 3.0744, 'theta': 0.6057},
        {'id': 1, 'e_m': 3.687046, 'e_o_k': [0.477609, 0.499576, 0.560218], 'p_i': 20, 'u_i': 3.8278, 'theta': 0.6593},
        {'id': 2, 'e_m': 3.391841, 'e_o_k': [1.134283, 1.006024, 1.390907], 'p_i': 40, 'u_i': 4.5630, 'theta': 0.6102},
        {'id': 3, 'e_m': 7.875502, 'e_o_k': [0.006215, 0.008188], 'p_i': 20, 'u_i': 4.8320, 'theta': 0.8520},
        {'id': 4, 'e_m': 2.022331, 'e_o_k': [1.400073, 1.438958, 1.205631], 'p_i': 20, 'u_i': 3.4172, 'theta': 0.8276},
    ]
    B_BUDGET = 51.519998
    return processors, tasks, B_BUDGET
