"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 23, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1008, "set": 8, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 23, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1008, "set": 8, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.55, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.55, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.343019, 'e_o_k': [0.288284, 0.375728, 0.354778, 0.269802, 0.257104], 'p_i': 10, 'u_i': 1.1912, 'theta': 0.8003},
        {'id': 1, 'e_m': 0.308567, 'e_o_k': [0.187813, 0.153237, 0.154945, 0.121139], 'p_i': 20, 'u_i': 4.0801, 'theta': 0.7942},
        {'id': 2, 'e_m': 3.031755, 'e_o_k': [0.447733, 0.470616, 0.575035, 0.579864], 'p_i': 40, 'u_i': 1.4523, 'theta': 0.8191},
        {'id': 3, 'e_m': 3.938392, 'e_o_k': [0.526671, 0.483790, 0.528564, 0.541516], 'p_i': 40, 'u_i': 2.7276, 'theta': 0.8533},
        {'id': 4, 'e_m': 4.565329, 'e_o_k': [0.142254, 0.129951], 'p_i': 40, 'u_i': 2.1600, 'theta': 0.6405},
        {'id': 5, 'e_m': 1.496842, 'e_o_k': [0.124982, 0.197027], 'p_i': 10, 'u_i': 2.6477, 'theta': 0.6090},
        {'id': 6, 'e_m': 2.733018, 'e_o_k': [0.227686, 0.281760, 0.268173, 0.270554, 0.245382], 'p_i': 40, 'u_i': 4.6489, 'theta': 0.9830},
        {'id': 7, 'e_m': 2.490805, 'e_o_k': [0.495861, 0.347154, 0.443427, 0.472819], 'p_i': 40, 'u_i': 3.8154, 'theta': 0.9944},
        {'id': 8, 'e_m': 0.316044, 'e_o_k': [0.016912, 0.023417, 0.008645], 'p_i': 10, 'u_i': 3.0197, 'theta': 0.6590},
        {'id': 9, 'e_m': 0.817015, 'e_o_k': [0.443736, 0.361422, 0.494617, 0.334254], 'p_i': 40, 'u_i': 1.3885, 'theta': 0.7124},
        {'id': 10, 'e_m': 0.078812, 'e_o_k': [0.056170, 0.047206, 0.054250], 'p_i': 20, 'u_i': 1.1726, 'theta': 0.9660},
        {'id': 11, 'e_m': 1.025309, 'e_o_k': [0.367520, 0.381347, 0.203480, 0.362984, 0.355591], 'p_i': 40, 'u_i': 4.3541, 'theta': 0.6028},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
