"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.200002, "H": 80, "J": 30, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 8, "rho": 0.7, "seed": 1072, "set": 72, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 193.200002, "H": 80, "J": 30, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 8, "rho": 0.7, "seed": 1072, "set": 72, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.6, 0.65, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.6, 0.65, 0.95, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.6, 0.65, 0.95, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.6, 0.65, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.584871, 'e_o_k': [0.367094, 0.832882, 0.489474, 0.718073], 'p_i': 10, 'u_i': 1.9966, 'theta': 0.9591},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [3.080339], 'p_i': 20, 'u_i': 2.6358, 'theta': 0.9042},
        {'id': 2, 'e_m': 6.257448, 'e_o_k': [0.704695, 0.920324, 0.839975, 1.184228], 'p_i': 40, 'u_i': 4.8190, 'theta': 0.8812},
        {'id': 3, 'e_m': 8.747862, 'e_o_k': [0.061078, 0.053030, 0.055987, 0.063554], 'p_i': 80, 'u_i': 1.4696, 'theta': 0.7758},
        {'id': 4, 'e_m': 4.504785, 'e_o_k': [1.702787, 2.236371, 0.754797], 'p_i': 40, 'u_i': 2.7309, 'theta': 0.7465},
        {'id': 5, 'e_m': 2.688303, 'e_o_k': [3.046157], 'p_i': 20, 'u_i': 1.0675, 'theta': 0.8349},
        {'id': 6, 'e_m': 1.131333, 'e_o_k': [0.457966, 0.373768], 'p_i': 10, 'u_i': 3.5007, 'theta': 0.7762},
        {'id': 7, 'e_m': 33.244832, 'e_o_k': [6.832806, 5.827149], 'p_i': 80, 'u_i': 4.6492, 'theta': 0.7074},
    ]
    B_BUDGET = 193.200002
    return processors, tasks, B_BUDGET
