"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300004, "H": 40, "J": 13, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}
"""

_SPEC = '{"B": 48.300004, "H": 40, "J": 13, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 6, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.671636, 'e_o_k': [0.370036], 'p_i': 10, 'u_i': 3.2500, 'theta': 0.6125},
        {'id': 1, 'e_m': 1.518103, 'e_o_k': [2.453975], 'p_i': 20, 'u_i': 2.4255, 'theta': 0.6347},
        {'id': 2, 'e_m': 3.242776, 'e_o_k': [0.647410, 0.952635, 1.161293], 'p_i': 40, 'u_i': 2.4760, 'theta': 0.6602},
        {'id': 3, 'e_m': 1.308925, 'e_o_k': [0.514695, 0.394151], 'p_i': 10, 'u_i': 4.0552, 'theta': 0.6304},
        {'id': 4, 'e_m': 3.222163, 'e_o_k': [1.349373, 0.893629, 1.647075], 'p_i': 40, 'u_i': 3.1592, 'theta': 0.8862},
        {'id': 5, 'e_m': 14.576612, 'e_o_k': [1.498253, 1.826858], 'p_i': 40, 'u_i': 2.9798, 'theta': 0.9677},
    ]
    B_BUDGET = 48.300004
    return processors, tasks, B_BUDGET
