"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 25, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 25, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.258877, 'e_o_k': [0.142521], 'p_i': 10, 'u_i': 4.8474, 'theta': 0.8962},
        {'id': 1, 'e_m': 0.812723, 'e_o_k': [0.952404], 'p_i': 20, 'u_i': 3.1592, 'theta': 0.8862},
        {'id': 2, 'e_m': 2.929621, 'e_o_k': [1.879175, 2.291326], 'p_i': 40, 'u_i': 2.9798, 'theta': 0.9677},
        {'id': 3, 'e_m': 0.583694, 'e_o_k': [0.043263, 0.052489, 0.039198], 'p_i': 10, 'u_i': 4.4850, 'theta': 0.9217},
        {'id': 4, 'e_m': 2.143349, 'e_o_k': [2.401841], 'p_i': 40, 'u_i': 2.4853, 'theta': 0.8358},
        {'id': 5, 'e_m': 5.165535, 'e_o_k': [0.771618, 0.764115, 0.585856], 'p_i': 40, 'u_i': 1.4687, 'theta': 0.6458},
        {'id': 6, 'e_m': 1.816992, 'e_o_k': [0.111525], 'p_i': 10, 'u_i': 2.9303, 'theta': 0.6285},
        {'id': 7, 'e_m': 1.763078, 'e_o_k': [0.037126, 0.061544, 0.058944], 'p_i': 10, 'u_i': 3.4732, 'theta': 0.7872},
        {'id': 8, 'e_m': 1.875596, 'e_o_k': [0.248551, 0.294099, 0.363534], 'p_i': 40, 'u_i': 2.1887, 'theta': 0.6342},
        {'id': 9, 'e_m': 4.011754, 'e_o_k': [1.065770, 1.229191, 1.268671], 'p_i': 40, 'u_i': 2.9013, 'theta': 0.8957},
        {'id': 10, 'e_m': 0.097784, 'e_o_k': [0.056144, 0.057276, 0.082149], 'p_i': 40, 'u_i': 3.9621, 'theta': 0.7605},
        {'id': 11, 'e_m': 4.460354, 'e_o_k': [1.383965, 1.165468], 'p_i': 40, 'u_i': 2.3501, 'theta': 0.9803},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
