"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.039999, "H": 80, "J": 37, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1089, "set": 89, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.039999, "H": 80, "J": 37, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1089, "set": 89, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.6, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.433903, 'e_o_k': [0.236724], 'p_i': 10, 'u_i': 4.9804, 'theta': 0.6221},
        {'id': 1, 'e_m': 1.263983, 'e_o_k': [1.241594, 1.286373], 'p_i': 20, 'u_i': 1.1154, 'theta': 0.6447},
        {'id': 2, 'e_m': 1.711049, 'e_o_k': [3.422098], 'p_i': 40, 'u_i': 4.6054, 'theta': 0.6133},
        {'id': 3, 'e_m': 40.000000, 'e_o_k': [4.511675, 4.973830], 'p_i': 80, 'u_i': 3.8735, 'theta': 0.6595},
        {'id': 4, 'e_m': 13.844047, 'e_o_k': [0.024457], 'p_i': 40, 'u_i': 3.9486, 'theta': 0.6047},
        {'id': 5, 'e_m': 0.792949, 'e_o_k': [0.053374, 0.056728, 0.050295], 'p_i': 20, 'u_i': 1.6386, 'theta': 0.6711},
        {'id': 6, 'e_m': 1.263385, 'e_o_k': [0.121726], 'p_i': 10, 'u_i': 2.5502, 'theta': 0.9518},
        {'id': 7, 'e_m': 0.385472, 'e_o_k': [0.125186, 0.124855], 'p_i': 10, 'u_i': 3.5073, 'theta': 0.8946},
    ]
    B_BUDGET = 103.039999
    return processors, tasks, B_BUDGET
