"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599999, "H": 80, "J": 20, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1097, "set": 97, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 96.599999, "H": 80, "J": 20, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1097, "set": 97, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.55, 0.6, 0.65, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.55, 0.6, 0.65, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.217312, 'e_o_k': [0.008422, 0.006803, 0.011688], 'p_i': 10, 'u_i': 1.1208, 'theta': 0.8162},
        {'id': 1, 'e_m': 5.408082, 'e_o_k': [2.126066, 1.148559], 'p_i': 20, 'u_i': 4.2918, 'theta': 0.7354},
        {'id': 2, 'e_m': 3.229465, 'e_o_k': [0.417043, 0.366847, 0.325692, 0.263499], 'p_i': 40, 'u_i': 4.3275, 'theta': 0.9305},
        {'id': 3, 'e_m': 12.163783, 'e_o_k': [0.316512, 0.230098, 0.204584, 0.389584], 'p_i': 80, 'u_i': 1.1240, 'theta': 0.9698},
        {'id': 4, 'e_m': 5.659287, 'e_o_k': [2.994816, 2.516507, 2.981593, 2.825657], 'p_i': 80, 'u_i': 2.1650, 'theta': 0.7070},
        {'id': 5, 'e_m': 4.310138, 'e_o_k': [0.593693, 0.776735, 0.705021], 'p_i': 40, 'u_i': 4.0198, 'theta': 0.9249},
        {'id': 6, 'e_m': 22.845285, 'e_o_k': [2.234116, 1.716295, 1.616129], 'p_i': 80, 'u_i': 3.2939, 'theta': 0.8934},
        {'id': 7, 'e_m': 0.881620, 'e_o_k': [0.653867, 0.553779, 0.555593], 'p_i': 80, 'u_i': 2.8069, 'theta': 0.7287},
    ]
    B_BUDGET = 96.599999
    return processors, tasks, B_BUDGET
