"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.04, "H": 80, "J": 31, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1043, "set": 43, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.04, "H": 80, "J": 31, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1043, "set": 43, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.55, 0.65, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.55, 0.65, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.455631, 'e_o_k': [0.385080, 0.367966], 'p_i': 10, 'u_i': 1.2704, 'theta': 0.8987},
        {'id': 1, 'e_m': 4.999992, 'e_o_k': [0.180788, 0.148896, 0.170389], 'p_i': 20, 'u_i': 1.2546, 'theta': 0.9973},
        {'id': 2, 'e_m': 2.131879, 'e_o_k': [1.018800, 0.786425, 0.829106], 'p_i': 40, 'u_i': 3.4531, 'theta': 0.9632},
        {'id': 3, 'e_m': 17.954206, 'e_o_k': [0.545800, 0.690036, 0.815830], 'p_i': 80, 'u_i': 4.6262, 'theta': 0.8137},
        {'id': 4, 'e_m': 3.508114, 'e_o_k': [0.044489, 0.030801], 'p_i': 10, 'u_i': 3.2398, 'theta': 0.8482},
        {'id': 5, 'e_m': 3.822401, 'e_o_k': [0.928536], 'p_i': 40, 'u_i': 3.2472, 'theta': 0.7141},
        {'id': 6, 'e_m': 4.919632, 'e_o_k': [2.670223], 'p_i': 40, 'u_i': 2.0941, 'theta': 0.8384},
        {'id': 7, 'e_m': 1.147011, 'e_o_k': [1.163218, 1.050575], 'p_i': 20, 'u_i': 2.4975, 'theta': 0.9511},
    ]
    B_BUDGET = 103.040000
    return processors, tasks, B_BUDGET
