"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.040006, "H": 80, "J": 27, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1078, "set": 78, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.6, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.040006, "H": 80, "J": 27, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1078, "set": 78, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.6, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.5, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.5, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.559216, 'e_o_k': [0.330948, 0.272138, 0.332737], 'p_i': 10, 'u_i': 4.2384, 'theta': 0.7620},
        {'id': 1, 'e_m': 1.271950, 'e_o_k': [1.352109, 1.191791], 'p_i': 20, 'u_i': 4.0320, 'theta': 0.9320},
        {'id': 2, 'e_m': 1.741762, 'e_o_k': [0.983978, 1.522706, 0.895987], 'p_i': 40, 'u_i': 3.7978, 'theta': 0.6148},
        {'id': 3, 'e_m': 20.698180, 'e_o_k': [4.516801, 5.118775], 'p_i': 80, 'u_i': 4.6871, 'theta': 0.7184},
        {'id': 4, 'e_m': 0.420670, 'e_o_k': [0.104769, 0.101857], 'p_i': 40, 'u_i': 2.3487, 'theta': 0.6617},
        {'id': 5, 'e_m': 5.531121, 'e_o_k': [2.084035, 2.459691, 2.226766, 1.810868], 'p_i': 80, 'u_i': 1.7898, 'theta': 0.9298},
        {'id': 6, 'e_m': 0.842735, 'e_o_k': [0.001637], 'p_i': 10, 'u_i': 2.9464, 'theta': 0.7688},
        {'id': 7, 'e_m': 33.142426, 'e_o_k': [4.889199], 'p_i': 80, 'u_i': 4.9388, 'theta': 0.6151},
    ]
    B_BUDGET = 103.040006
    return processors, tasks, B_BUDGET
