"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 90.159999, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1083, "set": 83, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 90.159999, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1083, "set": 83, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.5, 0.55, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.5, 0.55, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.471546, 'e_o_k': [1.345916], 'p_i': 10, 'u_i': 2.9572, 'theta': 0.6352},
        {'id': 1, 'e_m': 2.038114, 'e_o_k': [0.190293, 0.235960, 0.182990], 'p_i': 20, 'u_i': 3.6210, 'theta': 0.7624},
        {'id': 2, 'e_m': 2.803280, 'e_o_k': [1.838442, 1.685058, 2.083059], 'p_i': 40, 'u_i': 1.0463, 'theta': 0.6230},
        {'id': 3, 'e_m': 2.941431, 'e_o_k': [1.976368, 1.678183, 2.228311], 'p_i': 80, 'u_i': 3.6946, 'theta': 0.6884},
        {'id': 4, 'e_m': 0.918213, 'e_o_k': [1.057370, 0.779057], 'p_i': 20, 'u_i': 3.0916, 'theta': 0.7096},
        {'id': 5, 'e_m': 4.286725, 'e_o_k': [0.692057, 0.652830], 'p_i': 20, 'u_i': 4.2731, 'theta': 0.7395},
        {'id': 6, 'e_m': 4.212195, 'e_o_k': [0.461864, 0.617455, 0.475584], 'p_i': 80, 'u_i': 2.4720, 'theta': 0.7299},
        {'id': 7, 'e_m': 1.247617, 'e_o_k': [1.709782], 'p_i': 40, 'u_i': 2.9494, 'theta': 0.7813},
    ]
    B_BUDGET = 90.159999
    return processors, tasks, B_BUDGET
