"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 70.840005, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1083, "set": 83, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 70.840005, "H": 80, "J": 26, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1083, "set": 83, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.5, 0.55, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.5, 0.55, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.617887, 'e_o_k': [1.178583], 'p_i': 10, 'u_i': 2.9572, 'theta': 0.6352},
        {'id': 1, 'e_m': 0.509529, 'e_o_k': [0.285439, 0.353939, 0.274485], 'p_i': 20, 'u_i': 3.6210, 'theta': 0.7624},
        {'id': 2, 'e_m': 0.700820, 'e_o_k': [2.559504, 2.345961, 2.900064], 'p_i': 40, 'u_i': 1.0463, 'theta': 0.6230},
        {'id': 3, 'e_m': 0.735358, 'e_o_k': [4.553932, 3.866857, 5.134457], 'p_i': 80, 'u_i': 3.6946, 'theta': 0.6884},
        {'id': 4, 'e_m': 0.229553, 'e_o_k': [2.075373, 1.529108], 'p_i': 20, 'u_i': 3.0916, 'theta': 0.7096},
        {'id': 5, 'e_m': 1.071681, 'e_o_k': [1.012438, 0.955052], 'p_i': 20, 'u_i': 4.2731, 'theta': 0.7395},
        {'id': 6, 'e_m': 1.053049, 'e_o_k': [0.692796, 0.926182, 0.713375], 'p_i': 80, 'u_i': 2.4720, 'theta': 0.7299},
        {'id': 7, 'e_m': 0.311904, 'e_o_k': [2.564673], 'p_i': 40, 'u_i': 2.9494, 'theta': 0.7813},
    ]
    B_BUDGET = 70.840005
    return processors, tasks, B_BUDGET
