"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 45.079998, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1065, "set": 65, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 45.079998, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1065, "set": 65, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.55, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.55, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.999597, 'e_o_k': [0.271292, 0.282912], 'p_i': 10, 'u_i': 4.3114, 'theta': 0.9621},
        {'id': 1, 'e_m': 0.916981, 'e_o_k': [0.781584, 0.717565, 0.334813], 'p_i': 20, 'u_i': 2.8068, 'theta': 0.7496},
        {'id': 2, 'e_m': 8.208295, 'e_o_k': [1.424534], 'p_i': 40, 'u_i': 2.8978, 'theta': 0.9876},
        {'id': 3, 'e_m': 3.650078, 'e_o_k': [3.611175], 'p_i': 10, 'u_i': 1.3616, 'theta': 0.7374},
        {'id': 4, 'e_m': 1.679521, 'e_o_k': [1.123012], 'p_i': 20, 'u_i': 4.1589, 'theta': 0.8048},
    ]
    B_BUDGET = 45.079998
    return processors, tasks, B_BUDGET
