"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 57.960002, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1086, "set": 86, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 57.960002, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1086, "set": 86, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.6, 0.75, 0.8, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.6, 0.75, 0.8, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.861232, 'e_o_k': [0.108212, 0.117343], 'p_i': 10, 'u_i': 2.6559, 'theta': 0.7674},
        {'id': 1, 'e_m': 1.785096, 'e_o_k': [1.347633, 1.056680, 1.165879], 'p_i': 20, 'u_i': 3.3688, 'theta': 0.9146},
        {'id': 2, 'e_m': 9.425596, 'e_o_k': [5.249419], 'p_i': 40, 'u_i': 2.0974, 'theta': 0.7224},
        {'id': 3, 'e_m': 3.559285, 'e_o_k': [5.582074], 'p_i': 40, 'u_i': 2.2542, 'theta': 0.6249},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [2.492014, 2.710726, 1.360212], 'p_i': 20, 'u_i': 2.9688, 'theta': 0.6150},
    ]
    B_BUDGET = 57.960002
    return processors, tasks, B_BUDGET
