"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 38.639997, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1078, "set": 78, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 38.639997, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1078, "set": 78, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.5, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.5, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.372767, 'e_o_k': [0.271875, 0.294892, 0.178767], 'p_i': 10, 'u_i': 2.2641, 'theta': 0.8403},
        {'id': 1, 'e_m': 1.826562, 'e_o_k': [3.653123], 'p_i': 20, 'u_i': 4.5379, 'theta': 0.9717},
        {'id': 2, 'e_m': 0.568156, 'e_o_k': [0.610676, 0.599880], 'p_i': 40, 'u_i': 2.3623, 'theta': 0.7099},
        {'id': 3, 'e_m': 1.551915, 'e_o_k': [1.709439, 1.374495], 'p_i': 20, 'u_i': 4.0320, 'theta': 0.9320},
        {'id': 4, 'e_m': 3.591911, 'e_o_k': [1.214444, 1.612334, 1.248142, 1.598820, 1.492855], 'p_i': 20, 'u_i': 1.3968, 'theta': 0.9687},
    ]
    B_BUDGET = 38.639997
    return processors, tasks, B_BUDGET
