"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.860004, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1022, "set": 22, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.860004, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1022, "set": 22, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.55, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.55, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.590402, 'e_o_k': [0.546637, 0.634167], 'p_i': 10, 'u_i': 3.7265, 'theta': 0.8633},
        {'id': 1, 'e_m': 1.120980, 'e_o_k': [2.241960], 'p_i': 20, 'u_i': 1.1305, 'theta': 0.7251},
        {'id': 2, 'e_m': 1.426234, 'e_o_k': [0.559114, 0.365736, 0.355280], 'p_i': 40, 'u_i': 2.8794, 'theta': 0.7399},
        {'id': 3, 'e_m': 13.703898, 'e_o_k': [3.685794, 4.184984, 3.334556], 'p_i': 40, 'u_i': 1.9724, 'theta': 0.9359},
        {'id': 4, 'e_m': 4.266301, 'e_o_k': [1.442839, 2.641391, 2.223174], 'p_i': 40, 'u_i': 1.4581, 'theta': 0.8999},
    ]
    B_BUDGET = 41.860004
    return processors, tasks, B_BUDGET
