"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.199997, "H": 80, "J": 40, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 8, "rho": 0.7, "seed": 1027, "set": 27, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 193.199997, "H": 80, "J": 40, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 8, "rho": 0.7, "seed": 1027, "set": 27, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.65, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.35, 0.65, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.35, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.665585, 'e_o_k': [0.172921, 0.184153, 0.165753], 'p_i': 10, 'u_i': 2.9383, 'theta': 0.7627},
        {'id': 1, 'e_m': 3.381505, 'e_o_k': [2.842360], 'p_i': 20, 'u_i': 4.6487, 'theta': 0.6411},
        {'id': 2, 'e_m': 6.720011, 'e_o_k': [1.240586, 1.051456], 'p_i': 40, 'u_i': 4.8680, 'theta': 0.9878},
        {'id': 3, 'e_m': 13.106178, 'e_o_k': [0.300932], 'p_i': 80, 'u_i': 2.7918, 'theta': 0.9942},
        {'id': 4, 'e_m': 5.000000, 'e_o_k': [1.198904, 1.099659, 1.078876, 0.669291], 'p_i': 10, 'u_i': 3.7283, 'theta': 0.9086},
        {'id': 5, 'e_m': 13.159814, 'e_o_k': [1.081723, 1.840664, 1.069952, 1.810911], 'p_i': 80, 'u_i': 1.3751, 'theta': 0.7900},
        {'id': 6, 'e_m': 1.680411, 'e_o_k': [0.077919, 0.061851], 'p_i': 10, 'u_i': 1.1291, 'theta': 0.8876},
        {'id': 7, 'e_m': 5.000000, 'e_o_k': [2.533459], 'p_i': 10, 'u_i': 2.8776, 'theta': 0.6239},
    ]
    B_BUDGET = 193.199997
    return processors, tasks, B_BUDGET
