"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1072, "set": 72, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1072, "set": 72, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.65, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.65, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.050089, 'e_o_k': [0.016149, 0.016931, 0.024963, 0.025600], 'p_i': 10, 'u_i': 2.7671, 'theta': 0.9910},
        {'id': 1, 'e_m': 6.332639, 'e_o_k': [0.117539, 0.094653, 0.134587, 0.096523], 'p_i': 20, 'u_i': 3.2553, 'theta': 0.9563},
        {'id': 2, 'e_m': 3.051173, 'e_o_k': [1.356219, 1.931094], 'p_i': 40, 'u_i': 1.3090, 'theta': 0.8484},
        {'id': 3, 'e_m': 2.761666, 'e_o_k': [1.060389], 'p_i': 10, 'u_i': 2.5174, 'theta': 0.9694},
        {'id': 4, 'e_m': 9.036528, 'e_o_k': [2.425270, 2.504416, 2.963452, 1.876924, 1.479894], 'p_i': 40, 'u_i': 2.8429, 'theta': 0.9378},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
