"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299999, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.299999, "H": 40, "J": 7, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 3, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [2.695257], 'p_i': 10, 'u_i': 1.5195, 'theta': 0.7471},
        {'id': 1, 'e_m': 6.619670, 'e_o_k': [0.118597, 0.140487, 0.106972, 0.067106, 0.084378], 'p_i': 20, 'u_i': 2.0063, 'theta': 0.7007},
        {'id': 2, 'e_m': 6.760659, 'e_o_k': [3.051565, 2.463174, 2.669153], 'p_i': 40, 'u_i': 4.5985, 'theta': 0.9858},
    ]
    B_BUDGET = 48.299999
    return processors, tasks, B_BUDGET
