"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.59999, "H": 80, "J": 32, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 96.59999, "H": 80, "J": 32, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.5, 0.55, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.5, 0.55, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.444685, 'e_o_k': [0.001574, 0.001307, 0.001867], 'p_i': 10, 'u_i': 1.5234, 'theta': 0.8847},
        {'id': 1, 'e_m': 0.476651, 'e_o_k': [0.884204], 'p_i': 20, 'u_i': 1.5965, 'theta': 0.6797},
        {'id': 2, 'e_m': 1.540956, 'e_o_k': [0.138883, 0.155311, 0.144518], 'p_i': 40, 'u_i': 1.2215, 'theta': 0.6663},
        {'id': 3, 'e_m': 0.976466, 'e_o_k': [0.819802, 1.133129], 'p_i': 80, 'u_i': 1.1780, 'theta': 0.7103},
        {'id': 4, 'e_m': 0.049572, 'e_o_k': [0.038433, 0.028989, 0.031721], 'p_i': 80, 'u_i': 3.8762, 'theta': 0.7033},
        {'id': 5, 'e_m': 16.231733, 'e_o_k': [2.670486], 'p_i': 80, 'u_i': 1.6833, 'theta': 0.6710},
        {'id': 6, 'e_m': 15.381493, 'e_o_k': [3.839093, 2.878981, 2.249893, 3.661763], 'p_i': 40, 'u_i': 1.1185, 'theta': 0.7975},
        {'id': 7, 'e_m': 0.545956, 'e_o_k': [0.052660], 'p_i': 20, 'u_i': 4.0888, 'theta': 0.8519},
        {'id': 8, 'e_m': 1.726489, 'e_o_k': [0.175317], 'p_i': 10, 'u_i': 3.9122, 'theta': 0.8061},
        {'id': 9, 'e_m': 7.437504, 'e_o_k': [0.869011, 0.876492, 1.204866, 1.002206], 'p_i': 80, 'u_i': 3.9348, 'theta': 0.9743},
    ]
    B_BUDGET = 96.599990
    return processors, tasks, B_BUDGET
