"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 77.280009, "H": 80, "J": 25, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1065, "set": 65, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 77.280009, "H": 80, "J": 25, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1065, "set": 65, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.55, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.55, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.475189, 'e_o_k': [0.032740, 0.043061, 0.041188, 0.041674], 'p_i': 10, 'u_i': 1.3252, 'theta': 0.6460},
        {'id': 1, 'e_m': 2.649905, 'e_o_k': [0.030626, 0.048921, 0.034604], 'p_i': 20, 'u_i': 1.2019, 'theta': 0.8103},
        {'id': 2, 'e_m': 5.841718, 'e_o_k': [0.045244, 0.043933, 0.051688], 'p_i': 40, 'u_i': 3.9112, 'theta': 0.6238},
        {'id': 3, 'e_m': 6.873748, 'e_o_k': [0.766697, 0.593462, 0.473641], 'p_i': 80, 'u_i': 1.5887, 'theta': 0.7403},
        {'id': 4, 'e_m': 0.446887, 'e_o_k': [0.025178, 0.026153, 0.028903, 0.020388], 'p_i': 20, 'u_i': 1.3006, 'theta': 0.6453},
        {'id': 5, 'e_m': 17.555995, 'e_o_k': [2.857068, 2.749458], 'p_i': 80, 'u_i': 4.1778, 'theta': 0.8260},
        {'id': 6, 'e_m': 2.495298, 'e_o_k': [0.176833, 0.292192, 0.320881, 0.252534], 'p_i': 20, 'u_i': 4.2896, 'theta': 0.7474},
        {'id': 7, 'e_m': 1.716948, 'e_o_k': [1.059728, 0.920072], 'p_i': 80, 'u_i': 3.6449, 'theta': 0.6196},
    ]
    B_BUDGET = 77.280009
    return processors, tasks, B_BUDGET
