"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 51.519998, "H": 40, "J": 15, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 51.519998, "H": 40, "J": 15, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [1.069290, 1.777344], 'p_i': 10, 'u_i': 2.9783, 'theta': 0.6198},
        {'id': 1, 'e_m': 8.026426, 'e_o_k': [0.116467, 0.096905, 0.118616, 0.115953, 0.150514], 'p_i': 20, 'u_i': 4.5368, 'theta': 0.8987},
        {'id': 2, 'e_m': 3.902651, 'e_o_k': [0.086972, 0.192156, 0.107052], 'p_i': 40, 'u_i': 3.1574, 'theta': 0.8277},
        {'id': 3, 'e_m': 1.032032, 'e_o_k': [0.164934, 0.177591, 0.159789], 'p_i': 10, 'u_i': 4.2592, 'theta': 0.7037},
        {'id': 4, 'e_m': 0.979092, 'e_o_k': [0.122634, 0.132645], 'p_i': 10, 'u_i': 4.9113, 'theta': 0.9713},
    ]
    B_BUDGET = 51.519998
    return processors, tasks, B_BUDGET
