"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300001, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1048, "set": 48, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.300001, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1048, "set": 48, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.65, 0.7, 0.8, 0.85, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.65, 0.7, 0.8, 0.85, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.386350], 'p_i': 10, 'u_i': 1.4120, 'theta': 0.9596},
        {'id': 1, 'e_m': 3.383419, 'e_o_k': [0.669665, 0.879685, 1.118188, 1.285540], 'p_i': 20, 'u_i': 4.8397, 'theta': 0.6404},
        {'id': 2, 'e_m': 3.767851, 'e_o_k': [0.446958, 0.570831, 0.534999], 'p_i': 40, 'u_i': 1.9722, 'theta': 0.9197},
        {'id': 3, 'e_m': 1.003530, 'e_o_k': [0.402930, 0.580917, 0.461733, 0.561479], 'p_i': 10, 'u_i': 2.7675, 'theta': 0.8524},
        {'id': 4, 'e_m': 2.725596, 'e_o_k': [0.483710], 'p_i': 20, 'u_i': 3.5752, 'theta': 0.8999},
    ]
    B_BUDGET = 48.300001
    return processors, tasks, B_BUDGET
