"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299997, "H": 40, "J": 13, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.7}
"""

_SPEC = '{"B": 48.299997, "H": 40, "J": 13, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.7}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.703491, 'e_o_k': [0.359412, 0.273669, 0.171679, 0.215867, 0.256237], 'p_i': 10, 'u_i': 2.4344, 'theta': 0.8289},
        {'id': 1, 'e_m': 5.885116, 'e_o_k': [1.910358], 'p_i': 20, 'u_i': 1.9085, 'theta': 0.8643},
        {'id': 2, 'e_m': 1.006801, 'e_o_k': [1.040155, 0.973448], 'p_i': 40, 'u_i': 2.2654, 'theta': 0.8400},
        {'id': 3, 'e_m': 4.033638, 'e_o_k': [0.478120, 0.350387, 0.268926, 0.549985, 0.479914], 'p_i': 10, 'u_i': 3.6211, 'theta': 0.7189},
        {'id': 4, 'e_m': 0.137224, 'e_o_k': [0.067017, 0.061265, 0.080108, 0.066058], 'p_i': 20, 'u_i': 3.1655, 'theta': 0.8426},
    ]
    B_BUDGET = 48.299997
    return processors, tasks, B_BUDGET
