"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 122.360001, "H": 80, "J": 27, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1091, "set": 91, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 122.360001, "H": 80, "J": 27, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1091, "set": 91, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.5, 0.55, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.5, 0.55, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.537597, 'e_o_k': [0.001199, 0.001258, 0.001168, 0.001025], 'p_i': 10, 'u_i': 4.6593, 'theta': 0.9467},
        {'id': 1, 'e_m': 3.497400, 'e_o_k': [0.111096], 'p_i': 20, 'u_i': 1.5808, 'theta': 0.7497},
        {'id': 2, 'e_m': 12.991588, 'e_o_k': [0.106355, 0.107399, 0.106221, 0.125066], 'p_i': 40, 'u_i': 2.1180, 'theta': 0.9116},
        {'id': 3, 'e_m': 16.167027, 'e_o_k': [0.391893, 0.413086, 0.425032, 0.412109], 'p_i': 80, 'u_i': 2.6598, 'theta': 0.9893},
        {'id': 4, 'e_m': 4.225171, 'e_o_k': [0.803306], 'p_i': 40, 'u_i': 1.4707, 'theta': 0.6443},
        {'id': 5, 'e_m': 10.000000, 'e_o_k': [0.160626, 0.125754, 0.066074, 0.126748], 'p_i': 20, 'u_i': 3.0479, 'theta': 0.9130},
        {'id': 6, 'e_m': 4.406782, 'e_o_k': [0.107653, 0.163896], 'p_i': 20, 'u_i': 2.7003, 'theta': 0.9194},
        {'id': 7, 'e_m': 4.740976, 'e_o_k': [0.188299], 'p_i': 40, 'u_i': 3.7721, 'theta': 0.9569},
    ]
    B_BUDGET = 122.360001
    return processors, tasks, B_BUDGET
