"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 51.520003, "H": 40, "J": 15, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1070, "set": 70, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.6, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 51.520003, "H": 40, "J": 15, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1070, "set": 70, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.6, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.55, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.55, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.925668, 'e_o_k': [0.876611, 0.484135, 0.949938], 'p_i': 10, 'u_i': 3.4422, 'theta': 0.9483},
        {'id': 1, 'e_m': 6.369916, 'e_o_k': [1.879006, 2.131728], 'p_i': 20, 'u_i': 4.2689, 'theta': 0.6295},
        {'id': 2, 'e_m': 6.915448, 'e_o_k': [0.047876, 0.035499, 0.052909], 'p_i': 40, 'u_i': 4.2610, 'theta': 0.7292},
        {'id': 3, 'e_m': 1.360745, 'e_o_k': [0.038301, 0.042611, 0.044332], 'p_i': 10, 'u_i': 4.0315, 'theta': 0.9840},
        {'id': 4, 'e_m': 1.799766, 'e_o_k': [0.579747, 0.944889], 'p_i': 10, 'u_i': 3.1161, 'theta': 0.8949},
    ]
    B_BUDGET = 51.520003
    return processors, tasks, B_BUDGET
