"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 11, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1080, "set": 80, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 11, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1080, "set": 80, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.5, 0.6, 0.65, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.5, 0.6, 0.65, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.249452, 'e_o_k': [0.100628, 0.095283, 0.091766, 0.119211, 0.092016], 'p_i': 10, 'u_i': 3.4603, 'theta': 0.8173},
        {'id': 1, 'e_m': 6.255272, 'e_o_k': [1.412297], 'p_i': 20, 'u_i': 1.7653, 'theta': 0.9454},
        {'id': 2, 'e_m': 16.765307, 'e_o_k': [8.193931], 'p_i': 40, 'u_i': 1.6134, 'theta': 0.7374},
        {'id': 3, 'e_m': 0.230595, 'e_o_k': [0.100681, 0.139488, 0.110825, 0.110197], 'p_i': 20, 'u_i': 2.0894, 'theta': 0.7176},
        {'id': 4, 'e_m': 4.632575, 'e_o_k': [3.031738], 'p_i': 20, 'u_i': 4.6717, 'theta': 0.9021},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
