"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300001, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1019, "set": 19, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.300001, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1019, "set": 19, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.852160, 'e_o_k': [0.401469], 'p_i': 10, 'u_i': 3.4110, 'theta': 0.6760},
        {'id': 1, 'e_m': 1.163892, 'e_o_k': [0.376206, 0.427498, 0.384029, 0.541884, 0.598167], 'p_i': 20, 'u_i': 1.2172, 'theta': 0.8596},
        {'id': 2, 'e_m': 10.724205, 'e_o_k': [3.954116], 'p_i': 40, 'u_i': 4.2115, 'theta': 0.9078},
        {'id': 3, 'e_m': 7.391831, 'e_o_k': [4.136511], 'p_i': 20, 'u_i': 3.8451, 'theta': 0.7187},
        {'id': 4, 'e_m': 0.188927, 'e_o_k': [0.089972, 0.106925, 0.086511, 0.094447], 'p_i': 10, 'u_i': 1.7754, 'theta': 0.6906},
    ]
    B_BUDGET = 48.300001
    return processors, tasks, B_BUDGET
