"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1019, "set": 19, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1019, "set": 19, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.162723, 'e_o_k': [0.071898, 0.068756, 0.052135], 'p_i': 10, 'u_i': 2.7784, 'theta': 0.9238},
        {'id': 1, 'e_m': 3.286831, 'e_o_k': [0.165710, 0.170107, 0.159259, 0.200392], 'p_i': 20, 'u_i': 4.2232, 'theta': 0.8706},
        {'id': 2, 'e_m': 5.093742, 'e_o_k': [2.259280, 1.231538, 1.574087, 1.676984], 'p_i': 40, 'u_i': 2.1674, 'theta': 0.6409},
        {'id': 3, 'e_m': 0.920426, 'e_o_k': [0.492710, 0.357268, 0.437104, 0.553769], 'p_i': 10, 'u_i': 3.8451, 'theta': 0.7187},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [0.262911, 0.509021, 0.604933, 0.489444], 'p_i': 20, 'u_i': 1.7754, 'theta': 0.6906},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
