"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 61.179999, "H": 40, "J": 15, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.9, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 61.179999, "H": 40, "J": 15, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.9, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [2.405902, 3.999024], 'p_i': 10, 'u_i': 2.9783, 'theta': 0.6198},
        {'id': 1, 'e_m': 6.688688, 'e_o_k': [0.262052, 0.218037, 0.266885, 0.260894, 0.338657], 'p_i': 20, 'u_i': 4.5368, 'theta': 0.8987},
        {'id': 2, 'e_m': 1.620509, 'e_o_k': [0.195686, 0.432352, 0.240866], 'p_i': 40, 'u_i': 3.1574, 'theta': 0.8277},
        {'id': 3, 'e_m': 0.860027, 'e_o_k': [0.371102, 0.399579, 0.359526], 'p_i': 10, 'u_i': 4.2592, 'theta': 0.7037},
        {'id': 4, 'e_m': 0.390502, 'e_o_k': [0.275926, 0.298452], 'p_i': 10, 'u_i': 4.9113, 'theta': 0.9713},
    ]
    B_BUDGET = 61.179999
    return processors, tasks, B_BUDGET
