"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 1.0]},
        {'id': 1, 'frequencies': [0.45, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.226060, 'e_o_k': [0.474481, 0.407396, 0.464945], 'p_i': 10, 'u_i': 4.8328, 'theta': 0.8572},
        {'id': 1, 'e_m': 7.403791, 'e_o_k': [0.902244, 0.553536, 0.592833], 'p_i': 20, 'u_i': 4.4771, 'theta': 0.7718},
        {'id': 2, 'e_m': 7.744728, 'e_o_k': [1.540833, 3.031144], 'p_i': 40, 'u_i': 4.5690, 'theta': 0.8063},
        {'id': 3, 'e_m': 0.704729, 'e_o_k': [0.308793], 'p_i': 20, 'u_i': 3.0691, 'theta': 0.8058},
        {'id': 4, 'e_m': 3.133990, 'e_o_k': [1.859428, 1.757161, 1.709334], 'p_i': 40, 'u_i': 3.5072, 'theta': 0.7944},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
