"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299999, "H": 40, "J": 25, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1002, "set": 2, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.299999, "H": 40, "J": 25, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1002, "set": 2, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.45, 0.6, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.45, 0.6, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.593569, 'e_o_k': [0.192523], 'p_i': 10, 'u_i': 4.7572, 'theta': 0.8437},
        {'id': 1, 'e_m': 2.488285, 'e_o_k': [2.146410], 'p_i': 20, 'u_i': 3.3908, 'theta': 0.6274},
        {'id': 2, 'e_m': 0.013239, 'e_o_k': [0.013916, 0.012561], 'p_i': 40, 'u_i': 3.1962, 'theta': 0.9190},
        {'id': 3, 'e_m': 5.393568, 'e_o_k': [2.690936], 'p_i': 20, 'u_i': 2.9308, 'theta': 0.7970},
        {'id': 4, 'e_m': 4.373728, 'e_o_k': [0.594462], 'p_i': 20, 'u_i': 1.2467, 'theta': 0.6720},
        {'id': 5, 'e_m': 0.305007, 'e_o_k': [0.242140], 'p_i': 10, 'u_i': 1.3676, 'theta': 0.9310},
        {'id': 6, 'e_m': 3.985599, 'e_o_k': [0.942074], 'p_i': 40, 'u_i': 1.9479, 'theta': 0.6198},
        {'id': 7, 'e_m': 0.996261, 'e_o_k': [0.813150, 0.560937], 'p_i': 40, 'u_i': 2.8890, 'theta': 0.6628},
        {'id': 8, 'e_m': 2.220504, 'e_o_k': [1.222512], 'p_i': 40, 'u_i': 1.1082, 'theta': 0.7721},
        {'id': 9, 'e_m': 0.154583, 'e_o_k': [0.309165], 'p_i': 10, 'u_i': 1.3475, 'theta': 0.8311},
        {'id': 10, 'e_m': 0.884967, 'e_o_k': [0.513922, 0.558586, 0.412213], 'p_i': 40, 'u_i': 3.8782, 'theta': 0.9276},
        {'id': 11, 'e_m': 1.587816, 'e_o_k': [0.555600], 'p_i': 20, 'u_i': 2.3853, 'theta': 0.9315},
    ]
    B_BUDGET = 48.299999
    return processors, tasks, B_BUDGET
