"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599999, "H": 40, "J": 15, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.599999, "H": 40, "J": 15, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 2, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 3, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.849448, 'e_o_k': [0.628897, 0.564367, 0.627182, 0.625626, 0.905665], 'p_i': 10, 'u_i': 1.1514, 'theta': 0.7590},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [1.504173, 1.438432], 'p_i': 20, 'u_i': 2.2654, 'theta': 0.7866},
        {'id': 2, 'e_m': 11.231878, 'e_o_k': [0.051200, 0.050439, 0.036964, 0.028370, 0.058020], 'p_i': 40, 'u_i': 3.7628, 'theta': 0.6204},
        {'id': 3, 'e_m': 3.627642, 'e_o_k': [2.283464, 2.009108], 'p_i': 10, 'u_i': 2.5400, 'theta': 0.8202},
        {'id': 4, 'e_m': 5.689120, 'e_o_k': [0.104322, 0.106661], 'p_i': 20, 'u_i': 3.1655, 'theta': 0.7901},
        {'id': 5, 'e_m': 5.740761, 'e_o_k': [0.849225, 0.596072], 'p_i': 20, 'u_i': 1.9656, 'theta': 0.6665},
    ]
    B_BUDGET = 96.599999
    return processors, tasks, B_BUDGET
