"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 35.420002, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1094, "set": 94, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 35.420002, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1094, "set": 94, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.7, 0.8, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.7, 0.8, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.496868, 'e_o_k': [1.441158], 'p_i': 10, 'u_i': 4.3331, 'theta': 0.9083},
        {'id': 1, 'e_m': 0.807502, 'e_o_k': [5.113694], 'p_i': 20, 'u_i': 1.6866, 'theta': 0.9702},
        {'id': 2, 'e_m': 0.514204, 'e_o_k': [1.859259, 1.747800, 2.000223], 'p_i': 40, 'u_i': 1.1663, 'theta': 0.9355},
        {'id': 3, 'e_m': 0.022284, 'e_o_k': [1.774522], 'p_i': 10, 'u_i': 1.0995, 'theta': 0.8125},
        {'id': 4, 'e_m': 1.897092, 'e_o_k': [1.679548, 1.971758], 'p_i': 20, 'u_i': 2.5731, 'theta': 0.7266},
    ]
    B_BUDGET = 35.420002
    return processors, tasks, B_BUDGET
