"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600003, "H": 40, "J": 11, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1092, "set": 92, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.600003, "H": 40, "J": 11, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1092, "set": 92, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.172060, 'e_o_k': [0.673060, 0.966609, 0.697116], 'p_i': 10, 'u_i': 2.2399, 'theta': 0.7347},
        {'id': 1, 'e_m': 4.351480, 'e_o_k': [1.116612, 1.313367, 0.580189], 'p_i': 20, 'u_i': 4.4103, 'theta': 0.8216},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [2.262924, 1.839116, 2.463911, 2.416334, 2.353048], 'p_i': 40, 'u_i': 4.0378, 'theta': 0.9940},
        {'id': 3, 'e_m': 4.292419, 'e_o_k': [0.850003, 1.528902, 1.477594, 1.453283], 'p_i': 20, 'u_i': 3.7593, 'theta': 0.9499},
        {'id': 4, 'e_m': 8.541871, 'e_o_k': [1.185745, 1.072163], 'p_i': 40, 'u_i': 2.8667, 'theta': 0.8925},
        {'id': 5, 'e_m': 17.482093, 'e_o_k': [0.281934, 0.137787], 'p_i': 40, 'u_i': 4.5636, 'theta': 0.7511},
    ]
    B_BUDGET = 96.600003
    return processors, tasks, B_BUDGET
