"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 115.920004, "H": 80, "J": 30, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1072, "set": 72, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 115.920004, "H": 80, "J": 30, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1072, "set": 72, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.6, 0.65, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.6, 0.65, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.292435, 'e_o_k': [0.293676, 0.666306, 0.391579, 0.574458], 'p_i': 10, 'u_i': 1.9966, 'theta': 0.9591},
        {'id': 1, 'e_m': 5.539630, 'e_o_k': [2.464271], 'p_i': 20, 'u_i': 2.6358, 'theta': 0.9042},
        {'id': 2, 'e_m': 3.128724, 'e_o_k': [0.563756, 0.736259, 0.671980, 0.947383], 'p_i': 40, 'u_i': 4.8190, 'theta': 0.8812},
        {'id': 3, 'e_m': 3.973931, 'e_o_k': [0.048863, 0.042424, 0.044790, 0.050844], 'p_i': 80, 'u_i': 1.4696, 'theta': 0.7758},
        {'id': 4, 'e_m': 2.173133, 'e_o_k': [1.362229, 1.789097, 0.603838], 'p_i': 40, 'u_i': 2.7309, 'theta': 0.7465},
        {'id': 5, 'e_m': 1.344152, 'e_o_k': [2.436925], 'p_i': 20, 'u_i': 1.0675, 'theta': 0.8349},
        {'id': 6, 'e_m': 0.365667, 'e_o_k': [0.366372, 0.299015], 'p_i': 10, 'u_i': 3.5007, 'theta': 0.7762},
        {'id': 7, 'e_m': 16.622416, 'e_o_k': [5.466244, 4.661719], 'p_i': 80, 'u_i': 4.6492, 'theta': 0.7074},
    ]
    B_BUDGET = 115.920004
    return processors, tasks, B_BUDGET
