"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.4, 0.5, 0.55, 0.6, 0.65, 0.75, 0.8, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.4, 0.5, 0.55, 0.6, 0.65, 0.75, 0.8, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.230478, 'e_o_k': [1.152364], 'p_i': 10, 'u_i': 1.6257, 'theta': 0.6026},
        {'id': 1, 'e_m': 2.584186, 'e_o_k': [1.582908, 1.321059, 1.464040], 'p_i': 20, 'u_i': 3.8662, 'theta': 0.6386},
        {'id': 2, 'e_m': 4.993585, 'e_o_k': [0.142802, 0.192153, 0.151371, 0.133832], 'p_i': 40, 'u_i': 3.8466, 'theta': 0.6364},
        {'id': 3, 'e_m': 4.916130, 'e_o_k': [0.881179, 0.973148, 1.067543, 1.000412], 'p_i': 40, 'u_i': 3.6608, 'theta': 0.7712},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [0.518584, 0.537460], 'p_i': 20, 'u_i': 1.5800, 'theta': 0.6606},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
