"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599995, "H": 80, "J": 36, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1098, "set": 98, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.5}
"""

_SPEC = '{"B": 96.599995, "H": 80, "J": 36, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1098, "set": 98, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.5}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.5, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.5, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.631831, 'e_o_k': [0.817347], 'p_i': 10, 'u_i': 4.7746, 'theta': 0.9337},
        {'id': 1, 'e_m': 1.707801, 'e_o_k': [1.202515], 'p_i': 20, 'u_i': 4.7651, 'theta': 0.6117},
        {'id': 2, 'e_m': 6.144122, 'e_o_k': [0.139281, 0.146546, 0.167193], 'p_i': 40, 'u_i': 2.9395, 'theta': 0.9091},
        {'id': 3, 'e_m': 11.485668, 'e_o_k': [6.807548], 'p_i': 80, 'u_i': 3.2811, 'theta': 0.9301},
        {'id': 4, 'e_m': 1.271678, 'e_o_k': [0.530469, 0.259300], 'p_i': 20, 'u_i': 3.3211, 'theta': 0.6272},
        {'id': 5, 'e_m': 2.251865, 'e_o_k': [0.299706, 0.233011], 'p_i': 10, 'u_i': 2.9955, 'theta': 0.6939},
        {'id': 6, 'e_m': 11.288708, 'e_o_k': [4.037732, 2.835684, 3.965734], 'p_i': 80, 'u_i': 2.2105, 'theta': 0.8795},
        {'id': 7, 'e_m': 0.243737, 'e_o_k': [0.334701], 'p_i': 10, 'u_i': 2.1946, 'theta': 0.6683},
    ]
    B_BUDGET = 96.599995
    return processors, tasks, B_BUDGET
