"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 51.520003, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1048, "set": 48, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 51.520003, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1048, "set": 48, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.45, 0.5, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.45, 0.5, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.504404, 'e_o_k': [2.634219], 'p_i': 10, 'u_i': 4.6724, 'theta': 0.8958},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [0.626636, 0.726732], 'p_i': 20, 'u_i': 1.7454, 'theta': 0.6955},
        {'id': 2, 'e_m': 5.996482, 'e_o_k': [0.168514, 0.202057, 0.176569], 'p_i': 40, 'u_i': 3.4122, 'theta': 0.7145},
        {'id': 3, 'e_m': 4.690636, 'e_o_k': [0.004787, 0.004078, 0.005522], 'p_i': 20, 'u_i': 3.0082, 'theta': 0.6260},
        {'id': 4, 'e_m': 0.651158, 'e_o_k': [0.320448, 0.224671], 'p_i': 10, 'u_i': 2.4970, 'theta': 0.6847},
    ]
    B_BUDGET = 51.520003
    return processors, tasks, B_BUDGET
