"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 35.419999, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1096, "set": 96, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 35.419999, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1096, "set": 96, "sweep": "u_mand_factor", "u_mand_factor": 0.1, "u_opt_factor": 0.5, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.65, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.65, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.596642, 'e_o_k': [1.587450, 1.549848], 'p_i': 10, 'u_i': 3.6242, 'theta': 0.6159},
        {'id': 1, 'e_m': 0.152009, 'e_o_k': [1.257848, 0.995127, 1.375298, 1.370028, 0.829650], 'p_i': 20, 'u_i': 2.9768, 'theta': 0.9236},
        {'id': 2, 'e_m': 0.497504, 'e_o_k': [0.959679, 0.977294, 1.060815, 0.756401], 'p_i': 40, 'u_i': 4.0135, 'theta': 0.9801},
        {'id': 3, 'e_m': 0.108721, 'e_o_k': [1.954711, 1.252416], 'p_i': 20, 'u_i': 4.8426, 'theta': 0.7607},
        {'id': 4, 'e_m': 0.297234, 'e_o_k': [0.170762, 0.209456, 0.151100, 0.129484, 0.152429], 'p_i': 20, 'u_i': 2.1915, 'theta': 0.6942},
    ]
    B_BUDGET = 35.419999
    return processors, tasks, B_BUDGET
