"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 27.6, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.4, "seed": 1080, "set": 80, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 27.6, "H": 40, "J": 13, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.4, "seed": 1080, "set": 80, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.65, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.65, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.351629, 'e_o_k': [0.271167, 0.157062], 'p_i': 10, 'u_i': 4.8493, 'theta': 0.6104},
        {'id': 1, 'e_m': 4.247854, 'e_o_k': [1.528095, 2.185152], 'p_i': 20, 'u_i': 3.9460, 'theta': 0.8424},
        {'id': 2, 'e_m': 7.101554, 'e_o_k': [1.427952, 1.852313, 2.305687], 'p_i': 40, 'u_i': 1.3860, 'theta': 0.8836},
        {'id': 3, 'e_m': 2.486886, 'e_o_k': [0.440065, 0.354256], 'p_i': 10, 'u_i': 2.9947, 'theta': 0.7557},
        {'id': 4, 'e_m': 0.524339, 'e_o_k': [0.420944, 0.304982, 0.322751], 'p_i': 20, 'u_i': 2.0894, 'theta': 0.7176},
    ]
    B_BUDGET = 27.600000
    return processors, tasks, B_BUDGET
