"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 61.179999, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1009, "set": 9, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 61.179999, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1009, "set": 9, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.55, 0.75, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.55, 0.75, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.146037, 0.086147], 'p_i': 10, 'u_i': 1.2628, 'theta': 0.6801},
        {'id': 1, 'e_m': 6.420836, 'e_o_k': [1.120287], 'p_i': 20, 'u_i': 1.9745, 'theta': 0.6874},
        {'id': 2, 'e_m': 12.963961, 'e_o_k': [0.309623, 0.158765, 0.259136], 'p_i': 40, 'u_i': 1.5681, 'theta': 0.8150},
        {'id': 3, 'e_m': 6.706598, 'e_o_k': [0.022707], 'p_i': 20, 'u_i': 2.2974, 'theta': 0.9556},
        {'id': 4, 'e_m': 6.390585, 'e_o_k': [0.028876], 'p_i': 20, 'u_i': 3.4443, 'theta': 0.7198},
    ]
    B_BUDGET = 61.179999
    return processors, tasks, B_BUDGET
