"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600002, "H": 40, "J": 13, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.600002, "H": 40, "J": 13, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.738122, 0.641478, 0.849540], 'p_i': 10, 'u_i': 4.5666, 'theta': 0.9771},
        {'id': 1, 'e_m': 0.982746, 'e_o_k': [0.122069, 0.121029, 0.152576], 'p_i': 20, 'u_i': 3.5354, 'theta': 0.7331},
        {'id': 2, 'e_m': 8.316407, 'e_o_k': [8.798626, 7.834188], 'p_i': 40, 'u_i': 1.1966, 'theta': 0.9265},
        {'id': 3, 'e_m': 12.820698, 'e_o_k': [3.287991], 'p_i': 40, 'u_i': 2.6922, 'theta': 0.9412},
        {'id': 4, 'e_m': 20.000000, 'e_o_k': [4.385422, 3.979879], 'p_i': 40, 'u_i': 4.5239, 'theta': 0.6736},
        {'id': 5, 'e_m': 4.224351, 'e_o_k': [0.501497], 'p_i': 10, 'u_i': 1.0774, 'theta': 0.9632},
    ]
    B_BUDGET = 96.600002
    return processors, tasks, B_BUDGET
