"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 109.480001, "H": 80, "J": 24, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1097, "set": 97, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.7, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 109.480001, "H": 80, "J": 24, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1097, "set": 97, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.7, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.247625, 'e_o_k': [0.544482, 0.605149, 0.616210, 0.729408], 'p_i': 10, 'u_i': 3.2164, 'theta': 0.7713},
        {'id': 1, 'e_m': 0.442990, 'e_o_k': [0.012752, 0.014258, 0.014053, 0.013840], 'p_i': 20, 'u_i': 2.7921, 'theta': 0.9654},
        {'id': 2, 'e_m': 10.979208, 'e_o_k': [7.654274], 'p_i': 40, 'u_i': 2.8611, 'theta': 0.9165},
        {'id': 3, 'e_m': 6.502488, 'e_o_k': [0.669799, 0.575940, 0.512079, 0.975138], 'p_i': 80, 'u_i': 1.1240, 'theta': 0.9698},
        {'id': 4, 'e_m': 6.155283, 'e_o_k': [0.156736, 0.131703, 0.156044, 0.147883], 'p_i': 40, 'u_i': 2.1650, 'theta': 0.7070},
        {'id': 5, 'e_m': 1.475586, 'e_o_k': [0.844198, 1.104473, 1.002501], 'p_i': 20, 'u_i': 4.0198, 'theta': 0.9249},
        {'id': 6, 'e_m': 9.966110, 'e_o_k': [1.305640, 1.003021, 0.944482], 'p_i': 80, 'u_i': 3.2939, 'theta': 0.8934},
        {'id': 7, 'e_m': 5.803561, 'e_o_k': [0.284489, 0.240942, 0.241731], 'p_i': 40, 'u_i': 2.8069, 'theta': 0.7287},
    ]
    B_BUDGET = 109.480001
    return processors, tasks, B_BUDGET
