"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 386.400002, "H": 80, "J": 34, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1097, "set": 97, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 386.400002, "H": 80, "J": 34, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1097, "set": 97, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
        {'id': 4, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
        {'id': 5, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
        {'id': 6, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
        {'id': 7, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.406271, 0.549455, 0.490299], 'p_i': 10, 'u_i': 1.6059, 'theta': 0.7861},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [0.665523, 0.725391, 0.644958, 1.228176], 'p_i': 20, 'u_i': 1.1240, 'theta': 0.9698},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [0.667605, 0.560980, 0.664658, 0.629896], 'p_i': 40, 'u_i': 2.1650, 'theta': 0.7070},
        {'id': 3, 'e_m': 15.002826, 'e_o_k': [4.061462, 5.313651, 4.823058], 'p_i': 80, 'u_i': 4.0198, 'theta': 0.9249},
        {'id': 4, 'e_m': 7.509911, 'e_o_k': [6.028165, 4.630965, 4.360693], 'p_i': 40, 'u_i': 3.2939, 'theta': 0.8934},
        {'id': 5, 'e_m': 5.548992, 'e_o_k': [0.055281, 0.046819, 0.046973], 'p_i': 20, 'u_i': 2.8069, 'theta': 0.7287},
        {'id': 6, 'e_m': 33.068526, 'e_o_k': [17.391835, 14.436804, 11.212330], 'p_i': 80, 'u_i': 2.5756, 'theta': 0.9990},
        {'id': 7, 'e_m': 7.503200, 'e_o_k': [1.639779, 1.386329], 'p_i': 40, 'u_i': 3.4960, 'theta': 0.6731},
        {'id': 8, 'e_m': 40.000000, 'e_o_k': [5.253165, 4.507193, 4.841638], 'p_i': 80, 'u_i': 4.8689, 'theta': 0.8532},
        {'id': 9, 'e_m': 20.274601, 'e_o_k': [3.410481, 2.251407, 2.443787, 2.183556], 'p_i': 80, 'u_i': 3.2290, 'theta': 0.8876},
        {'id': 10, 'e_m': 3.732756, 'e_o_k': [0.558791, 0.958319, 1.030751], 'p_i': 20, 'u_i': 3.8044, 'theta': 0.6941},
        {'id': 11, 'e_m': 6.125208, 'e_o_k': [0.086037, 0.069634, 0.096756, 0.077415], 'p_i': 20, 'u_i': 3.9448, 'theta': 0.6518},
    ]
    B_BUDGET = 386.400002
    return processors, tasks, B_BUDGET
