"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 45.080005, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1013, "set": 13, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 45.080005, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1013, "set": 13, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.5, 0.65, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.5, 0.65, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.699660, 'e_o_k': [0.305764, 0.399737], 'p_i': 10, 'u_i': 3.5072, 'theta': 0.8708},
        {'id': 1, 'e_m': 0.861025, 'e_o_k': [0.712641, 0.710910], 'p_i': 20, 'u_i': 1.4156, 'theta': 0.6480},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [2.237599, 3.387035, 4.169069, 3.694391], 'p_i': 40, 'u_i': 3.7321, 'theta': 0.7276},
        {'id': 3, 'e_m': 0.904487, 'e_o_k': [0.418139, 0.429675, 0.271423, 0.394208, 0.295122], 'p_i': 20, 'u_i': 4.2631, 'theta': 0.6260},
        {'id': 4, 'e_m': 0.417584, 'e_o_k': [0.116227, 0.083295, 0.106896], 'p_i': 10, 'u_i': 2.8916, 'theta': 0.6286},
    ]
    B_BUDGET = 45.080005
    return processors, tasks, B_BUDGET
