"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 54.740002, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1013, "set": 13, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 54.740002, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1013, "set": 13, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.5, 0.65, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.5, 0.65, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.974405, 'e_o_k': [0.152882, 0.199868], 'p_i': 10, 'u_i': 3.5072, 'theta': 0.8708},
        {'id': 1, 'e_m': 4.006793, 'e_o_k': [0.356321, 0.355455], 'p_i': 20, 'u_i': 1.4156, 'theta': 0.6480},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [1.118799, 1.693518, 2.084534, 1.847195], 'p_i': 40, 'u_i': 3.7321, 'theta': 0.7276},
        {'id': 3, 'e_m': 3.981511, 'e_o_k': [0.209069, 0.214838, 0.135712, 0.197104, 0.147561], 'p_i': 20, 'u_i': 4.2631, 'theta': 0.6260},
        {'id': 4, 'e_m': 2.031443, 'e_o_k': [0.058113, 0.041648, 0.053448], 'p_i': 10, 'u_i': 2.8916, 'theta': 0.6286},
    ]
    B_BUDGET = 54.740002
    return processors, tasks, B_BUDGET
