"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.039993, "H": 80, "J": 28, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1092, "set": 92, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.6, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.039993, "H": 80, "J": 28, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1092, "set": 92, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.6, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.5, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.182273, 'e_o_k': [0.155577, 0.068727, 0.140243], 'p_i': 10, 'u_i': 4.1865, 'theta': 0.9184},
        {'id': 1, 'e_m': 0.564198, 'e_o_k': [0.347279, 0.397734, 0.383384], 'p_i': 20, 'u_i': 2.4368, 'theta': 0.8399},
        {'id': 2, 'e_m': 8.913083, 'e_o_k': [2.668936, 4.047034], 'p_i': 40, 'u_i': 4.4838, 'theta': 0.9240},
        {'id': 3, 'e_m': 11.481535, 'e_o_k': [3.082142, 1.821469, 2.632981], 'p_i': 80, 'u_i': 4.0627, 'theta': 0.6868},
        {'id': 4, 'e_m': 10.808951, 'e_o_k': [1.920476, 2.302279], 'p_i': 40, 'u_i': 2.6872, 'theta': 0.9768},
        {'id': 5, 'e_m': 10.126420, 'e_o_k': [0.599647, 0.697548, 0.734744, 0.814552], 'p_i': 40, 'u_i': 3.6018, 'theta': 0.8430},
        {'id': 6, 'e_m': 0.538264, 'e_o_k': [0.242092, 0.240669], 'p_i': 10, 'u_i': 3.7334, 'theta': 0.9857},
        {'id': 7, 'e_m': 0.800461, 'e_o_k': [0.463459, 0.351609, 0.393227, 0.392628], 'p_i': 80, 'u_i': 2.1947, 'theta': 0.9324},
    ]
    B_BUDGET = 103.039993
    return processors, tasks, B_BUDGET
