"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 70.840001, "H": 80, "J": 34, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1016, "set": 16, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 70.840001, "H": 80, "J": 34, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1016, "set": 16, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.6, 0.7, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.6, 0.7, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.026424, 'e_o_k': [0.026239, 0.018948, 0.028166], 'p_i': 10, 'u_i': 3.3241, 'theta': 0.7382},
        {'id': 1, 'e_m': 0.286064, 'e_o_k': [0.173494, 0.142961], 'p_i': 20, 'u_i': 3.7407, 'theta': 0.6360},
        {'id': 2, 'e_m': 4.856530, 'e_o_k': [0.368908, 0.196972], 'p_i': 40, 'u_i': 3.3362, 'theta': 0.9047},
        {'id': 3, 'e_m': 9.482344, 'e_o_k': [0.077519, 0.080614], 'p_i': 80, 'u_i': 4.5421, 'theta': 0.7194},
        {'id': 4, 'e_m': 0.977249, 'e_o_k': [0.050777, 0.037706, 0.051079, 0.047050], 'p_i': 10, 'u_i': 2.8759, 'theta': 0.8636},
        {'id': 5, 'e_m': 5.256204, 'e_o_k': [0.243493, 0.247994, 0.187382, 0.093807], 'p_i': 40, 'u_i': 2.9145, 'theta': 0.9228},
        {'id': 6, 'e_m': 27.146833, 'e_o_k': [0.700323], 'p_i': 80, 'u_i': 4.6070, 'theta': 0.8341},
        {'id': 7, 'e_m': 0.746464, 'e_o_k': [0.019054, 0.038993, 0.043423, 0.038392], 'p_i': 10, 'u_i': 2.2129, 'theta': 0.7749},
    ]
    B_BUDGET = 70.840001
    return processors, tasks, B_BUDGET
