"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 38.639996, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 38.639996, "H": 40, "J": 12, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.358752, 'e_o_k': [0.160277, 0.218303, 0.278132], 'p_i': 10, 'u_i': 3.8489, 'theta': 0.8250},
        {'id': 1, 'e_m': 3.661884, 'e_o_k': [7.313424], 'p_i': 20, 'u_i': 3.9101, 'theta': 0.7425},
        {'id': 2, 'e_m': 0.842912, 'e_o_k': [1.947349], 'p_i': 40, 'u_i': 3.4836, 'theta': 0.6583},
        {'id': 3, 'e_m': 0.725665, 'e_o_k': [0.440623, 0.464701, 0.546007], 'p_i': 10, 'u_i': 2.9871, 'theta': 0.6916},
        {'id': 4, 'e_m': 3.495648, 'e_o_k': [2.996812, 2.614399, 1.382419], 'p_i': 40, 'u_i': 3.1592, 'theta': 0.8862},
    ]
    B_BUDGET = 38.639996
    return processors, tasks, B_BUDGET
