"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 122.360001, "H": 80, "J": 40, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1090, "set": 90, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 122.360001, "H": 80, "J": 40, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1090, "set": 90, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.55, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.55, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.261509, 'e_o_k': [0.017123], 'p_i': 10, 'u_i': 3.3237, 'theta': 0.9493},
        {'id': 1, 'e_m': 5.974483, 'e_o_k': [0.168459], 'p_i': 20, 'u_i': 1.6064, 'theta': 0.8830},
        {'id': 2, 'e_m': 1.340824, 'e_o_k': [0.051708, 0.078852, 0.101071], 'p_i': 40, 'u_i': 4.2470, 'theta': 0.6636},
        {'id': 3, 'e_m': 9.335870, 'e_o_k': [0.199014], 'p_i': 80, 'u_i': 2.3215, 'theta': 0.8009},
        {'id': 4, 'e_m': 1.823413, 'e_o_k': [0.073549, 0.054501, 0.048920, 0.067261], 'p_i': 10, 'u_i': 4.6410, 'theta': 0.7851},
        {'id': 5, 'e_m': 1.109604, 'e_o_k': [0.060838, 0.071512, 0.072842, 0.065370], 'p_i': 10, 'u_i': 1.3550, 'theta': 0.6154},
        {'id': 6, 'e_m': 34.528342, 'e_o_k': [0.308604, 0.167195, 0.205562], 'p_i': 80, 'u_i': 3.0573, 'theta': 0.6117},
        {'id': 7, 'e_m': 5.000000, 'e_o_k': [0.054188, 0.054600, 0.052001, 0.055111], 'p_i': 10, 'u_i': 4.6517, 'theta': 0.7745},
    ]
    B_BUDGET = 122.360001
    return processors, tasks, B_BUDGET
