"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 386.40001, "H": 80, "J": 46, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1099, "set": 99, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 386.40001, "H": 80, "J": 46, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1099, "set": 99, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.6, 0.8, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.6, 0.8, 0.85, 1.0]},
        {'id': 2, 'frequencies': [0.45, 0.6, 0.8, 0.85, 1.0]},
        {'id': 3, 'frequencies': [0.45, 0.6, 0.8, 0.85, 1.0]},
        {'id': 4, 'frequencies': [0.45, 0.6, 0.8, 0.85, 1.0]},
        {'id': 5, 'frequencies': [0.45, 0.6, 0.8, 0.85, 1.0]},
        {'id': 6, 'frequencies': [0.45, 0.6, 0.8, 0.85, 1.0]},
        {'id': 7, 'frequencies': [0.45, 0.6, 0.8, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.995729, 'e_o_k': [0.732038], 'p_i': 10, 'u_i': 1.5858, 'theta': 0.7040},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [1.869514, 1.784056, 1.783132, 1.299592], 'p_i': 20, 'u_i': 4.1730, 'theta': 0.8490},
        {'id': 2, 'e_m': 11.233533, 'e_o_k': [1.006496, 1.260300, 1.190687], 'p_i': 40, 'u_i': 2.9293, 'theta': 0.6231},
        {'id': 3, 'e_m': 17.396710, 'e_o_k': [3.061849], 'p_i': 80, 'u_i': 1.0562, 'theta': 0.6336},
        {'id': 4, 'e_m': 17.814559, 'e_o_k': [2.487912, 2.740654, 1.591118], 'p_i': 80, 'u_i': 2.4449, 'theta': 0.8519},
        {'id': 5, 'e_m': 15.827670, 'e_o_k': [2.785977], 'p_i': 80, 'u_i': 2.8011, 'theta': 0.8818},
        {'id': 6, 'e_m': 5.000000, 'e_o_k': [0.951356, 0.947433, 1.089581], 'p_i': 10, 'u_i': 4.9424, 'theta': 0.9738},
        {'id': 7, 'e_m': 5.000000, 'e_o_k': [0.151902, 0.144425, 0.171402], 'p_i': 10, 'u_i': 2.2871, 'theta': 0.9000},
        {'id': 8, 'e_m': 5.000000, 'e_o_k': [1.779714, 1.434868, 1.277457], 'p_i': 10, 'u_i': 1.1031, 'theta': 0.8202},
        {'id': 9, 'e_m': 7.814541, 'e_o_k': [2.386506, 2.640058, 2.069514, 2.391274], 'p_i': 40, 'u_i': 2.1557, 'theta': 0.7545},
        {'id': 10, 'e_m': 10.175541, 'e_o_k': [5.198151, 5.511926], 'p_i': 40, 'u_i': 1.3661, 'theta': 0.6433},
        {'id': 11, 'e_m': 34.547996, 'e_o_k': [1.011081, 0.815955, 0.769854, 1.039208], 'p_i': 80, 'u_i': 2.7919, 'theta': 0.7149},
    ]
    B_BUDGET = 386.400010
    return processors, tasks, B_BUDGET
