"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 122.360001, "H": 80, "J": 33, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 122.360001, "H": 80, "J": 33, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.765007, 'e_o_k': [0.006712, 0.007448, 0.011048], 'p_i': 10, 'u_i': 2.5588, 'theta': 0.9794},
        {'id': 1, 'e_m': 5.372512, 'e_o_k': [0.333338], 'p_i': 20, 'u_i': 3.8633, 'theta': 0.6749},
        {'id': 2, 'e_m': 7.592249, 'e_o_k': [0.206032, 0.148870, 0.181988, 0.149930], 'p_i': 40, 'u_i': 1.9405, 'theta': 0.6527},
        {'id': 3, 'e_m': 8.172047, 'e_o_k': [0.597254, 0.625315, 0.244550, 0.641101], 'p_i': 80, 'u_i': 4.0552, 'theta': 0.7429},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [0.376965], 'p_i': 20, 'u_i': 2.7617, 'theta': 0.7558},
        {'id': 5, 'e_m': 20.000000, 'e_o_k': [0.002886, 0.002711, 0.003299, 0.002974], 'p_i': 40, 'u_i': 2.7259, 'theta': 0.6396},
        {'id': 6, 'e_m': 0.866004, 'e_o_k': [0.021620, 0.040221, 0.048353, 0.062081], 'p_i': 10, 'u_i': 1.5735, 'theta': 0.7435},
        {'id': 7, 'e_m': 1.526329, 'e_o_k': [0.004424, 0.004505, 0.004778, 0.004625], 'p_i': 20, 'u_i': 3.8044, 'theta': 0.7507},
    ]
    B_BUDGET = 122.360001
    return processors, tasks, B_BUDGET
