"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 122.359999, "H": 80, "J": 29, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1073, "set": 73, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.9, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 122.359999, "H": 80, "J": 29, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1073, "set": 73, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.9, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.55, 0.75, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.55, 0.75, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.178627, 'e_o_k': [0.231191, 0.337496], 'p_i': 10, 'u_i': 4.6097, 'theta': 0.9976},
        {'id': 1, 'e_m': 7.624422, 'e_o_k': [1.602421, 2.216570], 'p_i': 20, 'u_i': 3.8380, 'theta': 0.8557},
        {'id': 2, 'e_m': 3.415466, 'e_o_k': [1.277505, 1.120851], 'p_i': 40, 'u_i': 3.9239, 'theta': 0.9601},
        {'id': 3, 'e_m': 6.297853, 'e_o_k': [5.150543, 7.445163], 'p_i': 80, 'u_i': 1.6050, 'theta': 0.9657},
        {'id': 4, 'e_m': 0.966361, 'e_o_k': [0.690031, 0.582818, 0.348771], 'p_i': 10, 'u_i': 4.8129, 'theta': 0.8168},
        {'id': 5, 'e_m': 0.863761, 'e_o_k': [0.516745, 0.592701], 'p_i': 80, 'u_i': 4.7754, 'theta': 0.8141},
        {'id': 6, 'e_m': 10.239979, 'e_o_k': [20.479958], 'p_i': 80, 'u_i': 2.5140, 'theta': 0.8669},
        {'id': 7, 'e_m': 0.027470, 'e_o_k': [0.022818, 0.015595, 0.016527], 'p_i': 20, 'u_i': 3.3776, 'theta': 0.6362},
    ]
    B_BUDGET = 122.359999
    return processors, tasks, B_BUDGET
