"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300003, "H": 40, "J": 27, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.300003, "H": 40, "J": 27, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.160837, 'e_o_k': [0.162505, 0.117420, 0.143541, 0.118256], 'p_i': 10, 'u_i': 1.9405, 'theta': 0.6527},
        {'id': 1, 'e_m': 2.108320, 'e_o_k': [0.037528, 0.039291, 0.015366, 0.040283], 'p_i': 20, 'u_i': 4.0552, 'theta': 0.7429},
        {'id': 2, 'e_m': 11.702031, 'e_o_k': [8.190445], 'p_i': 40, 'u_i': 2.7617, 'theta': 0.7558},
        {'id': 3, 'e_m': 0.158792, 'e_o_k': [0.077227, 0.072528, 0.088256, 0.079572], 'p_i': 10, 'u_i': 2.7259, 'theta': 0.6396},
        {'id': 4, 'e_m': 1.885073, 'e_o_k': [0.010622, 0.019761, 0.023756, 0.030501], 'p_i': 20, 'u_i': 1.5735, 'theta': 0.7435},
        {'id': 5, 'e_m': 3.608580, 'e_o_k': [0.070363, 0.071655, 0.076002, 0.073566], 'p_i': 40, 'u_i': 3.8044, 'theta': 0.7507},
        {'id': 6, 'e_m': 0.232124, 'e_o_k': [0.046202, 0.036902, 0.026302, 0.025659, 0.044467], 'p_i': 10, 'u_i': 4.0908, 'theta': 0.7751},
        {'id': 7, 'e_m': 1.231524, 'e_o_k': [1.014786, 0.621988, 0.826275], 'p_i': 40, 'u_i': 1.8375, 'theta': 0.9393},
        {'id': 8, 'e_m': 3.609970, 'e_o_k': [1.665213], 'p_i': 40, 'u_i': 1.7838, 'theta': 0.8774},
        {'id': 9, 'e_m': 0.143310, 'e_o_k': [0.039499, 0.033049, 0.045206, 0.044406, 0.044052], 'p_i': 10, 'u_i': 3.7010, 'theta': 0.9852},
        {'id': 10, 'e_m': 0.563140, 'e_o_k': [0.172258, 0.387642, 0.566380], 'p_i': 40, 'u_i': 4.7962, 'theta': 0.6125},
        {'id': 11, 'e_m': 0.258860, 'e_o_k': [0.205277, 0.219231], 'p_i': 20, 'u_i': 3.0196, 'theta': 0.7190},
    ]
    B_BUDGET = 48.300003
    return processors, tasks, B_BUDGET
