"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1002, "set": 2, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1002, "set": 2, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.985969, 'e_o_k': [0.245196, 0.216808, 0.219893], 'p_i': 10, 'u_i': 3.6179, 'theta': 0.8765},
        {'id': 1, 'e_m': 0.617057, 'e_o_k': [0.134651, 0.213258, 0.314682, 0.293584, 0.277939], 'p_i': 20, 'u_i': 3.5798, 'theta': 0.7565},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [1.991261, 1.474827, 1.913570, 1.732105, 1.018052], 'p_i': 40, 'u_i': 1.7168, 'theta': 0.6170},
        {'id': 3, 'e_m': 5.472009, 'e_o_k': [4.592710], 'p_i': 40, 'u_i': 1.3361, 'theta': 0.7708},
        {'id': 4, 'e_m': 0.337500, 'e_o_k': [0.137612, 0.125071, 0.135584, 0.122148], 'p_i': 10, 'u_i': 3.8481, 'theta': 0.6441},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
