"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.2, "H": 40, "J": 25, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 193.2, "H": 40, "J": 25, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1084, "set": 84, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 4, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 5, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 6, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
        {'id': 7, 'frequencies': [0.3, 0.6, 0.8, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.235508, 'e_o_k': [0.570086], 'p_i': 10, 'u_i': 4.8474, 'theta': 0.8962},
        {'id': 1, 'e_m': 4.555515, 'e_o_k': [3.809615], 'p_i': 20, 'u_i': 3.1592, 'theta': 0.8862},
        {'id': 2, 'e_m': 11.718483, 'e_o_k': [7.516699, 9.165302], 'p_i': 40, 'u_i': 2.9798, 'theta': 0.9677},
        {'id': 3, 'e_m': 2.334775, 'e_o_k': [0.173053, 0.209958, 0.156793], 'p_i': 10, 'u_i': 4.4850, 'theta': 0.9217},
        {'id': 4, 'e_m': 8.973395, 'e_o_k': [9.607364], 'p_i': 40, 'u_i': 2.4853, 'theta': 0.8358},
        {'id': 5, 'e_m': 20.000000, 'e_o_k': [3.086472, 3.056461, 2.343423], 'p_i': 40, 'u_i': 1.4687, 'theta': 0.6458},
        {'id': 6, 'e_m': 5.000000, 'e_o_k': [0.376883], 'p_i': 10, 'u_i': 2.9303, 'theta': 0.6285},
        {'id': 7, 'e_m': 5.000000, 'e_o_k': [0.148504, 0.246176, 0.235775], 'p_i': 10, 'u_i': 3.4732, 'theta': 0.7872},
        {'id': 8, 'e_m': 8.974254, 'e_o_k': [0.994204, 1.176397, 1.454136], 'p_i': 40, 'u_i': 2.1887, 'theta': 0.6342},
        {'id': 9, 'e_m': 16.047016, 'e_o_k': [4.263078, 4.916763, 5.074685], 'p_i': 40, 'u_i': 2.9013, 'theta': 0.8957},
        {'id': 10, 'e_m': 9.053277, 'e_o_k': [0.304057, 0.310191, 0.444892], 'p_i': 40, 'u_i': 3.9621, 'theta': 0.7605},
        {'id': 11, 'e_m': 17.841415, 'e_o_k': [5.535859, 4.661873], 'p_i': 40, 'u_i': 2.3501, 'theta': 0.9803},
    ]
    B_BUDGET = 193.200000
    return processors, tasks, B_BUDGET
