"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.039987, "H": 80, "J": 33, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.039987, "H": 80, "J": 33, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.284880, 'e_o_k': [0.026846, 0.029793, 0.044191], 'p_i': 10, 'u_i': 2.5588, 'theta': 0.9794},
        {'id': 1, 'e_m': 3.581675, 'e_o_k': [1.333351], 'p_i': 20, 'u_i': 3.8633, 'theta': 0.6749},
        {'id': 2, 'e_m': 5.061499, 'e_o_k': [0.824127, 0.595481, 0.727954, 0.599722], 'p_i': 40, 'u_i': 1.9405, 'theta': 0.6527},
        {'id': 3, 'e_m': 5.448031, 'e_o_k': [2.389017, 2.501259, 0.978200, 2.564405], 'p_i': 80, 'u_i': 4.0552, 'theta': 0.7429},
        {'id': 4, 'e_m': 7.608306, 'e_o_k': [1.507862], 'p_i': 20, 'u_i': 2.7617, 'theta': 0.7558},
        {'id': 5, 'e_m': 13.967165, 'e_o_k': [0.011545, 0.010843, 0.013194, 0.011896], 'p_i': 40, 'u_i': 2.7259, 'theta': 0.6396},
        {'id': 6, 'e_m': 0.577336, 'e_o_k': [0.086481, 0.160882, 0.193410, 0.248326], 'p_i': 10, 'u_i': 1.5735, 'theta': 0.7435},
        {'id': 7, 'e_m': 0.209247, 'e_o_k': [0.017694, 0.018019, 0.019112, 0.018499], 'p_i': 20, 'u_i': 3.8044, 'theta': 0.7507},
    ]
    B_BUDGET = 103.039987
    return processors, tasks, B_BUDGET
