"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 57.959998, "H": 40, "J": 11, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1015, "set": 15, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 57.959998, "H": 40, "J": 11, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1015, "set": 15, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.5, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.5, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.238771, 'e_o_k': [0.283094, 0.203019], 'p_i': 10, 'u_i': 3.5135, 'theta': 0.8991},
        {'id': 1, 'e_m': 1.262728, 'e_o_k': [0.909403, 0.957859, 0.582888], 'p_i': 20, 'u_i': 3.3631, 'theta': 0.6271},
        {'id': 2, 'e_m': 10.142059, 'e_o_k': [1.460092, 1.989895], 'p_i': 40, 'u_i': 3.2123, 'theta': 0.7031},
        {'id': 3, 'e_m': 1.188700, 'e_o_k': [0.491485, 0.459735, 0.592599], 'p_i': 20, 'u_i': 1.4263, 'theta': 0.6722},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [3.220728, 3.127179, 2.960904], 'p_i': 20, 'u_i': 1.8962, 'theta': 0.6130},
    ]
    B_BUDGET = 57.959998
    return processors, tasks, B_BUDGET
