"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599998, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1034, "set": 34, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.599998, "H": 80, "J": 15, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1034, "set": 34, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.8, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.8, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.714917, 'e_o_k': [0.004790, 0.004223], 'p_i': 10, 'u_i': 3.8785, 'theta': 0.7923},
        {'id': 1, 'e_m': 7.533447, 'e_o_k': [2.970155, 2.712790], 'p_i': 20, 'u_i': 3.5984, 'theta': 0.9930},
        {'id': 2, 'e_m': 8.726086, 'e_o_k': [1.005486, 1.503612, 1.794988, 1.490533], 'p_i': 40, 'u_i': 4.9903, 'theta': 0.7041},
        {'id': 3, 'e_m': 10.694701, 'e_o_k': [2.752120, 2.854759], 'p_i': 80, 'u_i': 4.3035, 'theta': 0.8428},
    ]
    B_BUDGET = 96.599998
    return processors, tasks, B_BUDGET
