"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 57.959999, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1059, "set": 59, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 57.959999, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1059, "set": 59, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.45, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.45, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.259361, 'e_o_k': [0.265939, 0.235070, 0.241032], 'p_i': 10, 'u_i': 1.9890, 'theta': 0.7761},
        {'id': 1, 'e_m': 2.464957, 'e_o_k': [2.160962, 1.718748, 1.050204], 'p_i': 20, 'u_i': 4.8992, 'theta': 0.7794},
        {'id': 2, 'e_m': 4.913667, 'e_o_k': [0.094582, 0.086383, 0.079184], 'p_i': 40, 'u_i': 3.6826, 'theta': 0.9884},
        {'id': 3, 'e_m': 10.000000, 'e_o_k': [1.404967, 1.676175, 1.265157], 'p_i': 20, 'u_i': 4.3626, 'theta': 0.8371},
        {'id': 4, 'e_m': 5.118974, 'e_o_k': [4.969982, 5.249279], 'p_i': 40, 'u_i': 2.0007, 'theta': 0.9586},
    ]
    B_BUDGET = 57.959999
    return processors, tasks, B_BUDGET
