"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.860002, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1074, "set": 74, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.860002, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1074, "set": 74, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.55, 0.6, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.55, 0.6, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.336465, 'e_o_k': [0.825694, 0.504657, 0.664262, 0.614332], 'p_i': 10, 'u_i': 2.2591, 'theta': 0.9764},
        {'id': 1, 'e_m': 1.606634, 'e_o_k': [1.316988, 1.896280], 'p_i': 20, 'u_i': 1.1614, 'theta': 0.8471},
        {'id': 2, 'e_m': 1.800785, 'e_o_k': [0.009853, 0.005622, 0.008351, 0.010137], 'p_i': 40, 'u_i': 3.0678, 'theta': 0.8379},
        {'id': 3, 'e_m': 8.626107, 'e_o_k': [3.301268, 2.924610, 2.849888], 'p_i': 40, 'u_i': 1.5410, 'theta': 0.7220},
        {'id': 4, 'e_m': 1.013979, 'e_o_k': [0.448475, 0.344448, 0.439401, 0.486940, 0.308694], 'p_i': 40, 'u_i': 1.7796, 'theta': 0.8963},
    ]
    B_BUDGET = 41.860002
    return processors, tasks, B_BUDGET
