"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 61.180002, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1074, "set": 74, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 61.180002, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1074, "set": 74, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.55, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.55, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.464042], 'p_i': 10, 'u_i': 4.8386, 'theta': 0.6984},
        {'id': 1, 'e_m': 6.466968, 'e_o_k': [0.080533], 'p_i': 20, 'u_i': 3.0219, 'theta': 0.8333},
        {'id': 2, 'e_m': 12.896447, 'e_o_k': [0.208705, 0.129612, 0.234750, 0.228219, 0.217194], 'p_i': 40, 'u_i': 1.3079, 'theta': 0.8661},
        {'id': 3, 'e_m': 13.089563, 'e_o_k': [0.136420, 0.130728, 0.155988], 'p_i': 40, 'u_i': 4.9114, 'theta': 0.9586},
        {'id': 4, 'e_m': 6.540027, 'e_o_k': [0.071374, 0.043443, 0.081851, 0.073908], 'p_i': 20, 'u_i': 2.7091, 'theta': 0.9072},
    ]
    B_BUDGET = 61.180002
    return processors, tasks, B_BUDGET
