"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 115.920002, "H": 80, "J": 23, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1077, "set": 77, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 115.920002, "H": 80, "J": 23, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1077, "set": 77, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.55, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.55, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.204231, 'e_o_k': [0.292629], 'p_i': 10, 'u_i': 1.1771, 'theta': 0.7415},
        {'id': 1, 'e_m': 2.970548, 'e_o_k': [0.140734], 'p_i': 20, 'u_i': 1.8113, 'theta': 0.7017},
        {'id': 2, 'e_m': 1.708711, 'e_o_k': [0.300727, 0.314925, 0.297409, 0.366449], 'p_i': 40, 'u_i': 4.5099, 'theta': 0.8628},
        {'id': 3, 'e_m': 8.078036, 'e_o_k': [0.639324, 0.540269, 0.646452], 'p_i': 80, 'u_i': 3.7049, 'theta': 0.6084},
        {'id': 4, 'e_m': 2.291793, 'e_o_k': [0.072741, 0.076959], 'p_i': 20, 'u_i': 4.0854, 'theta': 0.6073},
        {'id': 5, 'e_m': 9.766496, 'e_o_k': [3.079946], 'p_i': 40, 'u_i': 4.8654, 'theta': 0.8001},
        {'id': 6, 'e_m': 32.199703, 'e_o_k': [0.044034, 0.040855, 0.045003, 0.045258], 'p_i': 80, 'u_i': 3.3108, 'theta': 0.6138},
        {'id': 7, 'e_m': 18.088641, 'e_o_k': [0.335986, 0.540630, 0.495398, 0.405108], 'p_i': 80, 'u_i': 4.7822, 'theta': 0.8136},
    ]
    B_BUDGET = 115.920002
    return processors, tasks, B_BUDGET
