"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300001, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1050, "set": 50, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.300001, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1050, "set": 50, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.707598, 'e_o_k': [0.512872, 0.661021], 'p_i': 10, 'u_i': 2.4311, 'theta': 0.9577},
        {'id': 1, 'e_m': 5.722269, 'e_o_k': [0.288778, 0.404003], 'p_i': 20, 'u_i': 4.9994, 'theta': 0.9538},
        {'id': 2, 'e_m': 0.203178, 'e_o_k': [0.091597, 0.099583, 0.093233, 0.121942], 'p_i': 40, 'u_i': 2.1461, 'theta': 0.7157},
        {'id': 3, 'e_m': 5.009971, 'e_o_k': [9.218053], 'p_i': 40, 'u_i': 3.4377, 'theta': 0.7481},
        {'id': 4, 'e_m': 2.255961, 'e_o_k': [0.627310, 0.426529, 0.498426, 0.594964], 'p_i': 20, 'u_i': 4.4016, 'theta': 0.9050},
    ]
    B_BUDGET = 48.300001
    return processors, tasks, B_BUDGET
