"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300006, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1096, "set": 96, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.300006, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1096, "set": 96, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.5, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.5, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.449436, 'e_o_k': [1.068212, 1.019756], 'p_i': 10, 'u_i': 1.1592, 'theta': 0.8165},
        {'id': 1, 'e_m': 4.666144, 'e_o_k': [0.421151, 0.475664, 0.416040], 'p_i': 20, 'u_i': 3.2685, 'theta': 0.7977},
        {'id': 2, 'e_m': 3.589282, 'e_o_k': [2.123835, 2.840719], 'p_i': 40, 'u_i': 2.4724, 'theta': 0.8701},
        {'id': 3, 'e_m': 4.224652, 'e_o_k': [0.382592, 0.415209], 'p_i': 10, 'u_i': 2.7946, 'theta': 0.9843},
        {'id': 4, 'e_m': 2.191041, 'e_o_k': [0.184576, 0.248756], 'p_i': 20, 'u_i': 1.0370, 'theta': 0.7095},
    ]
    B_BUDGET = 48.300006
    return processors, tasks, B_BUDGET
