"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 77.279997, "H": 80, "J": 24, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1097, "set": 97, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 77.279997, "H": 80, "J": 24, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1097, "set": 97, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.6, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.499050, 'e_o_k': [0.240430, 0.267219, 0.272103, 0.322089], 'p_i': 10, 'u_i': 3.2164, 'theta': 0.7713},
        {'id': 1, 'e_m': 0.177196, 'e_o_k': [0.061028, 0.068233, 0.067253, 0.066233], 'p_i': 20, 'u_i': 2.7921, 'theta': 0.9654},
        {'id': 2, 'e_m': 4.391683, 'e_o_k': [8.763885], 'p_i': 40, 'u_i': 2.8611, 'theta': 0.9165},
        {'id': 3, 'e_m': 2.600995, 'e_o_k': [1.157616, 0.995400, 0.885028, 1.685335], 'p_i': 80, 'u_i': 1.1240, 'theta': 0.9698},
        {'id': 4, 'e_m': 2.462113, 'e_o_k': [1.237499, 1.039855, 1.232035, 1.167600], 'p_i': 40, 'u_i': 2.1650, 'theta': 0.7070},
        {'id': 5, 'e_m': 0.590234, 'e_o_k': [0.418911, 0.548065, 0.497464], 'p_i': 20, 'u_i': 4.0198, 'theta': 0.9249},
        {'id': 6, 'e_m': 3.986444, 'e_o_k': [3.097549, 2.379604, 2.240725], 'p_i': 80, 'u_i': 3.2939, 'theta': 0.8934},
        {'id': 7, 'e_m': 2.321424, 'e_o_k': [1.660129, 1.406012, 1.410617], 'p_i': 40, 'u_i': 2.8069, 'theta': 0.7287},
    ]
    B_BUDGET = 77.279997
    return processors, tasks, B_BUDGET
