"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 90.160004, "H": 80, "J": 30, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1022, "set": 22, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.4, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 90.160004, "H": 80, "J": 30, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1022, "set": 22, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.4, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.55, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.55, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.395878, 'e_o_k': [0.472338, 0.407751], 'p_i': 10, 'u_i': 2.3987, 'theta': 0.8131},
        {'id': 1, 'e_m': 2.562547, 'e_o_k': [0.979669], 'p_i': 20, 'u_i': 4.4502, 'theta': 0.8723},
        {'id': 2, 'e_m': 1.297571, 'e_o_k': [1.309011, 1.286130], 'p_i': 40, 'u_i': 3.9986, 'theta': 0.8953},
        {'id': 3, 'e_m': 1.719885, 'e_o_k': [0.257608, 0.161368, 0.197567], 'p_i': 80, 'u_i': 3.6474, 'theta': 0.7325},
        {'id': 4, 'e_m': 1.333426, 'e_o_k': [0.253319, 0.275519, 0.325922], 'p_i': 10, 'u_i': 2.3475, 'theta': 0.8364},
        {'id': 5, 'e_m': 8.940451, 'e_o_k': [1.840224], 'p_i': 40, 'u_i': 1.8488, 'theta': 0.6616},
        {'id': 6, 'e_m': 1.469555, 'e_o_k': [0.067580], 'p_i': 20, 'u_i': 1.1416, 'theta': 0.7828},
        {'id': 7, 'e_m': 3.841230, 'e_o_k': [1.127608, 1.909193, 1.408144], 'p_i': 80, 'u_i': 3.9916, 'theta': 0.7626},
    ]
    B_BUDGET = 90.160004
    return processors, tasks, B_BUDGET
