"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299999, "H": 40, "J": 11, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.299999, "H": 40, "J": 11, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1064, "set": 64, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.4, 0.45, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.628854, 'e_o_k': [0.299310, 0.261947, 0.336738], 'p_i': 10, 'u_i': 3.8451, 'theta': 0.7690},
        {'id': 1, 'e_m': 3.442570, 'e_o_k': [1.484978, 1.681914], 'p_i': 20, 'u_i': 1.5900, 'theta': 0.6501},
        {'id': 2, 'e_m': 2.841967, 'e_o_k': [0.062610, 0.056111, 0.071817], 'p_i': 40, 'u_i': 4.9710, 'theta': 0.6282},
        {'id': 3, 'e_m': 6.235652, 'e_o_k': [1.655676], 'p_i': 20, 'u_i': 2.1505, 'theta': 0.9031},
        {'id': 4, 'e_m': 1.643086, 'e_o_k': [0.619158, 0.806205, 0.616749, 0.446689, 0.797372], 'p_i': 20, 'u_i': 4.7116, 'theta': 0.7912},
    ]
    B_BUDGET = 48.299999
    return processors, tasks, B_BUDGET
