"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 54.740002, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 54.740002, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.127298, 'e_o_k': [0.151398, 0.141375, 0.131354], 'p_i': 10, 'u_i': 2.0965, 'theta': 0.7617},
        {'id': 1, 'e_m': 8.068877, 'e_o_k': [0.872818, 0.682597, 0.757952, 0.678965], 'p_i': 20, 'u_i': 2.3485, 'theta': 0.9316},
        {'id': 2, 'e_m': 3.716278, 'e_o_k': [0.222111, 0.237543, 0.209406, 0.194038, 0.080422], 'p_i': 40, 'u_i': 2.2686, 'theta': 0.7738},
        {'id': 3, 'e_m': 10.000000, 'e_o_k': [0.281050, 0.374794, 0.273637], 'p_i': 20, 'u_i': 4.9053, 'theta': 0.9955},
        {'id': 4, 'e_m': 0.909194, 'e_o_k': [0.183473, 0.195614], 'p_i': 10, 'u_i': 4.9995, 'theta': 0.9882},
    ]
    B_BUDGET = 54.740002
    return processors, tasks, B_BUDGET
