"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 61.180002, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 61.180002, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1047, "set": 47, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.5, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.020812, 'e_o_k': [0.050466, 0.047125, 0.043785], 'p_i': 10, 'u_i': 2.0965, 'theta': 0.7617},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [0.290939, 0.227532, 0.252651, 0.226322], 'p_i': 20, 'u_i': 2.3485, 'theta': 0.9316},
        {'id': 2, 'e_m': 7.863785, 'e_o_k': [0.074037, 0.079181, 0.069802, 0.064679, 0.026807], 'p_i': 40, 'u_i': 2.2686, 'theta': 0.7738},
        {'id': 3, 'e_m': 10.000000, 'e_o_k': [0.093683, 0.124931, 0.091212], 'p_i': 20, 'u_i': 4.9053, 'theta': 0.9955},
        {'id': 4, 'e_m': 2.013242, 'e_o_k': [0.061158, 0.065205], 'p_i': 10, 'u_i': 4.9995, 'theta': 0.9882},
    ]
    B_BUDGET = 61.180002
    return processors, tasks, B_BUDGET
