"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 61.180002, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1020, "set": 20, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 61.180002, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1020, "set": 20, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.55, 0.65, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.55, 0.65, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.190077, 'e_o_k': [0.216957, 0.182987], 'p_i': 10, 'u_i': 3.4913, 'theta': 0.7386},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [0.087543], 'p_i': 20, 'u_i': 4.9398, 'theta': 0.8732},
        {'id': 2, 'e_m': 12.770277, 'e_o_k': [1.197715], 'p_i': 40, 'u_i': 1.7323, 'theta': 0.6718},
        {'id': 3, 'e_m': 12.798906, 'e_o_k': [0.245670, 0.420482, 0.291594], 'p_i': 40, 'u_i': 1.1923, 'theta': 0.9482},
        {'id': 4, 'e_m': 6.835255, 'e_o_k': [0.034839], 'p_i': 20, 'u_i': 4.6754, 'theta': 0.8903},
    ]
    B_BUDGET = 61.180002
    return processors, tasks, B_BUDGET
