"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 38.639999, "H": 40, "J": 11, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1052, "set": 52, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 38.639999, "H": 40, "J": 11, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1052, "set": 52, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.55, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.55, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.266353, 'e_o_k': [0.115909, 0.153823, 0.158278], 'p_i': 10, 'u_i': 1.6290, 'theta': 0.8832},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [0.098789, 0.079489, 0.094212, 0.114910], 'p_i': 20, 'u_i': 1.9051, 'theta': 0.8688},
        {'id': 2, 'e_m': 3.372955, 'e_o_k': [0.062919, 0.038895, 0.066537, 0.043247], 'p_i': 40, 'u_i': 3.8843, 'theta': 0.9025},
        {'id': 3, 'e_m': 0.905568, 'e_o_k': [0.215173, 0.360537, 0.324577], 'p_i': 20, 'u_i': 4.2171, 'theta': 0.7756},
        {'id': 4, 'e_m': 0.875247, 'e_o_k': [1.750495], 'p_i': 20, 'u_i': 2.3155, 'theta': 0.8832},
    ]
    B_BUDGET = 38.639999
    return processors, tasks, B_BUDGET
