"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.860001, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1078, "set": 78, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.860001, "H": 40, "J": 11, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1078, "set": 78, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.5, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.5, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.559151, 'e_o_k': [0.536443, 0.581859], 'p_i': 10, 'u_i': 2.8624, 'theta': 0.8572},
        {'id': 1, 'e_m': 2.739843, 'e_o_k': [2.382349, 1.835016], 'p_i': 20, 'u_i': 4.5379, 'theta': 0.9717},
        {'id': 2, 'e_m': 0.852234, 'e_o_k': [1.704469], 'p_i': 40, 'u_i': 2.3623, 'theta': 0.7099},
        {'id': 3, 'e_m': 2.327872, 'e_o_k': [0.290963], 'p_i': 20, 'u_i': 3.8291, 'theta': 0.8292},
        {'id': 4, 'e_m': 5.387866, 'e_o_k': [6.402834], 'p_i': 20, 'u_i': 4.1768, 'theta': 0.8798},
    ]
    B_BUDGET = 41.860001
    return processors, tasks, B_BUDGET
