"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 109.479996, "H": 80, "J": 32, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1076, "set": 76, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 109.479996, "H": 80, "J": 32, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1076, "set": 76, "sweep": "u_mand_factor", "u_mand_factor": 0.7, "u_opt_factor": 0.5, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.55, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.55, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.107963, 'e_o_k': [0.415110], 'p_i': 10, 'u_i': 1.9579, 'theta': 0.6499},
        {'id': 1, 'e_m': 3.518790, 'e_o_k': [1.131368, 1.327845], 'p_i': 20, 'u_i': 1.8876, 'theta': 0.6865},
        {'id': 2, 'e_m': 6.200949, 'e_o_k': [0.402687, 0.423742, 0.349551], 'p_i': 40, 'u_i': 1.7896, 'theta': 0.8145},
        {'id': 3, 'e_m': 31.167119, 'e_o_k': [0.082697], 'p_i': 80, 'u_i': 4.6296, 'theta': 0.7171},
        {'id': 4, 'e_m': 0.425811, 'e_o_k': [0.039360, 0.075148], 'p_i': 10, 'u_i': 4.3961, 'theta': 0.9215},
        {'id': 5, 'e_m': 11.986467, 'e_o_k': [0.729910], 'p_i': 80, 'u_i': 3.7475, 'theta': 0.8610},
        {'id': 6, 'e_m': 0.196386, 'e_o_k': [0.054326, 0.036183, 0.064863], 'p_i': 20, 'u_i': 2.0620, 'theta': 0.8239},
        {'id': 7, 'e_m': 1.328404, 'e_o_k': [0.436809, 0.397237, 0.700991], 'p_i': 20, 'u_i': 2.8583, 'theta': 0.8574},
    ]
    B_BUDGET = 109.479996
    return processors, tasks, B_BUDGET
