"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599997, "H": 80, "J": 36, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1057, "set": 57, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 96.599997, "H": 80, "J": 36, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1057, "set": 57, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.794198, 'e_o_k': [0.527144, 0.323852, 0.507672, 0.229728], 'p_i': 10, 'u_i': 2.9058, 'theta': 0.7849},
        {'id': 1, 'e_m': 0.216021, 'e_o_k': [0.011183, 0.007745, 0.010217], 'p_i': 20, 'u_i': 4.3220, 'theta': 0.7183},
        {'id': 2, 'e_m': 0.055981, 'e_o_k': [0.056499, 0.055463], 'p_i': 40, 'u_i': 1.0030, 'theta': 0.8214},
        {'id': 3, 'e_m': 8.708366, 'e_o_k': [0.580903, 0.464034], 'p_i': 80, 'u_i': 4.0571, 'theta': 0.9400},
        {'id': 4, 'e_m': 0.324474, 'e_o_k': [0.253922, 0.395026], 'p_i': 20, 'u_i': 2.2408, 'theta': 0.9127},
        {'id': 5, 'e_m': 1.882906, 'e_o_k': [0.748546], 'p_i': 20, 'u_i': 1.5632, 'theta': 0.7263},
        {'id': 6, 'e_m': 34.927278, 'e_o_k': [7.815635, 7.992516], 'p_i': 80, 'u_i': 2.1337, 'theta': 0.9681},
        {'id': 7, 'e_m': 1.289205, 'e_o_k': [0.005417], 'p_i': 40, 'u_i': 3.5977, 'theta': 0.9689},
        {'id': 8, 'e_m': 0.217252, 'e_o_k': [0.076837, 0.091279, 0.092774], 'p_i': 10, 'u_i': 4.0726, 'theta': 0.6467},
        {'id': 9, 'e_m': 7.944391, 'e_o_k': [1.205652], 'p_i': 40, 'u_i': 3.0102, 'theta': 0.6053},
    ]
    B_BUDGET = 96.599997
    return processors, tasks, B_BUDGET
