"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 103.03999, "H": 80, "J": 32, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1076, "set": 76, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 103.03999, "H": 80, "J": 32, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1076, "set": 76, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.55, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.55, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.521111, 'e_o_k': [0.553479], 'p_i': 10, 'u_i': 1.9579, 'theta': 0.6499},
        {'id': 1, 'e_m': 3.016105, 'e_o_k': [1.508491, 1.770460], 'p_i': 20, 'u_i': 1.8876, 'theta': 0.6865},
        {'id': 2, 'e_m': 5.315099, 'e_o_k': [0.536916, 0.564989, 0.466068], 'p_i': 40, 'u_i': 1.7896, 'theta': 0.8145},
        {'id': 3, 'e_m': 26.714673, 'e_o_k': [0.110262], 'p_i': 80, 'u_i': 4.6296, 'theta': 0.7171},
        {'id': 4, 'e_m': 0.364981, 'e_o_k': [0.052480, 0.100197], 'p_i': 10, 'u_i': 4.3961, 'theta': 0.9215},
        {'id': 5, 'e_m': 10.274114, 'e_o_k': [0.973214], 'p_i': 80, 'u_i': 3.7475, 'theta': 0.8610},
        {'id': 6, 'e_m': 0.168331, 'e_o_k': [0.072435, 0.048244, 0.086485], 'p_i': 20, 'u_i': 2.0620, 'theta': 0.8239},
        {'id': 7, 'e_m': 1.138632, 'e_o_k': [0.582412, 0.529649, 0.934655], 'p_i': 20, 'u_i': 2.8583, 'theta': 0.8574},
    ]
    B_BUDGET = 103.039990
    return processors, tasks, B_BUDGET
