"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299999, "H": 40, "J": 13, "factor": "n_prc", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1065, "set": 65, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 48.299999, "H": 40, "J": 13, "factor": "n_prc", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1065, "set": 65, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.45, 0.55, 0.85, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.45, 0.55, 0.85, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.249496, 'e_o_k': [0.149692, 0.156103, 0.156042], 'p_i': 10, 'u_i': 3.2805, 'theta': 0.9616},
        {'id': 1, 'e_m': 1.146227, 'e_o_k': [0.747951, 0.677618, 0.866884], 'p_i': 20, 'u_i': 2.8068, 'theta': 0.7496},
        {'id': 2, 'e_m': 10.260369, 'e_o_k': [0.363987, 0.823125], 'p_i': 40, 'u_i': 1.4984, 'theta': 0.9280},
        {'id': 3, 'e_m': 4.562597, 'e_o_k': [0.913818, 0.869542, 0.843877], 'p_i': 10, 'u_i': 3.0481, 'theta': 0.9653},
        {'id': 4, 'e_m': 2.099401, 'e_o_k': [0.224900, 0.326643, 0.384301], 'p_i': 20, 'u_i': 3.9112, 'theta': 0.6238},
    ]
    B_BUDGET = 48.299999
    return processors, tasks, B_BUDGET
