"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600016, "H": 80, "J": 44, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1041, "set": 41, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 96.600016, "H": 80, "J": 44, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1041, "set": 41, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.6, 0.65, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.6, 0.65, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.833907, 'e_o_k': [0.138246, 0.165546], 'p_i': 10, 'u_i': 4.7806, 'theta': 0.7207},
        {'id': 1, 'e_m': 3.131556, 'e_o_k': [0.124791, 0.110960, 0.132272, 0.120468], 'p_i': 20, 'u_i': 1.5284, 'theta': 0.7108},
        {'id': 2, 'e_m': 3.170322, 'e_o_k': [2.049900, 1.660439], 'p_i': 40, 'u_i': 1.6373, 'theta': 0.7383},
        {'id': 3, 'e_m': 3.407865, 'e_o_k': [0.129698, 0.153890, 0.115306, 0.154610], 'p_i': 80, 'u_i': 2.8197, 'theta': 0.7135},
        {'id': 4, 'e_m': 2.280450, 'e_o_k': [0.480892, 0.351298, 0.255023, 0.446291], 'p_i': 10, 'u_i': 1.7006, 'theta': 0.8762},
        {'id': 5, 'e_m': 0.061947, 'e_o_k': [0.123893], 'p_i': 20, 'u_i': 4.4755, 'theta': 0.9143},
        {'id': 6, 'e_m': 0.251870, 'e_o_k': [0.221986, 0.148631, 0.133123], 'p_i': 10, 'u_i': 4.3237, 'theta': 0.6752},
        {'id': 7, 'e_m': 4.980771, 'e_o_k': [2.611146], 'p_i': 80, 'u_i': 1.9950, 'theta': 0.7300},
        {'id': 8, 'e_m': 0.286731, 'e_o_k': [0.163920, 0.089762], 'p_i': 20, 'u_i': 2.3940, 'theta': 0.9813},
        {'id': 9, 'e_m': 6.104994, 'e_o_k': [0.402425, 0.464202, 0.938906], 'p_i': 20, 'u_i': 1.9539, 'theta': 0.7511},
    ]
    B_BUDGET = 96.600016
    return processors, tasks, B_BUDGET
