"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599994, "H": 80, "J": 28, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1068, "set": 68, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 96.599994, "H": 80, "J": 28, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1068, "set": 68, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.55, 0.6, 0.65, 0.7, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.55, 0.6, 0.65, 0.7, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.392862, 'e_o_k': [0.163844, 0.196513, 0.218546, 0.206821], 'p_i': 10, 'u_i': 3.7894, 'theta': 0.8381},
        {'id': 1, 'e_m': 8.095287, 'e_o_k': [0.373473, 0.468388, 0.318384, 0.200750], 'p_i': 20, 'u_i': 4.9498, 'theta': 0.9370},
        {'id': 2, 'e_m': 6.551865, 'e_o_k': [0.689120, 0.523816, 0.859494], 'p_i': 40, 'u_i': 4.0485, 'theta': 0.7015},
        {'id': 3, 'e_m': 0.062319, 'e_o_k': [0.124638], 'p_i': 80, 'u_i': 3.7125, 'theta': 0.9618},
        {'id': 4, 'e_m': 0.787564, 'e_o_k': [1.575128], 'p_i': 40, 'u_i': 1.9609, 'theta': 0.8979},
        {'id': 5, 'e_m': 11.698055, 'e_o_k': [2.260376, 2.518637], 'p_i': 80, 'u_i': 2.0021, 'theta': 0.7945},
        {'id': 6, 'e_m': 4.212966, 'e_o_k': [3.046327], 'p_i': 40, 'u_i': 3.2718, 'theta': 0.8917},
        {'id': 7, 'e_m': 1.201349, 'e_o_k': [0.347500, 0.486007, 0.413843], 'p_i': 10, 'u_i': 1.5461, 'theta': 0.6536},
    ]
    B_BUDGET = 96.599994
    return processors, tasks, B_BUDGET
