"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1075, "set": 75, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1075, "set": 75, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 1.0]},
        {'id': 1, 'frequencies': [0.3, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.630269, 'e_o_k': [0.030622], 'p_i': 10, 'u_i': 1.8498, 'theta': 0.6137},
        {'id': 1, 'e_m': 2.729000, 'e_o_k': [2.362047, 2.774115], 'p_i': 20, 'u_i': 1.9231, 'theta': 0.8930},
        {'id': 2, 'e_m': 14.246213, 'e_o_k': [2.816339], 'p_i': 40, 'u_i': 2.7392, 'theta': 0.8056},
        {'id': 3, 'e_m': 1.664488, 'e_o_k': [0.333900, 0.204707], 'p_i': 10, 'u_i': 4.1040, 'theta': 0.9057},
        {'id': 4, 'e_m': 3.116760, 'e_o_k': [4.634422], 'p_i': 40, 'u_i': 1.8392, 'theta': 0.9115},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
