"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599994, "H": 80, "J": 29, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1080, "set": 80, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 96.599994, "H": 80, "J": 29, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1080, "set": 80, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 0.65, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.5, 0.65, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.209640, 'e_o_k': [1.665559], 'p_i': 10, 'u_i': 1.6134, 'theta': 0.7374},
        {'id': 1, 'e_m': 3.895657, 'e_o_k': [0.213466, 0.295746, 0.234975, 0.233643], 'p_i': 20, 'u_i': 2.0894, 'theta': 0.7176},
        {'id': 2, 'e_m': 0.189282, 'e_o_k': [0.378564], 'p_i': 40, 'u_i': 4.6717, 'theta': 0.9021},
        {'id': 3, 'e_m': 9.554635, 'e_o_k': [0.345244, 0.344239, 0.223135, 0.287826], 'p_i': 80, 'u_i': 3.0219, 'theta': 0.8597},
        {'id': 4, 'e_m': 1.321126, 'e_o_k': [1.263355], 'p_i': 20, 'u_i': 3.3614, 'theta': 0.8533},
        {'id': 5, 'e_m': 8.783240, 'e_o_k': [0.558513, 0.644636, 0.453558], 'p_i': 80, 'u_i': 4.2255, 'theta': 0.7997},
        {'id': 6, 'e_m': 0.475682, 'e_o_k': [0.590144], 'p_i': 20, 'u_i': 2.5511, 'theta': 0.6909},
        {'id': 7, 'e_m': 2.881245, 'e_o_k': [0.439946, 0.713727, 0.669864], 'p_i': 80, 'u_i': 2.7348, 'theta': 0.7952},
        {'id': 8, 'e_m': 0.488903, 'e_o_k': [0.513846, 0.463960], 'p_i': 40, 'u_i': 4.6056, 'theta': 0.6120},
        {'id': 9, 'e_m': 12.488763, 'e_o_k': [3.978390], 'p_i': 40, 'u_i': 4.9515, 'theta': 0.6716},
    ]
    B_BUDGET = 96.599994
    return processors, tasks, B_BUDGET
