"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1045, "set": 45, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1045, "set": 45, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.45, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.45, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.415131, 'e_o_k': [0.789505], 'p_i': 10, 'u_i': 4.1665, 'theta': 0.9942},
        {'id': 1, 'e_m': 2.353613, 'e_o_k': [1.717450, 1.537775], 'p_i': 20, 'u_i': 1.3993, 'theta': 0.8163},
        {'id': 2, 'e_m': 9.239283, 'e_o_k': [0.747406, 1.042933, 0.721364], 'p_i': 40, 'u_i': 1.6178, 'theta': 0.9884},
        {'id': 3, 'e_m': 10.097886, 'e_o_k': [3.081795, 2.196605], 'p_i': 40, 'u_i': 2.0853, 'theta': 0.6018},
        {'id': 4, 'e_m': 7.147541, 'e_o_k': [0.603330, 0.667384], 'p_i': 20, 'u_i': 2.8702, 'theta': 0.7315},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
