"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 11, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 11, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 4, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.55, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.55, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.415671, 0.438763, 0.451350, 0.495050, 0.315881], 'p_i': 10, 'u_i': 2.7562, 'theta': 0.7422},
        {'id': 1, 'e_m': 5.634964, 'e_o_k': [3.550284], 'p_i': 20, 'u_i': 4.9381, 'theta': 0.6435},
        {'id': 2, 'e_m': 4.326501, 'e_o_k': [2.426797], 'p_i': 40, 'u_i': 2.7456, 'theta': 0.6511},
        {'id': 3, 'e_m': 1.100893, 'e_o_k': [0.161797, 0.103641, 0.116146, 0.119859], 'p_i': 10, 'u_i': 4.1188, 'theta': 0.8447},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
