"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 54.740001, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1018, "set": 18, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.7, "value": "0.7", "xi": 0.6}
"""

_SPEC = '{"B": 54.740001, "H": 40, "J": 10, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1018, "set": 18, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.7, "value": "0.7", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.149297, 'e_o_k': [0.562598, 0.343527, 0.488795], 'p_i': 10, 'u_i': 2.5410, 'theta': 0.8330},
        {'id': 1, 'e_m': 0.952159, 'e_o_k': [0.335256, 0.469126], 'p_i': 20, 'u_i': 2.5502, 'theta': 0.9929},
        {'id': 2, 'e_m': 1.288039, 'e_o_k': [1.986644], 'p_i': 40, 'u_i': 1.8035, 'theta': 0.7273},
        {'id': 3, 'e_m': 6.720054, 'e_o_k': [0.788421, 0.944935], 'p_i': 40, 'u_i': 4.6367, 'theta': 0.9358},
        {'id': 4, 'e_m': 8.745202, 'e_o_k': [8.545777], 'p_i': 20, 'u_i': 1.4892, 'theta': 0.9087},
    ]
    B_BUDGET = 54.740001
    return processors, tasks, B_BUDGET
