"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600006, "H": 80, "J": 64, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1058, "set": 58, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 96.600006, "H": 80, "J": 64, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1058, "set": 58, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.4, 0.45, 0.5, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.4, 0.45, 0.5, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.046154, 'e_o_k': [0.437390, 0.371872, 0.477484], 'p_i': 10, 'u_i': 2.0427, 'theta': 0.6454},
        {'id': 1, 'e_m': 0.359799, 'e_o_k': [0.045682, 0.030985], 'p_i': 20, 'u_i': 1.1462, 'theta': 0.6406},
        {'id': 2, 'e_m': 7.792455, 'e_o_k': [1.502689, 1.624684, 1.206344], 'p_i': 40, 'u_i': 3.4919, 'theta': 0.8589},
        {'id': 3, 'e_m': 8.694310, 'e_o_k': [0.166766, 0.137802, 0.169692], 'p_i': 80, 'u_i': 4.0226, 'theta': 0.8969},
        {'id': 4, 'e_m': 0.192574, 'e_o_k': [0.145791, 0.101878, 0.137479], 'p_i': 20, 'u_i': 4.7297, 'theta': 0.8990},
        {'id': 5, 'e_m': 3.006607, 'e_o_k': [0.460070], 'p_i': 20, 'u_i': 4.9096, 'theta': 0.6963},
        {'id': 6, 'e_m': 0.183069, 'e_o_k': [0.112858, 0.147378, 0.105902], 'p_i': 10, 'u_i': 1.8429, 'theta': 0.9045},
        {'id': 7, 'e_m': 0.829224, 'e_o_k': [0.009345, 0.009564, 0.007040], 'p_i': 10, 'u_i': 2.1098, 'theta': 0.6497},
        {'id': 8, 'e_m': 0.551052, 'e_o_k': [0.193986, 0.358953, 0.216330], 'p_i': 10, 'u_i': 2.9885, 'theta': 0.9911},
        {'id': 9, 'e_m': 0.171585, 'e_o_k': [0.205592, 0.137577], 'p_i': 10, 'u_i': 3.1065, 'theta': 0.6837},
        {'id': 10, 'e_m': 5.260036, 'e_o_k': [0.760547, 0.695285, 0.759277, 0.634408], 'p_i': 80, 'u_i': 3.6438, 'theta': 0.9760},
        {'id': 11, 'e_m': 0.747020, 'e_o_k': [0.055054, 0.054114, 0.085751, 0.053966], 'p_i': 10, 'u_i': 1.7291, 'theta': 0.6288},
    ]
    B_BUDGET = 96.600006
    return processors, tasks, B_BUDGET
