"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 115.919998, "H": 80, "J": 27, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1091, "set": 91, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 115.919998, "H": 80, "J": 27, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1091, "set": 91, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.8, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.5, 0.55, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.5, 0.55, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.854220, 'e_o_k': [0.009596, 0.010063, 0.009343, 0.008202], 'p_i': 10, 'u_i': 4.6593, 'theta': 0.9467},
        {'id': 1, 'e_m': 1.943000, 'e_o_k': [0.888769], 'p_i': 20, 'u_i': 1.5808, 'theta': 0.7497},
        {'id': 2, 'e_m': 7.217549, 'e_o_k': [0.850836, 0.859189, 0.849764, 1.000525], 'p_i': 40, 'u_i': 2.1180, 'theta': 0.9116},
        {'id': 3, 'e_m': 8.981682, 'e_o_k': [3.135145, 3.304692, 3.400256, 3.296873], 'p_i': 80, 'u_i': 2.6598, 'theta': 0.9893},
        {'id': 4, 'e_m': 0.801928, 'e_o_k': [1.603857], 'p_i': 40, 'u_i': 1.4707, 'theta': 0.6443},
        {'id': 5, 'e_m': 6.328250, 'e_o_k': [2.093264, 1.638812, 0.861068, 1.651765], 'p_i': 20, 'u_i': 3.0479, 'theta': 0.9130},
        {'id': 6, 'e_m': 2.448212, 'e_o_k': [0.861227, 1.311166], 'p_i': 20, 'u_i': 2.7003, 'theta': 0.9194},
        {'id': 7, 'e_m': 2.633876, 'e_o_k': [1.506389], 'p_i': 40, 'u_i': 3.7721, 'theta': 0.9569},
    ]
    B_BUDGET = 115.919998
    return processors, tasks, B_BUDGET
