"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 61.180003, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1002, "set": 2, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 61.180003, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1002, "set": 2, "sweep": "u_mand_factor", "u_mand_factor": 0.9, "u_opt_factor": 0.5, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.45, 0.55, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.45, 0.55, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.023785, 0.036030, 0.026463], 'p_i': 10, 'u_i': 3.6773, 'theta': 0.8978},
        {'id': 1, 'e_m': 7.512436, 'e_o_k': [0.060640, 0.091764, 0.078798, 0.072045], 'p_i': 20, 'u_i': 2.0136, 'theta': 0.7966},
        {'id': 2, 'e_m': 8.776204, 'e_o_k': [0.115946], 'p_i': 40, 'u_i': 2.0964, 'theta': 0.6572},
        {'id': 3, 'e_m': 5.000000, 'e_o_k': [0.146809, 0.186119, 0.234624], 'p_i': 10, 'u_i': 3.7009, 'theta': 0.8302},
        {'id': 4, 'e_m': 4.099462, 'e_o_k': [0.119259, 0.119190, 0.092673], 'p_i': 20, 'u_i': 4.2627, 'theta': 0.9821},
    ]
    B_BUDGET = 61.180003
    return processors, tasks, B_BUDGET
