"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.6, "H": 40, "J": 17, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1046, "set": 46, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.6, "H": 40, "J": 17, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1046, "set": 46, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.65, 0.75, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.65, 0.75, 0.9, 1.0]},
        {'id': 2, 'frequencies': [0.35, 0.65, 0.75, 0.9, 1.0]},
        {'id': 3, 'frequencies': [0.35, 0.65, 0.75, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.865039, 'e_o_k': [2.215248, 1.838963], 'p_i': 10, 'u_i': 1.5400, 'theta': 0.8030},
        {'id': 1, 'e_m': 5.749451, 'e_o_k': [3.445304], 'p_i': 20, 'u_i': 2.2764, 'theta': 0.8579},
        {'id': 2, 'e_m': 11.508757, 'e_o_k': [0.803066, 0.795179], 'p_i': 40, 'u_i': 1.4500, 'theta': 0.9397},
        {'id': 3, 'e_m': 6.878144, 'e_o_k': [0.423480, 0.704768, 0.936836], 'p_i': 20, 'u_i': 3.2272, 'theta': 0.8506},
        {'id': 4, 'e_m': 5.000000, 'e_o_k': [1.172104], 'p_i': 10, 'u_i': 2.7700, 'theta': 0.7410},
        {'id': 5, 'e_m': 2.943974, 'e_o_k': [0.541580, 0.455729, 0.621621], 'p_i': 10, 'u_i': 2.7848, 'theta': 0.6882},
    ]
    B_BUDGET = 96.600000
    return processors, tasks, B_BUDGET
