"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 77.280003, "H": 80, "J": 26, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 77.280003, "H": 80, "J": 26, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.2, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.397400, 'e_o_k': [0.250853, 0.232230, 0.160207, 0.306588], 'p_i': 10, 'u_i': 4.8579, 'theta': 0.6157},
        {'id': 1, 'e_m': 2.063860, 'e_o_k': [0.014593, 0.017735, 0.021042], 'p_i': 20, 'u_i': 2.8364, 'theta': 0.9742},
        {'id': 2, 'e_m': 6.282269, 'e_o_k': [0.080851, 0.144832, 0.123826, 0.142870], 'p_i': 40, 'u_i': 2.5400, 'theta': 0.8202},
        {'id': 3, 'e_m': 6.871639, 'e_o_k': [0.226278, 0.189106], 'p_i': 80, 'u_i': 3.1655, 'theta': 0.7901},
        {'id': 4, 'e_m': 3.100796, 'e_o_k': [0.304362, 0.423275], 'p_i': 20, 'u_i': 1.9656, 'theta': 0.6665},
        {'id': 5, 'e_m': 5.009414, 'e_o_k': [0.618275, 0.580251, 0.590694, 0.693245], 'p_i': 80, 'u_i': 3.5220, 'theta': 0.7736},
        {'id': 6, 'e_m': 0.124401, 'e_o_k': [0.248802], 'p_i': 40, 'u_i': 2.3507, 'theta': 0.9362},
        {'id': 7, 'e_m': 1.866946, 'e_o_k': [0.146518, 0.077667], 'p_i': 20, 'u_i': 1.9884, 'theta': 0.7576},
    ]
    B_BUDGET = 77.280003
    return processors, tasks, B_BUDGET
