"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 34.499999, "H": 40, "J": 10, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.5, "seed": 1014, "set": 14, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}
"""

_SPEC = '{"B": 34.499999, "H": 40, "J": 10, "factor": "rho", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.5, "seed": 1014, "set": 14, "sweep": "rho", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.5, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.5, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.066787, 'e_o_k': [0.133574], 'p_i': 10, 'u_i': 1.9931, 'theta': 0.9545},
        {'id': 1, 'e_m': 2.908475, 'e_o_k': [0.370306, 0.421203], 'p_i': 20, 'u_i': 3.1845, 'theta': 0.6744},
        {'id': 2, 'e_m': 10.744403, 'e_o_k': [3.450266], 'p_i': 40, 'u_i': 1.2190, 'theta': 0.7111},
        {'id': 3, 'e_m': 5.643439, 'e_o_k': [1.123196, 1.498247, 1.700526], 'p_i': 20, 'u_i': 4.5050, 'theta': 0.8180},
        {'id': 4, 'e_m': 11.884621, 'e_o_k': [1.835483, 1.877050, 2.075948], 'p_i': 40, 'u_i': 2.8305, 'theta': 0.6442},
    ]
    B_BUDGET = 34.499999
    return processors, tasks, B_BUDGET
