"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 51.52, "H": 40, "J": 11, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1012, "set": 12, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.6, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 51.52, "H": 40, "J": 11, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1012, "set": 12, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.6, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.45, 0.55, 0.6, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.45, 0.55, 0.6, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.018280, 'e_o_k': [0.535788, 0.263707, 0.313101], 'p_i': 10, 'u_i': 1.6648, 'theta': 0.8453},
        {'id': 1, 'e_m': 4.387595, 'e_o_k': [2.617260, 3.065054, 2.251640], 'p_i': 20, 'u_i': 4.2991, 'theta': 0.7144},
        {'id': 2, 'e_m': 6.285991, 'e_o_k': [1.202699], 'p_i': 40, 'u_i': 4.3793, 'theta': 0.9813},
        {'id': 3, 'e_m': 3.704060, 'e_o_k': [0.140763, 0.561499, 0.407203], 'p_i': 20, 'u_i': 1.9020, 'theta': 0.8013},
        {'id': 4, 'e_m': 6.728790, 'e_o_k': [0.070609, 0.059430], 'p_i': 20, 'u_i': 4.0286, 'theta': 0.6247},
    ]
    B_BUDGET = 51.520000
    return processors, tasks, B_BUDGET
