"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599987, "H": 80, "J": 44, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1054, "set": 54, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 96.599987, "H": 80, "J": 44, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1054, "set": 54, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.322458, 'e_o_k': [0.219401, 0.110500], 'p_i': 10, 'u_i': 1.8773, 'theta': 0.9390},
        {'id': 1, 'e_m': 0.562971, 'e_o_k': [0.570285, 0.248428, 0.205822], 'p_i': 20, 'u_i': 2.1006, 'theta': 0.8173},
        {'id': 2, 'e_m': 3.713573, 'e_o_k': [0.161785], 'p_i': 40, 'u_i': 4.1560, 'theta': 0.8160},
        {'id': 3, 'e_m': 8.632418, 'e_o_k': [3.177149], 'p_i': 80, 'u_i': 1.6499, 'theta': 0.9240},
        {'id': 4, 'e_m': 6.350141, 'e_o_k': [1.148432, 1.209133], 'p_i': 20, 'u_i': 2.7624, 'theta': 0.6795},
        {'id': 5, 'e_m': 1.884564, 'e_o_k': [0.790470, 0.709314, 0.752758], 'p_i': 40, 'u_i': 2.5581, 'theta': 0.8691},
        {'id': 6, 'e_m': 0.343857, 'e_o_k': [0.687714], 'p_i': 80, 'u_i': 4.2425, 'theta': 0.7622},
        {'id': 7, 'e_m': 1.921009, 'e_o_k': [1.479393, 1.459849], 'p_i': 40, 'u_i': 4.0308, 'theta': 0.6437},
        {'id': 8, 'e_m': 0.366966, 'e_o_k': [0.034770, 0.031638, 0.035797], 'p_i': 10, 'u_i': 1.0584, 'theta': 0.7390},
        {'id': 9, 'e_m': 0.000889, 'e_o_k': [0.000561, 0.000678, 0.000539], 'p_i': 20, 'u_i': 2.2703, 'theta': 0.8205},
        {'id': 10, 'e_m': 1.232193, 'e_o_k': [0.376313, 0.227114], 'p_i': 20, 'u_i': 3.7677, 'theta': 0.6490},
        {'id': 11, 'e_m': 4.471315, 'e_o_k': [1.505480], 'p_i': 20, 'u_i': 1.3695, 'theta': 0.9615},
    ]
    B_BUDGET = 96.599987
    return processors, tasks, B_BUDGET
