"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 386.399998, "H": 80, "J": 34, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 386.399998, "H": 80, "J": 34, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 2, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 3, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 4, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 5, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 6, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 7, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.423260, 'e_o_k': [0.287860, 0.322186, 0.302034, 0.442815], 'p_i': 10, 'u_i': 4.3109, 'theta': 0.9510},
        {'id': 1, 'e_m': 4.991507, 'e_o_k': [3.424903], 'p_i': 20, 'u_i': 1.0763, 'theta': 0.9798},
        {'id': 2, 'e_m': 9.991953, 'e_o_k': [1.914947, 1.989968, 2.304020, 1.558534], 'p_i': 40, 'u_i': 4.1236, 'theta': 0.7069},
        {'id': 3, 'e_m': 24.225077, 'e_o_k': [1.879370, 2.063365, 0.920804, 2.214105], 'p_i': 80, 'u_i': 3.3661, 'theta': 0.7466},
        {'id': 4, 'e_m': 20.000000, 'e_o_k': [11.352572], 'p_i': 40, 'u_i': 4.0853, 'theta': 0.7239},
        {'id': 5, 'e_m': 2.446306, 'e_o_k': [0.006213, 0.004905, 0.004469, 0.006043], 'p_i': 10, 'u_i': 3.3611, 'theta': 0.6565},
        {'id': 6, 'e_m': 40.000000, 'e_o_k': [4.641668, 4.452837, 3.634336], 'p_i': 80, 'u_i': 1.3291, 'theta': 0.8571},
        {'id': 7, 'e_m': 9.853745, 'e_o_k': [0.998182, 1.473485, 1.355347, 1.347638], 'p_i': 40, 'u_i': 2.6129, 'theta': 0.8004},
        {'id': 8, 'e_m': 18.792629, 'e_o_k': [6.693211, 4.414097], 'p_i': 40, 'u_i': 1.9596, 'theta': 0.6646},
        {'id': 9, 'e_m': 11.180506, 'e_o_k': [1.888461, 1.237180, 1.703900, 1.272542], 'p_i': 40, 'u_i': 4.8249, 'theta': 0.7075},
        {'id': 10, 'e_m': 21.561907, 'e_o_k': [1.989130, 1.042620, 1.802611], 'p_i': 80, 'u_i': 1.0944, 'theta': 0.8061},
        {'id': 11, 'e_m': 19.652786, 'e_o_k': [7.994582, 7.700672, 4.508261, 7.435664], 'p_i': 80, 'u_i': 3.4489, 'theta': 0.7762},
    ]
    B_BUDGET = 386.399998
    return processors, tasks, B_BUDGET
