"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 35.420001, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 35.420001, "H": 40, "J": 13, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1004, "set": 4, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.219208, 'e_o_k': [0.021453, 0.019721], 'p_i': 10, 'u_i': 1.3714, 'theta': 0.8051},
        {'id': 1, 'e_m': 2.524017, 'e_o_k': [0.109026, 0.123382, 0.155599, 0.153468], 'p_i': 20, 'u_i': 1.2021, 'theta': 0.9935},
        {'id': 2, 'e_m': 4.925672, 'e_o_k': [0.209905, 0.159783, 0.174112, 0.110401, 0.141048], 'p_i': 40, 'u_i': 3.8633, 'theta': 0.6749},
        {'id': 3, 'e_m': 1.287366, 'e_o_k': [0.041029, 0.036713, 0.026527, 0.032428], 'p_i': 10, 'u_i': 1.9405, 'theta': 0.6527},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [0.164641, 0.220041, 0.230379, 0.090097], 'p_i': 20, 'u_i': 4.0552, 'theta': 0.7429},
    ]
    B_BUDGET = 35.420001
    return processors, tasks, B_BUDGET
