"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 57.960001, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1079, "set": 79, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 57.960001, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1079, "set": 79, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.068623, 'e_o_k': [0.109585, 0.077454, 0.076497], 'p_i': 10, 'u_i': 3.5200, 'theta': 0.9328},
        {'id': 1, 'e_m': 4.254867, 'e_o_k': [1.015502], 'p_i': 20, 'u_i': 3.0285, 'theta': 0.7215},
        {'id': 2, 'e_m': 14.795559, 'e_o_k': [0.927186, 1.039588, 0.592413], 'p_i': 40, 'u_i': 4.1387, 'theta': 0.8633},
        {'id': 3, 'e_m': 4.210106, 'e_o_k': [0.035051, 0.027465, 0.023476], 'p_i': 20, 'u_i': 1.5244, 'theta': 0.7720},
        {'id': 4, 'e_m': 20.000000, 'e_o_k': [1.181620, 1.002065], 'p_i': 40, 'u_i': 3.6079, 'theta': 0.9163},
    ]
    B_BUDGET = 57.960001
    return processors, tasks, B_BUDGET
