"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.600002, "H": 80, "J": 22, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 96.600002, "H": 80, "J": 22, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1011, "set": 11, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.5, 1.0]},
        {'id': 1, 'frequencies': [0.5, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.341899, 'e_o_k': [0.645726], 'p_i': 10, 'u_i': 1.6257, 'theta': 0.6026},
        {'id': 1, 'e_m': 2.453167, 'e_o_k': [0.243661, 0.203354, 0.225364], 'p_i': 20, 'u_i': 3.8662, 'theta': 0.6386},
        {'id': 2, 'e_m': 4.303667, 'e_o_k': [1.308342, 1.760494, 1.386845, 1.226156], 'p_i': 40, 'u_i': 3.8466, 'theta': 0.6364},
        {'id': 3, 'e_m': 20.600849, 'e_o_k': [1.500991, 1.657649, 1.818442, 1.704091], 'p_i': 80, 'u_i': 3.6608, 'theta': 0.7712},
        {'id': 4, 'e_m': 8.609153, 'e_o_k': [1.697562, 1.759353], 'p_i': 80, 'u_i': 1.5800, 'theta': 0.6606},
        {'id': 5, 'e_m': 3.373777, 'e_o_k': [0.259737, 0.393784], 'p_i': 20, 'u_i': 3.2630, 'theta': 0.7059},
        {'id': 6, 'e_m': 3.289673, 'e_o_k': [4.195142], 'p_i': 80, 'u_i': 1.9225, 'theta': 0.9018},
        {'id': 7, 'e_m': 12.850025, 'e_o_k': [2.147849, 1.685839], 'p_i': 80, 'u_i': 2.7718, 'theta': 0.7208},
    ]
    B_BUDGET = 96.600002
    return processors, tasks, B_BUDGET
