"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299998, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}
"""

_SPEC = '{"B": 48.299998, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 3, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1035, "set": 35, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.708707, 'e_o_k': [0.442700, 0.490400, 0.522580], 'p_i': 10, 'u_i': 4.2231, 'theta': 0.6619},
        {'id': 1, 'e_m': 7.952500, 'e_o_k': [0.955501, 0.858468, 1.495197, 1.407864, 1.021283], 'p_i': 20, 'u_i': 4.7591, 'theta': 0.9537},
        {'id': 2, 'e_m': 7.797965, 'e_o_k': [0.466915, 0.260121, 0.252501], 'p_i': 40, 'u_i': 2.1107, 'theta': 0.7410},
        {'id': 3, 'e_m': 0.111554, 'e_o_k': [0.042983, 0.048790], 'p_i': 10, 'u_i': 4.2592, 'theta': 0.7037},
        {'id': 4, 'e_m': 0.507994, 'e_o_k': [0.325231, 0.351782], 'p_i': 20, 'u_i': 4.9113, 'theta': 0.9713},
    ]
    B_BUDGET = 48.299998
    return processors, tasks, B_BUDGET
