"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.200003, "H": 40, "J": 24, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1018, "set": 18, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 193.200003, "H": 40, "J": 24, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1018, "set": 18, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 2, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 3, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 4, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 5, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 6, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
        {'id': 7, 'frequencies': [0.35, 0.6, 0.8, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.237759], 'p_i': 10, 'u_i': 1.4892, 'theta': 0.9087},
        {'id': 1, 'e_m': 4.697399, 'e_o_k': [0.555700, 0.667775, 0.798639], 'p_i': 20, 'u_i': 1.2698, 'theta': 0.8079},
        {'id': 2, 'e_m': 20.000000, 'e_o_k': [7.565371], 'p_i': 40, 'u_i': 2.1993, 'theta': 0.6966},
        {'id': 3, 'e_m': 9.267765, 'e_o_k': [0.074388, 0.077902], 'p_i': 40, 'u_i': 4.2719, 'theta': 0.7926},
        {'id': 4, 'e_m': 4.667083, 'e_o_k': [5.077400, 4.199019], 'p_i': 20, 'u_i': 4.7299, 'theta': 0.8952},
        {'id': 5, 'e_m': 2.316552, 'e_o_k': [2.231893, 2.401211], 'p_i': 10, 'u_i': 3.9362, 'theta': 0.9877},
        {'id': 6, 'e_m': 9.441670, 'e_o_k': [1.338248, 1.405329], 'p_i': 40, 'u_i': 4.5549, 'theta': 0.7301},
        {'id': 7, 'e_m': 5.000000, 'e_o_k': [1.141333, 0.534802], 'p_i': 10, 'u_i': 3.0638, 'theta': 0.7386},
        {'id': 8, 'e_m': 14.641474, 'e_o_k': [4.414707], 'p_i': 40, 'u_i': 1.2711, 'theta': 0.7010},
        {'id': 9, 'e_m': 9.259568, 'e_o_k': [7.975437, 6.364005], 'p_i': 40, 'u_i': 2.9738, 'theta': 0.8873},
        {'id': 10, 'e_m': 9.394352, 'e_o_k': [0.408681, 0.393948, 0.474363], 'p_i': 40, 'u_i': 2.0278, 'theta': 0.9564},
        {'id': 11, 'e_m': 10.000000, 'e_o_k': [0.194053, 0.167230], 'p_i': 20, 'u_i': 4.4188, 'theta': 0.6979},
    ]
    B_BUDGET = 193.200003
    return processors, tasks, B_BUDGET
