"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.860005, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1082, "set": 82, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.860005, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1082, "set": 82, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.661617, 'e_o_k': [2.749975], 'p_i': 10, 'u_i': 1.3524, 'theta': 0.8640},
        {'id': 1, 'e_m': 0.396189, 'e_o_k': [0.225239, 0.262299, 0.304840], 'p_i': 20, 'u_i': 2.3035, 'theta': 0.9854},
        {'id': 2, 'e_m': 2.196097, 'e_o_k': [0.635337, 0.755160, 0.370563], 'p_i': 40, 'u_i': 1.1414, 'theta': 0.6912},
        {'id': 3, 'e_m': 3.852123, 'e_o_k': [3.971555], 'p_i': 20, 'u_i': 1.1350, 'theta': 0.6740},
        {'id': 4, 'e_m': 6.660815, 'e_o_k': [2.032806, 3.678370], 'p_i': 40, 'u_i': 1.4970, 'theta': 0.7153},
    ]
    B_BUDGET = 41.860005
    return processors, tasks, B_BUDGET
