"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 38.640002, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1082, "set": 82, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 38.640002, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1082, "set": 82, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.7, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.107744, 'e_o_k': [2.342829], 'p_i': 10, 'u_i': 1.3524, 'theta': 0.8640},
        {'id': 1, 'e_m': 0.264126, 'e_o_k': [0.179071, 0.208535, 0.242356], 'p_i': 20, 'u_i': 2.3035, 'theta': 0.9854},
        {'id': 2, 'e_m': 1.464064, 'e_o_k': [1.014715, 1.206088, 0.591837], 'p_i': 40, 'u_i': 1.1414, 'theta': 0.6912},
        {'id': 3, 'e_m': 2.568082, 'e_o_k': [4.996063], 'p_i': 20, 'u_i': 1.1350, 'theta': 0.6740},
        {'id': 4, 'e_m': 4.440543, 'e_o_k': [3.048224, 5.515773], 'p_i': 40, 'u_i': 1.4970, 'theta': 0.7153},
    ]
    B_BUDGET = 38.640002
    return processors, tasks, B_BUDGET
