"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599994, "H": 80, "J": 26, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1057, "set": 57, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 96.599994, "H": 80, "J": 26, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1057, "set": 57, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.85, 0.9, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.85, 0.9, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.351398, 'e_o_k': [0.053548, 0.032897, 0.051570, 0.023336], 'p_i': 10, 'u_i': 2.9058, 'theta': 0.7849},
        {'id': 1, 'e_m': 1.872229, 'e_o_k': [1.341349, 0.928945, 1.225435], 'p_i': 20, 'u_i': 4.3220, 'theta': 0.7183},
        {'id': 2, 'e_m': 7.025758, 'e_o_k': [2.207580, 2.167113], 'p_i': 40, 'u_i': 1.0030, 'theta': 0.8214},
        {'id': 3, 'e_m': 16.852729, 'e_o_k': [0.511805, 0.408838], 'p_i': 80, 'u_i': 4.0571, 'theta': 0.9400},
        {'id': 4, 'e_m': 24.076203, 'e_o_k': [4.638115, 7.215497], 'p_i': 80, 'u_i': 2.2408, 'theta': 0.9127},
        {'id': 5, 'e_m': 1.236472, 'e_o_k': [0.020018], 'p_i': 10, 'u_i': 1.5632, 'theta': 0.7263},
        {'id': 6, 'e_m': 3.586956, 'e_o_k': [0.277385, 0.283663], 'p_i': 80, 'u_i': 2.1337, 'theta': 0.9681},
        {'id': 7, 'e_m': 1.240719, 'e_o_k': [2.481437], 'p_i': 80, 'u_i': 3.5977, 'theta': 0.9689},
    ]
    B_BUDGET = 96.599994
    return processors, tasks, B_BUDGET
