"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1077, "set": 77, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 10, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1077, "set": 77, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.55, 0.65, 0.8, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.55, 0.65, 0.8, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.236738, 'e_o_k': [0.252069, 0.301199, 0.284691], 'p_i': 10, 'u_i': 1.3118, 'theta': 0.7424},
        {'id': 1, 'e_m': 2.957943, 'e_o_k': [1.791347], 'p_i': 20, 'u_i': 3.5439, 'theta': 0.8396},
        {'id': 2, 'e_m': 1.939610, 'e_o_k': [3.879219], 'p_i': 40, 'u_i': 3.6665, 'theta': 0.8899},
        {'id': 3, 'e_m': 6.192974, 'e_o_k': [1.657889, 1.391581, 1.457280, 1.376225], 'p_i': 40, 'u_i': 4.5099, 'theta': 0.8628},
        {'id': 4, 'e_m': 6.502289, 'e_o_k': [0.585703, 0.577723, 0.488212], 'p_i': 20, 'u_i': 4.9531, 'theta': 0.7214},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
