"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.299999, "H": 40, "J": 11, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1077, "set": 77, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 48.299999, "H": 40, "J": 11, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1077, "set": 77, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 1.0]},
        {'id': 1, 'frequencies': [0.3, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.262727, 'e_o_k': [0.101085, 0.108391, 0.117166, 0.076710, 0.122102], 'p_i': 10, 'u_i': 1.5801, 'theta': 0.7079},
        {'id': 1, 'e_m': 4.590770, 'e_o_k': [1.478972], 'p_i': 20, 'u_i': 1.4810, 'theta': 0.9728},
        {'id': 2, 'e_m': 11.908698, 'e_o_k': [5.341463], 'p_i': 40, 'u_i': 3.8204, 'theta': 0.9775},
        {'id': 3, 'e_m': 3.675903, 'e_o_k': [0.649053, 0.899190], 'p_i': 20, 'u_i': 3.4444, 'theta': 0.8065},
        {'id': 4, 'e_m': 5.253524, 'e_o_k': [1.273260, 0.697031, 0.510806, 0.770048], 'p_i': 20, 'u_i': 1.2365, 'theta': 0.8711},
    ]
    B_BUDGET = 48.299999
    return processors, tasks, B_BUDGET
