"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300002, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1075, "set": 75, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 48.300002, "H": 40, "J": 13, "factor": "n_frq", "n_frq": 8, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1075, "set": 75, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 5.000000, 'e_o_k': [0.575988, 0.516035, 0.490760, 0.541895, 0.390421], 'p_i': 10, 'u_i': 4.5700, 'theta': 0.9139},
        {'id': 1, 'e_m': 4.679987, 'e_o_k': [1.504900, 1.382602], 'p_i': 20, 'u_i': 1.8392, 'theta': 0.9115},
        {'id': 2, 'e_m': 1.291917, 'e_o_k': [2.583834], 'p_i': 40, 'u_i': 3.6327, 'theta': 0.7463},
        {'id': 3, 'e_m': 1.013706, 'e_o_k': [0.093741, 0.105788, 0.103118, 0.136229, 0.081987], 'p_i': 20, 'u_i': 4.5821, 'theta': 0.7185},
        {'id': 4, 'e_m': 1.830175, 'e_o_k': [0.032875, 0.025657, 0.039043, 0.037185], 'p_i': 10, 'u_i': 1.1171, 'theta': 0.6574},
    ]
    B_BUDGET = 48.300002
    return processors, tasks, B_BUDGET
