"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1075, "set": 75, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 12, "factor": "n_frq", "n_frq": 12, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1075, "set": 75, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.45, 0.5, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.229466, 'e_o_k': [0.172361, 0.154763, 0.131808], 'p_i': 10, 'u_i': 2.2593, 'theta': 0.6602},
        {'id': 1, 'e_m': 1.529237, 'e_o_k': [0.639827, 0.656435], 'p_i': 20, 'u_i': 1.8392, 'theta': 0.9115},
        {'id': 2, 'e_m': 17.558555, 'e_o_k': [9.001067], 'p_i': 40, 'u_i': 3.6327, 'theta': 0.7463},
        {'id': 3, 'e_m': 3.635578, 'e_o_k': [0.137639, 0.155328, 0.151407, 0.200024, 0.120381], 'p_i': 10, 'u_i': 4.5821, 'theta': 0.7185},
        {'id': 4, 'e_m': 3.922795, 'e_o_k': [0.856658, 0.668573, 1.017374, 0.968960], 'p_i': 40, 'u_i': 1.1171, 'theta': 0.6574},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
