"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 51.52, "H": 40, "J": 15, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1098, "set": 98, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}
"""

_SPEC = '{"B": 51.52, "H": 40, "J": 15, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1098, "set": 98, "sweep": "u_mand_factor", "u_mand_factor": 0.6, "u_opt_factor": 0.5, "value": "0.6", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.5, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.5, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.326737, 'e_o_k': [0.830435, 1.039837], 'p_i': 10, 'u_i': 4.4063, 'theta': 0.7297},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [0.005330, 0.004483, 0.006738], 'p_i': 20, 'u_i': 1.4704, 'theta': 0.9775},
        {'id': 2, 'e_m': 5.217568, 'e_o_k': [0.784378], 'p_i': 40, 'u_i': 4.7651, 'theta': 0.6893},
        {'id': 3, 'e_m': 3.057163, 'e_o_k': [0.299703, 0.356581, 0.349157], 'p_i': 10, 'u_i': 2.7973, 'theta': 0.9885},
        {'id': 4, 'e_m': 1.311708, 'e_o_k': [0.269741, 0.389960, 0.260216], 'p_i': 10, 'u_i': 3.2811, 'theta': 0.9441},
    ]
    B_BUDGET = 51.520000
    return processors, tasks, B_BUDGET
