"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 15, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1098, "set": 98, "sweep": "u_mand_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 15, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1098, "set": 98, "sweep": "u_mand_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.5, 0.7, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.5, 0.7, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.065200, 'e_o_k': [0.945937, 1.184463], 'p_i': 10, 'u_i': 4.4063, 'theta': 0.7297},
        {'id': 1, 'e_m': 9.414161, 'e_o_k': [0.140270, 0.117980, 0.177319], 'p_i': 20, 'u_i': 1.4704, 'theta': 0.9775},
        {'id': 2, 'e_m': 3.681307, 'e_o_k': [0.980473], 'p_i': 40, 'u_i': 4.7651, 'theta': 0.6893},
        {'id': 3, 'e_m': 2.547636, 'e_o_k': [0.374629, 0.445726, 0.436446], 'p_i': 10, 'u_i': 2.7973, 'theta': 0.9885},
        {'id': 4, 'e_m': 0.759757, 'e_o_k': [0.337176, 0.487450, 0.325270], 'p_i': 10, 'u_i': 3.2811, 'theta': 0.9441},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
