"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300001, "H": 40, "J": 13, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1046, "set": 46, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.5}
"""

_SPEC = '{"B": 48.300001, "H": 40, "J": 13, "factor": "xi", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1046, "set": 46, "sweep": "xi", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "0.5", "xi": 0.5}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.35, 0.65, 0.75, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.35, 0.65, 0.75, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.845175, 'e_o_k': [0.489843, 0.624430], 'p_i': 10, 'u_i': 2.6501, 'theta': 0.6997},
        {'id': 1, 'e_m': 0.749980, 'e_o_k': [0.808910], 'p_i': 20, 'u_i': 4.8257, 'theta': 0.7085},
        {'id': 2, 'e_m': 18.245906, 'e_o_k': [10.399567], 'p_i': 40, 'u_i': 2.8390, 'theta': 0.5714},
        {'id': 3, 'e_m': 0.459449, 'e_o_k': [0.918899], 'p_i': 20, 'u_i': 3.1378, 'theta': 0.9653},
        {'id': 4, 'e_m': 0.988634, 'e_o_k': [0.421931], 'p_i': 10, 'u_i': 4.5142, 'theta': 0.6983},
    ]
    B_BUDGET = 48.300001
    return processors, tasks, B_BUDGET
