"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 9, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 9, "factor": "n_frq", "n_frq": 2, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1069, "set": 69, "sweep": "n_frq", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 1.0]},
        {'id': 1, 'frequencies': [0.55, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 1.625988, 'e_o_k': [0.310828, 0.511957], 'p_i': 10, 'u_i': 3.0557, 'theta': 0.9068},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [2.944733, 2.948853], 'p_i': 20, 'u_i': 2.4217, 'theta': 0.6152},
        {'id': 2, 'e_m': 3.863351, 'e_o_k': [3.288858], 'p_i': 40, 'u_i': 4.3172, 'theta': 0.7746},
        {'id': 3, 'e_m': 0.561470, 'e_o_k': [0.538470, 0.584469], 'p_i': 40, 'u_i': 2.0085, 'theta': 0.8952},
        {'id': 4, 'e_m': 9.071227, 'e_o_k': [0.175761, 0.161328, 0.172802], 'p_i': 40, 'u_i': 1.1725, 'theta': 0.8760},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
