"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.300003, "H": 40, "J": 26, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 48.300003, "H": 40, "J": 26, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.652576, 'e_o_k': [0.901629], 'p_i': 10, 'u_i': 4.2898, 'theta': 0.8940},
        {'id': 1, 'e_m': 1.740236, 'e_o_k': [0.122160, 0.184967, 0.179445], 'p_i': 20, 'u_i': 4.6480, 'theta': 0.7874},
        {'id': 2, 'e_m': 2.614054, 'e_o_k': [2.578729, 2.526915], 'p_i': 40, 'u_i': 3.5142, 'theta': 0.7540},
        {'id': 3, 'e_m': 0.460565, 'e_o_k': [0.236328, 0.343774, 0.341028], 'p_i': 10, 'u_i': 2.9013, 'theta': 0.6996},
        {'id': 4, 'e_m': 2.061613, 'e_o_k': [0.115568], 'p_i': 20, 'u_i': 3.9404, 'theta': 0.6966},
        {'id': 5, 'e_m': 1.007724, 'e_o_k': [1.788297], 'p_i': 20, 'u_i': 3.4601, 'theta': 0.7290},
        {'id': 6, 'e_m': 1.165822, 'e_o_k': [0.257428, 0.244015, 0.245871], 'p_i': 40, 'u_i': 2.7357, 'theta': 0.9764},
        {'id': 7, 'e_m': 2.046460, 'e_o_k': [0.026726], 'p_i': 10, 'u_i': 4.4563, 'theta': 0.6876},
        {'id': 8, 'e_m': 0.148446, 'e_o_k': [0.017483], 'p_i': 10, 'u_i': 4.6684, 'theta': 0.6988},
        {'id': 9, 'e_m': 0.684397, 'e_o_k': [0.442000, 0.507148], 'p_i': 20, 'u_i': 1.1442, 'theta': 0.7699},
    ]
    B_BUDGET = 48.300003
    return processors, tasks, B_BUDGET
