"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 38.639997, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 38.639997, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1023, "set": 23, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.65, 0.85, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.408238, 'e_o_k': [0.500462, 0.362591], 'p_i': 10, 'u_i': 4.6615, 'theta': 0.6774},
        {'id': 1, 'e_m': 0.430320, 'e_o_k': [0.288607, 0.322844, 0.249189], 'p_i': 20, 'u_i': 2.5264, 'theta': 0.7336},
        {'id': 2, 'e_m': 5.567627, 'e_o_k': [4.507205, 2.943191, 3.660493], 'p_i': 40, 'u_i': 1.4642, 'theta': 0.9452},
        {'id': 3, 'e_m': 2.539846, 'e_o_k': [2.367675, 2.631043], 'p_i': 20, 'u_i': 2.3811, 'theta': 0.8284},
        {'id': 4, 'e_m': 0.714772, 'e_o_k': [0.666749, 0.762796], 'p_i': 10, 'u_i': 4.2272, 'theta': 0.9006},
    ]
    B_BUDGET = 38.639997
    return processors, tasks, B_BUDGET
