"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 48.3, "H": 40, "J": 26, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1050, "set": 50, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}
"""

_SPEC = '{"B": 48.3, "H": 40, "J": 26, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 10, "rho": 0.7, "seed": 1050, "set": 50, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "10", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.55, 0.6, 0.65, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.55, 0.6, 0.65, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.058886, 'e_o_k': [0.117771], 'p_i': 10, 'u_i': 1.2657, 'theta': 0.8045},
        {'id': 1, 'e_m': 1.229415, 'e_o_k': [0.074164, 0.060622, 0.073125], 'p_i': 20, 'u_i': 1.0685, 'theta': 0.7672},
        {'id': 2, 'e_m': 11.372094, 'e_o_k': [2.641916, 2.724450, 2.495923], 'p_i': 40, 'u_i': 4.3042, 'theta': 0.8003},
        {'id': 3, 'e_m': 2.089063, 'e_o_k': [0.238861, 0.211039], 'p_i': 10, 'u_i': 4.6489, 'theta': 0.6265},
        {'id': 4, 'e_m': 0.036956, 'e_o_k': [0.033643, 0.040268], 'p_i': 10, 'u_i': 4.5939, 'theta': 0.6267},
        {'id': 5, 'e_m': 1.484310, 'e_o_k': [0.199706, 0.314045, 0.369064], 'p_i': 20, 'u_i': 1.7993, 'theta': 0.7202},
        {'id': 6, 'e_m': 0.849658, 'e_o_k': [0.028166], 'p_i': 10, 'u_i': 2.8772, 'theta': 0.9642},
        {'id': 7, 'e_m': 0.687593, 'e_o_k': [0.547516, 0.402153, 0.425516], 'p_i': 20, 'u_i': 4.9484, 'theta': 0.9858},
        {'id': 8, 'e_m': 0.899221, 'e_o_k': [0.453998], 'p_i': 20, 'u_i': 3.1371, 'theta': 0.8217},
        {'id': 9, 'e_m': 7.888578, 'e_o_k': [3.618899], 'p_i': 40, 'u_i': 3.7653, 'theta': 0.9214},
    ]
    B_BUDGET = 48.300000
    return processors, tasks, B_BUDGET
