"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 45.080001, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1040, "set": 40, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 45.080001, "H": 40, "J": 13, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1040, "set": 40, "sweep": "u_mand_factor", "u_mand_factor": 0.4, "u_opt_factor": 0.5, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.45, 0.5, 0.75, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.45, 0.5, 0.75, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.465234, 'e_o_k': [0.175333, 0.183202], 'p_i': 10, 'u_i': 3.0889, 'theta': 0.7317},
        {'id': 1, 'e_m': 2.297632, 'e_o_k': [1.737469], 'p_i': 20, 'u_i': 2.6383, 'theta': 0.7786},
        {'id': 2, 'e_m': 11.419075, 'e_o_k': [1.276937, 1.339005, 1.341130, 1.342926, 1.470224], 'p_i': 40, 'u_i': 3.4129, 'theta': 0.8575},
        {'id': 3, 'e_m': 0.610073, 'e_o_k': [0.361154, 0.274819, 0.259192, 0.324981], 'p_i': 20, 'u_i': 1.8952, 'theta': 0.7391},
        {'id': 4, 'e_m': 3.226145, 'e_o_k': [0.562904, 0.778799, 0.640347, 0.488052], 'p_i': 10, 'u_i': 2.1177, 'theta': 0.6373},
    ]
    B_BUDGET = 45.080001
    return processors, tasks, B_BUDGET
