"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 70.839999, "H": 80, "J": 31, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1075, "set": 75, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}
"""

_SPEC = '{"B": 70.839999, "H": 80, "J": 31, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1075, "set": 75, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.1, "value": "0.1", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.6, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.6, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 3.434993, 'e_o_k': [0.084145, 0.051588, 0.069725], 'p_i': 10, 'u_i': 1.8497, 'theta': 0.6381},
        {'id': 1, 'e_m': 3.741476, 'e_o_k': [0.038347, 0.062713], 'p_i': 20, 'u_i': 3.5091, 'theta': 0.9343},
        {'id': 2, 'e_m': 0.345494, 'e_o_k': [0.088024, 0.052813, 0.080521], 'p_i': 40, 'u_i': 2.3485, 'theta': 0.6378},
        {'id': 3, 'e_m': 2.185504, 'e_o_k': [0.893986, 0.855583], 'p_i': 80, 'u_i': 2.4870, 'theta': 0.8925},
        {'id': 4, 'e_m': 3.116780, 'e_o_k': [0.067157, 0.060932, 0.049009], 'p_i': 20, 'u_i': 2.8271, 'theta': 0.6117},
        {'id': 5, 'e_m': 5.986672, 'e_o_k': [0.204024, 0.401449], 'p_i': 40, 'u_i': 1.4361, 'theta': 0.7571},
        {'id': 6, 'e_m': 4.943385, 'e_o_k': [0.569813], 'p_i': 40, 'u_i': 3.2992, 'theta': 0.8669},
        {'id': 7, 'e_m': 0.043803, 'e_o_k': [0.023789, 0.017082, 0.021604, 0.025131], 'p_i': 10, 'u_i': 1.0746, 'theta': 0.7865},
    ]
    B_BUDGET = 70.839999
    return processors, tasks, B_BUDGET
