"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.200006, "H": 80, "J": 33, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 8, "rho": 0.7, "seed": 1087, "set": 87, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 193.200006, "H": 80, "J": 33, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 8, "rho": 0.7, "seed": 1087, "set": 87, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
        {'id': 2, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
        {'id': 3, 'frequencies': [0.3, 0.45, 0.5, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.400768, 'e_o_k': [0.237278, 0.187942, 0.224376, 0.151939], 'p_i': 10, 'u_i': 1.4706, 'theta': 0.9655},
        {'id': 1, 'e_m': 7.698353, 'e_o_k': [1.256576, 0.697192], 'p_i': 20, 'u_i': 2.6908, 'theta': 0.9792},
        {'id': 2, 'e_m': 9.448643, 'e_o_k': [6.316296], 'p_i': 40, 'u_i': 2.5549, 'theta': 0.7125},
        {'id': 3, 'e_m': 39.042962, 'e_o_k': [5.675753, 5.333147, 5.306679, 5.970678], 'p_i': 80, 'u_i': 4.8390, 'theta': 0.6533},
        {'id': 4, 'e_m': 7.619015, 'e_o_k': [0.198246, 0.368207, 0.415025, 0.499013], 'p_i': 20, 'u_i': 2.2557, 'theta': 0.7061},
        {'id': 5, 'e_m': 2.968699, 'e_o_k': [0.051793, 0.129063, 0.129304], 'p_i': 40, 'u_i': 4.0230, 'theta': 0.6832},
        {'id': 6, 'e_m': 4.589557, 'e_o_k': [0.373511, 0.304017, 0.291329, 0.354079], 'p_i': 20, 'u_i': 4.9167, 'theta': 0.9599},
        {'id': 7, 'e_m': 1.661064, 'e_o_k': [2.377472], 'p_i': 10, 'u_i': 3.7106, 'theta': 0.9293},
    ]
    B_BUDGET = 193.200006
    return processors, tasks, B_BUDGET
