"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 193.199999, "H": 40, "J": 34, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}
"""

_SPEC = '{"B": 193.199999, "H": 40, "J": 34, "factor": "n_prc", "n_frq": 5, "n_prc": 8, "n_tsk": 12, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 2, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 3, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 4, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 5, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 6, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 7, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 4.067093, 'e_o_k': [4.953318], 'p_i': 10, 'u_i': 3.7628, 'theta': 0.6204},
        {'id': 1, 'e_m': 6.115552, 'e_o_k': [0.175555, 0.169723, 0.183920], 'p_i': 20, 'u_i': 4.9116, 'theta': 0.7542},
        {'id': 2, 'e_m': 9.352230, 'e_o_k': [8.207431, 9.824815], 'p_i': 40, 'u_i': 1.7471, 'theta': 0.8403},
        {'id': 3, 'e_m': 4.766606, 'e_o_k': [0.550151, 0.569088], 'p_i': 10, 'u_i': 2.6805, 'theta': 0.8504},
        {'id': 4, 'e_m': 4.832927, 'e_o_k': [0.274609], 'p_i': 20, 'u_i': 2.4411, 'theta': 0.7757},
        {'id': 5, 'e_m': 4.703971, 'e_o_k': [0.027632, 0.040239, 0.040545], 'p_i': 20, 'u_i': 2.7357, 'theta': 0.9764},
        {'id': 6, 'e_m': 20.000000, 'e_o_k': [17.096325], 'p_i': 40, 'u_i': 4.4563, 'theta': 0.6876},
        {'id': 7, 'e_m': 2.400364, 'e_o_k': [1.172458], 'p_i': 10, 'u_i': 4.6684, 'theta': 0.6988},
        {'id': 8, 'e_m': 3.803106, 'e_o_k': [0.367501, 0.421668], 'p_i': 10, 'u_i': 1.1442, 'theta': 0.7699},
        {'id': 9, 'e_m': 4.822679, 'e_o_k': [0.608698, 0.770757], 'p_i': 20, 'u_i': 4.9748, 'theta': 0.8993},
        {'id': 10, 'e_m': 5.000000, 'e_o_k': [0.423446, 0.579431, 0.456848], 'p_i': 10, 'u_i': 4.7142, 'theta': 0.7405},
        {'id': 11, 'e_m': 2.387209, 'e_o_k': [0.578109], 'p_i': 10, 'u_i': 1.6647, 'theta': 0.7919},
    ]
    B_BUDGET = 193.199999
    return processors, tasks, B_BUDGET
