"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599998, "H": 40, "J": 15, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}
"""

_SPEC = '{"B": 96.599998, "H": 40, "J": 15, "factor": "n_prc", "n_frq": 5, "n_prc": 4, "n_tsk": 6, "rho": 0.7, "seed": 1032, "set": 32, "sweep": "n_prc", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 2, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
        {'id': 3, 'frequencies': [0.4, 0.6, 0.7, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.849448, 'e_o_k': [1.157902, 1.039092, 1.154744], 'p_i': 10, 'u_i': 1.1748, 'theta': 0.9350},
        {'id': 1, 'e_m': 10.000000, 'e_o_k': [2.942605], 'p_i': 20, 'u_i': 1.9085, 'theta': 0.8191},
        {'id': 2, 'e_m': 11.231878, 'e_o_k': [0.224994], 'p_i': 40, 'u_i': 2.2654, 'theta': 0.7866},
        {'id': 3, 'e_m': 3.627642, 'e_o_k': [1.585678, 1.562112, 1.144781], 'p_i': 10, 'u_i': 2.8364, 'theta': 0.9742},
        {'id': 4, 'e_m': 5.689120, 'e_o_k': [0.056898, 0.075636, 0.078449], 'p_i': 20, 'u_i': 4.9116, 'theta': 0.7542},
        {'id': 5, 'e_m': 5.740761, 'e_o_k': [0.749381, 0.695915], 'p_i': 20, 'u_i': 1.7471, 'theta': 0.8403},
    ]
    B_BUDGET = 96.599998
    return processors, tasks, B_BUDGET
