"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 96.599994, "H": 80, "J": 54, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}
"""

_SPEC = '{"B": 96.599994, "H": 80, "J": 54, "factor": "n_tsk", "n_frq": 5, "n_prc": 2, "n_tsk": 12, "rho": 0.7, "seed": 1007, "set": 7, "sweep": "n_tsk", "u_mand_factor": 0.5, "u_opt_factor": 0.5, "value": "12", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.4, 0.75, 0.9, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.643888, 'e_o_k': [1.417255], 'p_i': 10, 'u_i': 4.6571, 'theta': 0.7650},
        {'id': 1, 'e_m': 0.269002, 'e_o_k': [0.193977, 0.204280], 'p_i': 20, 'u_i': 2.8203, 'theta': 0.9139},
        {'id': 2, 'e_m': 4.220761, 'e_o_k': [0.984326, 0.980274], 'p_i': 40, 'u_i': 1.4591, 'theta': 0.6281},
        {'id': 3, 'e_m': 2.089596, 'e_o_k': [1.111415, 1.306834, 1.556694], 'p_i': 80, 'u_i': 1.5767, 'theta': 0.9944},
        {'id': 4, 'e_m': 3.718384, 'e_o_k': [0.445320, 0.287759, 0.199030, 0.268275], 'p_i': 20, 'u_i': 4.2655, 'theta': 0.9196},
        {'id': 5, 'e_m': 0.524930, 'e_o_k': [0.386298, 0.358875, 0.304688], 'p_i': 20, 'u_i': 2.4727, 'theta': 0.6235},
        {'id': 6, 'e_m': 0.105020, 'e_o_k': [0.126794], 'p_i': 10, 'u_i': 2.8663, 'theta': 0.9141},
        {'id': 7, 'e_m': 3.746340, 'e_o_k': [0.130941, 0.155976, 0.133829], 'p_i': 20, 'u_i': 3.5394, 'theta': 0.9328},
        {'id': 8, 'e_m': 0.630366, 'e_o_k': [0.214734], 'p_i': 10, 'u_i': 4.4106, 'theta': 0.7972},
        {'id': 9, 'e_m': 1.593007, 'e_o_k': [0.972578, 0.423481, 0.726743, 0.563509], 'p_i': 80, 'u_i': 1.7356, 'theta': 0.7138},
        {'id': 10, 'e_m': 2.240708, 'e_o_k': [0.466030, 0.417381], 'p_i': 40, 'u_i': 4.4419, 'theta': 0.9599},
        {'id': 11, 'e_m': 0.415704, 'e_o_k': [0.038855, 0.041772, 0.031883, 0.049424], 'p_i': 10, 'u_i': 3.9270, 'theta': 0.6719},
    ]
    B_BUDGET = 96.599994
    return processors, tasks, B_BUDGET
