"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 41.860001, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1074, "set": 74, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}
"""

_SPEC = '{"B": 41.860001, "H": 40, "J": 9, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1074, "set": 74, "sweep": "u_mand_factor", "u_mand_factor": 0.3, "u_opt_factor": 0.5, "value": "0.3", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.4, 0.55, 0.6, 0.8, 1.0]},
        {'id': 1, 'frequencies': [0.4, 0.55, 0.6, 0.8, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.336465, 'e_o_k': [1.619265, 0.989679], 'p_i': 10, 'u_i': 3.5789, 'theta': 0.9059},
        {'id': 1, 'e_m': 1.606634, 'e_o_k': [1.671421, 1.541848], 'p_i': 20, 'u_i': 4.4277, 'theta': 0.7780},
        {'id': 2, 'e_m': 1.800785, 'e_o_k': [0.011212, 0.011517, 0.011234], 'p_i': 40, 'u_i': 4.3156, 'theta': 0.8465},
        {'id': 3, 'e_m': 8.626107, 'e_o_k': [9.075766], 'p_i': 40, 'u_i': 2.8175, 'theta': 0.8068},
        {'id': 4, 'e_m': 1.013979, 'e_o_k': [0.765729, 0.478301, 0.783929], 'p_i': 40, 'u_i': 2.2589, 'theta': 0.7004},
    ]
    B_BUDGET = 41.860001
    return processors, tasks, B_BUDGET
