"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 57.96, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1086, "set": 86, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}
"""

_SPEC = '{"B": 57.96, "H": 40, "J": 10, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 5, "rho": 0.7, "seed": 1086, "set": 86, "sweep": "u_mand_factor", "u_mand_factor": 0.8, "u_opt_factor": 0.5, "value": "0.8", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.6, 0.75, 0.8, 0.95, 1.0]},
        {'id': 1, 'frequencies': [0.6, 0.75, 0.8, 0.95, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 2.444915, 'e_o_k': [0.027053, 0.029336], 'p_i': 10, 'u_i': 2.6559, 'theta': 0.7674},
        {'id': 1, 'e_m': 4.736153, 'e_o_k': [0.481491, 0.377538, 0.416553], 'p_i': 20, 'u_i': 3.3688, 'theta': 0.9146},
        {'id': 2, 'e_m': 15.080953, 'e_o_k': [1.312355], 'p_i': 40, 'u_i': 2.0974, 'theta': 0.7224},
        {'id': 3, 'e_m': 9.667080, 'e_o_k': [1.395518], 'p_i': 40, 'u_i': 2.2542, 'theta': 0.6249},
        {'id': 4, 'e_m': 10.000000, 'e_o_k': [0.477562, 0.519475, 0.260667], 'p_i': 20, 'u_i': 2.9688, 'theta': 0.6150},
    ]
    B_BUDGET = 57.960000
    return processors, tasks, B_BUDGET
