"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 122.360006, "H": 80, "J": 40, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1027, "set": 27, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.9, "value": "0.9", "xi": 0.6}
"""

_SPEC = '{"B": 122.360006, "H": 80, "J": 40, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1027, "set": 27, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.9, "value": "0.9", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.511073, 'e_o_k': [0.155629, 0.165738, 0.149178], 'p_i': 10, 'u_i': 2.9383, 'theta': 0.7627},
        {'id': 1, 'e_m': 0.309669, 'e_o_k': [0.619338], 'p_i': 20, 'u_i': 4.6487, 'theta': 0.6411},
        {'id': 2, 'e_m': 0.160006, 'e_o_k': [0.173209, 0.146803], 'p_i': 40, 'u_i': 4.8680, 'theta': 0.9878},
        {'id': 3, 'e_m': 0.553089, 'e_o_k': [0.270839], 'p_i': 80, 'u_i': 2.7918, 'theta': 0.9942},
        {'id': 4, 'e_m': 3.390542, 'e_o_k': [1.079014, 0.989693, 0.970988, 0.602362], 'p_i': 10, 'u_i': 3.7283, 'theta': 0.9086},
        {'id': 5, 'e_m': 6.579907, 'e_o_k': [0.973551, 1.656597, 0.962957, 1.629820], 'p_i': 80, 'u_i': 1.3751, 'theta': 0.7900},
        {'id': 6, 'e_m': 0.490206, 'e_o_k': [0.070127, 0.055666], 'p_i': 10, 'u_i': 1.1291, 'theta': 0.8876},
        {'id': 7, 'e_m': 4.521719, 'e_o_k': [3.685213], 'p_i': 10, 'u_i': 2.8776, 'theta': 0.6239},
    ]
    B_BUDGET = 122.360006
    return processors, tasks, B_BUDGET
