"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 90.15999, "H": 80, "J": 40, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1027, "set": 27, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.4, "value": "0.4", "xi": 0.6}
"""

_SPEC = '{"B": 90.15999, "H": 80, "J": 40, "factor": "u_opt_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1027, "set": 27, "sweep": "u_opt_factor", "u_mand_factor": 0.5, "u_opt_factor": 0.4, "value": "0.4", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.65, 0.7, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.65, 0.7, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.511073, 'e_o_k': [0.069168, 0.073661, 0.066301], 'p_i': 10, 'u_i': 2.9383, 'theta': 0.7627},
        {'id': 1, 'e_m': 0.309669, 'e_o_k': [0.619338], 'p_i': 20, 'u_i': 4.6487, 'theta': 0.6411},
        {'id': 2, 'e_m': 0.160006, 'e_o_k': [0.173209, 0.146803], 'p_i': 40, 'u_i': 4.8680, 'theta': 0.9878},
        {'id': 3, 'e_m': 0.553089, 'e_o_k': [0.120373], 'p_i': 80, 'u_i': 2.7918, 'theta': 0.9942},
        {'id': 4, 'e_m': 3.390542, 'e_o_k': [0.479562, 0.439864, 0.431550, 0.267716], 'p_i': 10, 'u_i': 3.7283, 'theta': 0.9086},
        {'id': 5, 'e_m': 6.579907, 'e_o_k': [0.432689, 0.736265, 0.427981, 0.724364], 'p_i': 80, 'u_i': 1.3751, 'theta': 0.7900},
        {'id': 6, 'e_m': 0.490206, 'e_o_k': [0.031167, 0.024740], 'p_i': 10, 'u_i': 1.1291, 'theta': 0.8876},
        {'id': 7, 'e_m': 4.521719, 'e_o_k': [1.421388], 'p_i': 10, 'u_i': 2.8776, 'theta': 0.6239},
    ]
    B_BUDGET = 90.159990
    return processors, tasks, B_BUDGET
