"""Auto-generated USRT testcase -- DO NOT EDIT BY HAND.

Generated by usrt.gen following paper Section VII.A.
Each task carries 'theta': the per-task ACET multiplier (VII.A.2(f)); a segment
completes in theta * its worst-case execution time.

Provenance:
{"B": 77.279998, "H": 80, "J": 23, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1019, "set": 19, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}
"""

_SPEC = '{"B": 77.279998, "H": 80, "J": 23, "factor": "u_mand_factor", "n_frq": 5, "n_prc": 2, "n_tsk": 8, "rho": 0.7, "seed": 1019, "set": 19, "sweep": "u_mand_factor", "u_mand_factor": 0.2, "u_opt_factor": 0.5, "value": "0.2", "xi": 0.6}'


def testcase():
    processors = [
        {'id': 0, 'frequencies': [0.3, 0.35, 0.45, 0.55, 1.0]},
        {'id': 1, 'frequencies': [0.3, 0.35, 0.45, 0.55, 1.0]},
    ]
    tasks = [
        {'id': 0, 'e_m': 0.653766, 'e_o_k': [0.286402, 0.340024, 0.312662, 0.298728], 'p_i': 10, 'u_i': 3.5957, 'theta': 0.9524},
        {'id': 1, 'e_m': 1.471460, 'e_o_k': [0.565383, 0.980255, 0.545475, 0.771802], 'p_i': 20, 'u_i': 1.4259, 'theta': 0.8995},
        {'id': 2, 'e_m': 3.800043, 'e_o_k': [3.945792, 3.267696], 'p_i': 40, 'u_i': 3.5771, 'theta': 0.6837},
        {'id': 3, 'e_m': 1.343616, 'e_o_k': [0.956723, 1.227662], 'p_i': 80, 'u_i': 3.0047, 'theta': 0.6495},
        {'id': 4, 'e_m': 0.769361, 'e_o_k': [0.607465, 0.529188, 0.557093], 'p_i': 20, 'u_i': 4.5875, 'theta': 0.8530},
        {'id': 5, 'e_m': 2.526350, 'e_o_k': [1.229706, 1.454834, 1.270904, 1.055502], 'p_i': 40, 'u_i': 4.8130, 'theta': 0.7177},
        {'id': 6, 'e_m': 2.116217, 'e_o_k': [1.386736, 1.152068, 1.024093, 1.721311], 'p_i': 80, 'u_i': 3.6299, 'theta': 0.7717},
        {'id': 7, 'e_m': 1.693971, 'e_o_k': [2.146967, 1.806395], 'p_i': 80, 'u_i': 2.3193, 'theta': 0.9044},
    ]
    B_BUDGET = 77.279998
    return processors, tasks, B_BUDGET
